### ISSUE TITLE
Изображение в balloon

### ISSUE THREAD

**Issue by devillom** [PNKBizz/vue-yandex-map#10]
Есть тут возможность впихнуть картинку в balloon?

**Comment by PNKBizz** [comment]
Пока нет. В следующем релизе запилю. Или буду рад пулл-реквесту с этой фичей )

**Comment by PNKBizz** [comment]
Теперь есть  возможность задавать маркеры со всеми свойствами напрямую в карту. Там же можно сконфигурировать balloon

**Comment by PNKBizz** [comment]
Хотя в будущем думаю добавлю возможность конфигурировать balloon через атрибуты маркера

**Comment by devillom** [comment]
Классно, мне бы так понравилось бы
`
<ymap-marker >{тут html код}</ymap-marker >
`

**Comment by web2easy** [comment]
@devillom 

Балун и так можно конфигурировать через атрибуты маркера или через св-во `placemarks` компоонента `yandexMap`. Пример для маркера:
```html
<ymap-marker
    marker-type = "placemark"
    :coords     = "[54.7778, 38.7774]"
    :balloon    = "{
        header: '<img src=\'picture.jpg\'/>'
    }"
></ymap-marker>
```

**Comment by PNKBizz** [comment]
Отлично, не пробовал =) Но поддержку передачи верстки через слот я в любом случае реализую в следующем релизе.

**Comment by Matthew-Risedale** [comment]
А возможно ли вставить в balloon не просто верстку, а вьюшный темплейт или компонент сразу, например?

**Comment by PNKBizz** [comment]
@devillom @web2easy В общем добавил возможность добавления кастомного темплейта, только не через слот, а через пропсы. Смотрите, тестируйте, надеюсь будет полезно.
В ридми описал пример использования.
