### ISSUE TITLE
Перерисовка карты при изменение контейнера

### ISSUE THREAD

**Issue by BTakakho** [PNKBizz/vue-yandex-map#100]
Здравствуйте. Есть карта шириной 320px. При нажатии на "expand map", родительский контейнер плавно растягивается на 100%. При этом сама карта не меняет ширину под контейнер. Карта растягивается если изменить viewport или отфильтровать placemarks. 
В доках нашел метод `map.container.fitToViewport`, но он не отрабатывает или отрабатывает криво (бывает карта дублируется рядышком с основной). 
В чем может быть причина такого поведения или, может, Вы подскажете как реализовать такую карту?
**Демо**: https://codesandbox.io/s/0y06yvrk6n

**Comment by AlexeyKot** [comment]
У меня получилось решить этим методом. Просто добавил eventHandler, срабатывающий при ресайзе контейнера, который отрабатывает map.container.fitToViewport

**Comment by mirecl** [comment]
а можешь пример показать?

**Comment by PNKBizz** [comment]
Пофиксил в v0.8.4

**Comment by dzhiryakov** [comment]
Тоже столкнулся с такой проблемой. Проверял на версии 0.8.4 - также не работает
