### ISSUE TITLE
Куда добавить API ключ?

### ISSUE THREAD

**Issue by andreydos** [PNKBizz/vue-yandex-map#101]
Нигде в документации не нашел как добавить АПИ ключ. Боюсь как дело до продакшена дойдет, то всплывет надобность этот АПИ ключ добавить

**Comment by Elgorm** [comment]
Насколько я понял из кода это параметр map-link у карты https://api-maps.yandex.ru/2.1/?apikey=<ваш API-ключ>&lang=ru_RU

<yandex-map
        :coords="center"
        :controls="['trafficControl', 'geolocationControl', 'zoomControl']"
        :behaviors="['dblClickZoom', 'drag']"
        callbacks="{ click: e => {this.clickMap(e)}}"
        zoom="10"
        style="width: 100%; height: 600px;"
        map-type="map"
        map-link="https://api-maps.yandex.ru/2.1/?apikey=<ваш API-ключ>&lang=ru_RU"
        @map-was-initialized="initHandler"
      />

**Comment by Pinegin** [comment]
Это как то не очень удобно. Может добавить options в Vue.use(YmapPlugin);
Было бы легче управлять этим сразу для всех компонентов на странице.

А так придётся с каждый <yandex-map /> добавлять map-link.

**Comment by PNKBizz** [comment]
@Pinegin Добавил возможность указания опций. Будет в следующем релизе.
