### ISSUE TITLE
Некорректное отображение карты при переходе по роутам

### ISSUE THREAD

**Issue by mihan007** [PNKBizz/vue-yandex-map#102]
1. Если загружать страницу по url сразу, то карта отображается корректно
2. Если загружать страницу, перейдя на нее по роуту с другой страницы, то вот что получается(сверху исходный стейт карты, снизу карта, но с переходом к нужному адресу):
![image](https://user-images.githubusercontent.com/939122/50452040-dbb6db00-0948-11e9-9530-b2094f5a03a0.png)

**Comment by PNKBizz** [comment]
Сделайте пример в песочнице. Не могу воспроизвести проблему.

**Comment by Fasturtle1** [comment]
Бакая же проблема, долго мучился. Помогло следующее:
window.location.replace('твой роут')
