### ISSUE TITLE
Усложнение логики

### ISSUE THREAD

**Issue by borodinalive** [PNKBizz/vue-yandex-map#11]
Салют!
Хотел уточнить, зачем надо было так усложнять логику, если можно создавать placemark-и, передавая в компонент карты сразу массив подготовленных PLacemark-в. Тогда функция init может схлопнуться до довольно компактного вида
function init() {
        var vm = this;
        this.myMap = new ymaps.Map(this.ymapId, {
          center: this.coordinates,
          zoom: +this.zoom,
          behaviors: this.behaviors,
          controls: this.controls,
          type: 'yandex#${this.mapType}'
        });

        var myGeoObjects = new ymaps.GeoObjectCollection();

        vm.placemarks.forEach(function (placemark) {
          var yplacemark =
              new ymaps.Placemark(
                  placemark.coordinates,
                  placemark.properties,
                  placemark.options);

          myGeoObjects.add(yplacemark);
        })

          vm.myMap.geoObjects.add(myGeoObjects);
      }
класс Placemarks может выглядеть типа

export default class Placemark {
  constructor(lat, lon) {
    this.coordinates = [lat, lon]

    this.properties = {};
    this.options = {
      iconLayout: "default#image"
    };
  }
}

Тогда не надо ничего переопределять и можно работать со всеми свойствами карты
Может я чего-то просто недопонял?

ps/ github очень странно парсит код...

pps/ Да, и добавлять маркеры на карту лучше разом, а не по одному

**Comment by PNKBizz** [comment]
Привет!
В целом ты прав. Так было бы проще и логичнее, но (тут мне нечего написать)
В общем спасибо огромное за коммент, в следующем релизе сделаю возможность прокидывать маркеры через пропсы, оставив и возможность установки маркеров через слот (это нагляднее и проще для понимания).
Если вдруг ты захочешь сделать PR c этими изменеиями - будет очень круто! )

**Comment by PNKBizz** [comment]
Запилил  возможность задавать маркеры со всеми свойствами напрямую в карту. Спасибо за идею! )

**Comment by novweb** [comment]
@PNKBizz день добрый. вопрос как реализовать пример по ссылке с помощью вашего компонента https://tech.yandex.ru/maps/jsbox/2.1/placemark_shape
