### ISSUE TITLE
Некорректное масштабирование карты

### ISSUE THREAD

**Issue by linermgn** [PNKBizz/vue-yandex-map#110]
После отрисовки карты, если расширить окно браузера, то карта масштабируется корректно под новый размер, если потом попробовать уменьшить, то размер карты не меняется и появляется скролл
![default](https://user-images.githubusercontent.com/499078/51444382-9b186a80-1d18-11e9-8e45-51b61d607a6c.png)
Первоначальное состояние
![default](https://user-images.githubusercontent.com/499078/51444408-f0ed1280-1d18-11e9-8e72-946932d2da49.png)
Расширили экран, всё корректно
![default](https://user-images.githubusercontent.com/499078/51444394-c733eb80-1d18-11e9-91e0-edb71daccabe.png)
Сузили до первоначального состояния, размер карты не изменился, появился скролл

**Comment by Mertico** [comment]
Думаю как временное решение 
https://tech.yandex.ru/maps/jsbox/2.1/fillcontainer

А так мб что тут не так то?
https://github.com/PNKBizz/vue-yandex-map/commit/741195a92035ad62625ae1936fcbbcb9b1ec9b40

Думаю просто при ресайзе размер блока не изменяться тк дочерний блок (карта) больше

**Comment by PNKBizz** [comment]
Пофиксил в v0.8.4

**Comment by linermgn** [comment]
Нет, не исправлено.
![image](https://user-images.githubusercontent.com/499078/55321412-073ee980-5493-11e9-8343-79158c6171d9.png)
`style="width: 1348px; height: 386px;`
При расширении контейнера ширина растёт, а при сужении остаётся прежней и появляется скролл.

**Comment by PNKBizz** [comment]
Нужен пример в песочнице. Не смог воспроизвести у себя

**Comment by Yulms** [comment]
Подобное поведение наблюдал, когда карта находилась внутри fieldset - браузерный стиль имеет свойство min-inline-size: min-content;
Для предотвращения изменить min-content на другое значение или просто установить min-width
