### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by idegart** [PNKBizz/vue-yandex-map#111]
Добрый день!
Не знаю в чем именно может быть проблема, так что сразу к делу)

Установил компонент, карта отрендерилась, все гуд
Решил использовать также геокодер

После недолгих поисков выяснил что он установлен вместе с картой, так что решил попробовать использовать и все получилось

Но потом день через день начала падать ошибка 429
Почитал что есть ограничение на 25к запросов в день, но я как разработчик не могу столько использовать чисто физически)

Решил может дело в том что крутится это все на localhost и есть еще куча таких как я и они там что то мутят и вылазят за ограничение, ок

Создал свой YANDEX_API_KEY в яндексе, но это не принесло мне результатов...

При этом заметил, что карта добавляется без token'a:
`<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" async="" defer=""></script>`,
Хотя я указал его при инициализации:

```
import YandexMapPlugin from 'vue-yandex-maps'
Vue.use(YandexMapPlugin, {
    apiKey: process.env.MIX_YANDEX_API_KEY, // на строку заменял - все так же
    lang: 'ru_RU',
    version: '2.1'
})
```

**Comment by Ellanskii** [comment]
@idegart решил как-то? столкнулся с такой же проблемой
