### ISSUE TITLE
Центральные координаты карты

### ISSUE THREAD

**Issue by cerutisi** [PNKBizz/vue-yandex-map#112]
У меня вопрос. Как динамически получать координаты центра карты?

**Comment by GoogyWoogy** [comment]
`<yandex-map
                        @map-was-initialized="initHandler">
</yandex-map>

 methods: {
            initHandler(obj) {
                   obj.events.add('actionend', function (e) {
                        let canter = e.originalEvent.target.getCenter()
                     });
            });
}
`
Такой вариант должен работать

**Comment by Zmhan-github** [comment]
obj.events.add('actionend', function (e) {
                        let center = obj.getCenter().reverse()
                     });
