### ISSUE TITLE
Интерфейс placemarks не совпадает с интерфейсом api (?)

### ISSUE THREAD

**Issue by salmasov** [PNKBizz/vue-yandex-map#113]
Испытываю огромные проблемы с добавлением полигонов через :placemarks у компонента. Дергал полигоны из json-файлов ЯндексКарты-Конструктора, т.е. уверен что использую корректный интерфейс
Как бороться? Подскажите, пожалуйста

**Comment by PNKBizz** [comment]
К сожалению через :placemarks можно добавлять только маркеры типа `placemark`
