### ISSUE TITLE
Error in callback for watcher "zoom": "TypeError: this.myMap.setZoom is not a function"

### ISSUE THREAD

**Issue by Zmhan-github** [PNKBizz/vue-yandex-map#116]
В чем может быть проблема?

```

      <yandex-map
          :zoom="zoom"
      ....
      ></yandex-map>

// hooks

created() {
  navigator.geolocation.getCurrentPosition(this.handleGeolocation)
}
methods: {

  handleGeolocation(event) {
     event -> for get native Coords
      ---
      this.$store.dispatch('geolocation/setZoom', 16) // Error
       or 
      this.zoom = 16 // Error
      ---
   }
}
```

> Error:
> 
> [Vue warn]: Error in callback for watcher "zoom": "TypeError: this.myMap.setZoom is not a function"
> 
> TypeError: this.myMap.setZoom is not a function
>

**Comment by araimbekoff** [comment]
Проблема актуальна для меня тоже

**Comment by PNKBizz** [comment]
Посмотрю в чем проблема.

**Comment by windstep** [comment]
Проблема все еще актуальна.

**Comment by justLbee** [comment]
Подтверждаю. Если храню данные настроек на сервере, при получении, все выстраивается как надо но консоль пестрит Error in callback for watcher "zoom": "TypeError: this.myMap.setZoom is not a function".
`
mutations: {
  update_zoom(state, value) {
      state.map_zoom = value || 15;
  },
},
actions: {
   ... {
      commit('update_zoom', response.mapZoom);
  }
}
`

**Comment by zezic** [comment]
Как временное решение проблемы - подпишитесь на событие 'map-was-initialized' от компонента 'yandex-map', после чего производите манипуляции с зумом и прочим.
Автору в компоненте карты могу предложить либо вешать вотчеры динамически после инициализации объекта `this.myMap`, либо защитить работу вотчеров проверками готовности этого объекта.
