### ISSUE TITLE
KML support

### ISSUE THREAD

**Issue by heihachi88** [PNKBizz/vue-yandex-map#119]
Is it possible to use kml files with this plugin?

**Comment by PNKBizz** [comment]
You may to work with map instance and use kml with native ymaps methods. https://tech.yandex.com/maps/jsbox/2.1/geoxml_display

**Comment by heihachi88** [comment]
Я попробовал вот так:

```
ymaps.geoXml.load('http://openflights.org/demo/openflights-sample.kml')
```
Но плагина  geoXml нет, как его можно корректно подключить? Тупо скриптом подключить?
