### ISSUE TITLE
Как отловить клик по маркеру?

### ISSUE THREAD

**Issue by voroncv** [PNKBizz/vue-yandex-map#12]
Привет, есть ли способ как отследить когда пользователь кликнул по маркеру на карте?

**Comment by PNKBizz** [comment]
Привет. На этой неделе выкачу релиз. Можно будет передавать функцию-обработчик для о любого события

**Comment by PNKBizz** [comment]
Добавлен атрибут on-click для маркера, а также возможность задавать маркеры со всеми свойствами напрямую в карту.

**Comment by voroncv** [comment]
Спасибо большое, но есть 1 проблема. Когда отдаляем карту и на маркере вместо конкретного объекта появляется группа из нескольких, то по клику на них в консоли ошибка

**Comment by PNKBizz** [comment]
Это баг. Буду чинить ) Спасибо за фидбэк! Обещаю в скором времени пофиксить.

**Comment by PNKBizz** [comment]
Исправлено в версии 0.4.2

**Comment by PNKBizz** [comment]
Кстати, немного изменился способ передачи коллбэка. Теперь можно несколько событий отлавливать

**Comment by astreiko-egor** [comment]
Добрый вечер, можно ли увидеть пример, как отследить клик по маркеру ?
