### ISSUE TITLE
Ошибка на статической странице

### ISSUE THREAD

**Issue by Sergey-Ssn** [PNKBizz/vue-yandex-map#121]
Привет,
Использую на статичных страницах (использую пререндер) возникает ошибка если обновить страницу или зайти напрямую https://yadi.sk/i/L7Far7sQgWBppA

Живой пример http://appvue.pickstyle.ru/contacts/ 
`<div id="map" class="map-contacts">
      <yandex-map
      zoom="12"
      class="ymap"
      :coords="coords"
      :scroll-zoom=false
      :controls="[]"

      >
      <ymap-marker
        marker-type="placemark"
        :coords="coords"
        :balloonTemplate = "balloonTemplate"
        markerId = '1'
        :icon="{
          layout: 'default#image',
          imageHref: '/static/images/contacts/map-marker.png',
          imageSize: [66, 90],
          imageOffset: [-23, -110]
        }"
        >
      </ymap-marker>
      </yandex-map>
    </div>

...

  data () {
    return {
        coords: [52.947023, 38.589711],
        zoomMap: 12,
        balloonTemplate:'',
        properties: {}, // define properties here
        options: {}, // define options here
    }
  }`

**Comment by PNKBizz** [comment]
Карта должна рендериться на клиенте.
