### ISSUE TITLE
[Вопрос] Как передать токен (api key)?

### ISSUE THREAD

**Issue by batFormat** [PNKBizz/vue-yandex-map#123]
При использовании карты таким способом, подскажите пожалуйста, как передать apiKey?

```
import { yandexMap, ymapMarker } from 'vue-yandex-maps'
new Vue({
  components: { yandexMap, ymapMarker }
})
```

**Comment by dmitrytarassov** [comment]
Возможность добавлена: https://github.com/PNKBizz/vue-yandex-map#register-component
Можно закрывать таск.
