### ISSUE TITLE
@map-was-initialized возвращает исходный инстанс карты (без маркеров) @map-was-initialized returns initial 'map' instance (without placemark geoObjects on it)

### ISSUE THREAD

**Issue by BogdanovArt** [PNKBizz/vue-yandex-map#124]
Возможно я упускаю что-то очевидное, но как в таком случае обращаться к геообъектам карты 
Насколько я понял из YMap.js карта сначала запускает @map-was-initialized когда маркеры еще не созданы, а потом просто добавляет их уже после инициализации.
Возможно это так и должно работать, т.к. маркеры меняются на лету.
Но вопрос обращения к геообъектам остается тем же. Я, например пытаюсь вызвать у маркера Balloon.open(). Но даже не могу пока что обратиться к нему.

Не уверен стоит ли уточнять, но открытие балуна я пытаюсь запустить из внешнего компонента. по клику, разумеется всё работает. 
```jsx
<yandex-map
    :coords="coordinates"
    zoom="10"
    :style="{ height: '400px' }"
    :controls="[]"
    :scroll-zoom="false"
    :zoom-control="{
       visible: true
    }"
    @map-was-initialized="mapLoaded"
  >
    <ymap-marker
      v-for="(mark, id) in stores"
      :key="id"
      :marker-id="id"
      :marker-type="mark.markerType"
      :coords="mark.coords"
      :balloon-template="balloons[id]"
      :icon="icon"
      :callbacks="{
         click: () => setCurrentMarker(id)
       }"
     />
  </yandex-map>
```

**Comment by BogdanovArt** [comment]
Как я и предполагал, я все же упустил очевидное. Маркеры возвращенного инстанса хранятся не напрямую в списке геообъектов карты, а, в зависимости от установленных опций, в кластере, либо objectManager-е.

**Comment by NathanielBumppo** [comment]
не подскажете, при стандартных настройках, в initHandler(obj) где искать балуны? Потому что obj.balloon.open() открывает пустой

**Comment by BogdanovArt** [comment]
```js
mapInstance.geoObjects.get(0).get(n).balloon.open()
```

в данном случае mapInstance - инстанс карты, полученный в @map-was-initialized
.geoObjects.get(0) - получает кластер, содержащий в себе объекты меток 
.get(n) - получает саму метку 
и с ней уже можно работать её методами

у вас может не быть кластера и геообъекты меток будут доступны сразу на уровне mapInstance.geoObjects
