### ISSUE TITLE
objectManager set Markers bug?

### ISSUE THREAD

**Issue by pandemozhno** [PNKBizz/vue-yandex-map#127]
Когда устанавливаю  useObjectManager некоторые маркеры на карте начинают вести себя странным образом, предыдущий маркер используя свои координаты берёт данные для контента иконки из следующего. Также клик по такому маркеру открывает балун на следующего, по индексу в массиве, координатах. При зуме карты такие маркеры то исчезаю то появляются. В чём може быть дело? Без параметра useObjectManager всё работает как надо

**Comment by PNKBizz** [comment]
Воспороизведите пример в песочнице, пожалуйста.

**Comment by pandemozhno** [comment]
Постараюсь сделать на днях. Спасибо
