### ISSUE TITLE
Добавить инструкцию по сборке/тестированию проекта

### ISSUE THREAD

**Issue by zlodes** [PNKBizz/vue-yandex-map#128]
Не хватает инструкции по сборке и CONTRIBUTE-гайда.
После запуска `npm run build` и использовании полученного бандла, в Nuxt получаем ошибку: 
```
Cannot read property 'install' of undefined
```

Скорее всего, собирается неправильно.

**Comment by PNKBizz** [comment]
Да, были косяки. Спасибо.
