### ISSUE TITLE
Ошибка при смене координат карты(ERR_ABORTED 400)

### ISSUE THREAD

**Issue by Fasturtle1** [PNKBizz/vue-yandex-map#129]
Иногда при заходе на страницу с картой она не прогружается. В консоле ошибка:  
![image](https://user-images.githubusercontent.com/35260551/56203675-388feb80-6035-11e9-8b62-e360cac38142.png)
Хэдер ошибки:  
![image](https://user-images.githubusercontent.com/35260551/56203831-84429500-6035-11e9-94cb-db9c0dae5897.png)

Как видно в параметрах запроса не передаются координаты из-за этого возвращает ошибку  
![image](https://user-images.githubusercontent.com/35260551/56203889-afc57f80-6035-11e9-9886-6a64998a09f8.png)

компонент плагина объявлен в коде:
![image](https://user-images.githubusercontent.com/35260551/56204041-07fc8180-6036-11e9-991c-7c30446f7537.png)

Замечу что **Z** в параметрах запроса равен нулю. А у меня он жёстко задан 12 и не меняется в коде.

Кто сталкивался с подобной ошибкой подскажите как исправить и что тригерит этот *пустой* запрос. Спасибо.

PS: в ходе проверок обнаружил что этот запрос отсылается при смене центра карты "**переменная coords**". Однако значения переменной(массив из двух координат) валидны. 

PPS: Ошибка возникает когда у компонента <yandex-map> сменяются координаты в момент когда его **высота** или **ширина** равны нулю. Так же если прописан **v-show="false"**. С **v-if="false"** всё работает нормально так как компонент еще не инициализирован.

**Comment by PNKBizz** [comment]
Воспроизведите пример в песочнице, у себя не смог поймать такую же ошибку
