### ISSUE TITLE
Cluster-callback

### ISSUE THREAD

**Issue by bomba65** [PNKBizz/vue-yandex-map#130]
Добрый день!
Я хотел добавить event на click по карте с помощю cluster-callbacks.
Написал вот так:
<yandex-map
        :coords="[0, 0]"
        zoom="1"
        style="width: 100%; height: 100%;"
        @click="addMarker"
        :placemarks="placemarks"
        :cluster-callbacks="{ click: addMarker }"
        >
</yandex-map>

Но почему то он реагирует. Может быть я что-то не правильно делаю?

**Comment by PNKBizz** [comment]
Да, карта не эмитит событие `click`. В новом релизе постараюсь добавить эту фичу. Будет до 15 мая.

**Comment by PNKBizz** [comment]
добавил эмит события `click` в версии 0.8.5

**Comment by belazz** [comment]
Cluster callback'и таки не работают
`        <yandex-map
                :coords="coords"
                :zoom="zoom"
                :style="this.viewport"
                :placemarks="placemarks"
                :init-without-markers="true"
                @map-was-initialized="onInit"
                :cluster-callbacks="clusterCallbacks"
        >`

`                clusterCallbacks: {
                    click: function (event) {
                        console.log('click');
                    },
                    contextmenu: function (event) {
                        console.log('menu');
                    },
                    open: function (event) {
                        console.log('open');
                    },
                },`

ни один из ивентов не срабатывает

**Comment by SergeyNekrasoff** [comment]
cluster-callbacks не работает, 
Добавляю в yandex-maps
```:cluster-callbacks="{ click: test }"```
в методе
```test() { console.log('test') }```

Как пофиксить без плагина, может кто подскажет?

**Comment by PNKBizz** [comment]
Пофиксил описание в ридми. Нужно дополнительно указывать имя кластера. Т.е.
`{clusterName: {click: callback}}`
