### ISSUE TITLE
Options не работает

### ISSUE THREAD

**Issue by fobiasmog** [PNKBizz/vue-yandex-map#131]
Не могу изменить язык и в целом опции для Map из https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Map-docpage/

https://codepen.io/fobiasmog/pen/OYVXwK

**Comment by PNKBizz** [comment]
Привет! Прошу прощения, эта фича еще не зарелизилась, до 15 числа будет новый релиз.

**Comment by fobiasmog** [comment]
Понял, спасибо :)
