### ISSUE TITLE
Проблема с markerType 

### ISSUE THREAD

**Issue by yuvmironov** [PNKBizz/vue-yandex-map#132]
Доброго времени суток. При работе с плагином в консоли появляется ошибка 
`Uncaught TypeError: ymaps[e.markerType] is not a constructor
    at b (vue-yandex-maps.js?e151:1)
    at VueComponent.createMarkers (vue-yandex-maps.js?e151:1)
    at VueComponent.setMarkers (vue-yandex-maps.js?e151:1)
    at VueComponent.eval (vue-yandex-maps.js?e151:1)`

Вот исходник
`<yandex-map
                class="Map-Map"
                :coords="[51.533103, 46.034158]"
                zoom="13"
                >
                <ymap-marker v-for='element in placemarks'
                  :key=element.id
                  :markerId=element.id
                  marker-type="placemark"
                  :hint-content=element.hint
                  :coords=element.coords
                  :balloon=element.balloon
                  :options=element.options
                  :properties=element.properties
                  :callbacks=element.callbacks
                >
                </ymap-marker>
              </yandex-map>`

Уже весь мозг взорвал, пробовал разные варианты написания. При этом карта работает и все отображает.

**Comment by PNKBizz** [comment]
Посмотрю, спасибо.

**Comment by PNKBizz** [comment]
Не получается воспроизвести. Нужен пример с ошибкой в песочнице

**Comment by yuvmironov** [comment]
Я приношу свои извинения, но проблема разрешилась сама собой. Что это было я тоже не смог понять.

**Comment by yuvmironov** [comment]
Ан не, не решилась. Прошу прощения. Чуть позже в личку напишу где можно посмотреть код.

**Comment by yuvmironov** [comment]
Вечер добрый, поделитесь если не сложно вашей почтой, я добавлю вас к
репозиторию. В песочнице не получается воссоздать ошибку

С уважением,
Миронов Юрий Владимирович
тел: +7 916 841 8667
mail: yuvmironov@gmail.com




вс, 12 мая 2019 г. в 13:38, PNKBizz <notifications@github.com>:

**Comment by SergeyNekrasoff** [comment]
Напишите как последовательно сначала подгрузить карты, а затем placemarks? Столкнулся с такой же проблемой и судя по гуглению, placemarks подгружаются раньше карт и это только на вложенных компонентах.

**Comment by SergeyNekrasoff** [comment]
Выяснилось, что если убрать :placemarks из yandex-map и поставить проверку на наличия координат, ошибки не будет!
