### ISSUE TITLE
Создать шаблон для кластера (TypeError: Cannot read property 'createClass' of undefined)

### ISSUE THREAD

**Issue by dickkharper** [PNKBizz/vue-yandex-map#133]
`<yandex-map 
            zoom="9" 
            :coords="[54.62896654088406, 39.731893822753904]"
            :cluster-options="{ 
            1: {
                clusterDisableClickZoom: true,
                openBalloonOnClick: false,
                clusterIconContentLayout: clusterIconContentLayout,
                clusterIcons: [{
                    href: clusterIcon,
                    size: [40, 40],
                    offset: [-20, -20],
                    color: 'white'
                }]
            }}" 
            style="width: 100%; height: 100%;"
            @map-was-initialized="initHandler">`

`initHandler: function(map) {
            clusterIconContentLayout = map.templateLayoutFactory.createClass('{{ properties.geoObjects.length }}')
        }`

**Comment by PNKBizz** [comment]
Можете сделать пример в песочнице?
