### ISSUE TITLE
Как получить ObjectManager?

### ISSUE THREAD

**Issue by mpgm** [PNKBizz/vue-yandex-map#135]
Можно ли как-то получить экземпляр ObjectManager?

**Comment by PNKBizz** [comment]
Не нашел как можно сделать это из карты, пользуясь АПИ Яндекса. Попробую возвращать его вместе в картой при инициализации.

**Comment by mpgm** [comment]
` const objectManager = myMap.geoObjects.get(0);`
Вот так вроде получилось

**Comment by Zorii4** [comment]
Так не получается. Может появились какие-то новые другие способы?

**Comment by Zorii4** [comment]
0.11.15
