### ISSUE TITLE
Возможность изменить coordorder

### ISSUE THREAD

**Issue by pavel-pavel** [PNKBizz/vue-yandex-map#136]
https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/meta-docpage/#field_detail__coordinatesOrder

Нет возможности изменить coordorder

**Comment by PNKBizz** [comment]
Добавлю в след. билде

**Comment by PNKBizz** [comment]
Можете задавать `coordorder` в аттрибуте `settings`. В ридми будет добавлено чуть позже
