### ISSUE TITLE
Как добавить кастомную кнопку на карту?

### ISSUE THREAD

**Issue by SergeyNekrasoff** [PNKBizz/vue-yandex-map#137]
Пытаюсь добавить кнопку на карту, пробовал вот так

`const btn = this.$refs.map.myMap.control.Button("Кнопка")`
 `this.$refs.map.myMap.controls.add(btn, {`
    `float: 'left'`
 `})`
и так
`const btn = obj.control.Button("Кнопка")`
 `obj.controls.add(btn, {`
    `float: 'left'`
 `})`
при инициализации в методе @map-was-initialized.

Прилетает ошибка 

> Cannot read property 'Button' of undefined

Подскажите как решить, куда копать?

**Comment by mosinve** [comment]
Копать в документацию API
```js
methods: {
    initHandler(map) {
      const btn = new ymaps.control.Button("Кнопка");
      map.controls.add(btn, {
        float: 'left',
        floatIndex: 100
      });
   }
}
```

**Comment by SergeyNekrasoff** [comment]
> Копать в документацию API Яндекс.Карт
> 
Я в итоге реализовал через свойство autoFitToViewport чтобы карта подстраивалась под размер контейнера по клику на кнопку. Но спасибо за пример, как попробую - закрою issue.
