### ISSUE TITLE
Перевод новой документации на английский.

### ISSUE THREAD

**Issue by PNKBizz** [PNKBizz/vue-yandex-map#138]
Новая документация доступна только на русском. Требуется помощь в переводе на английский язык.

**Comment by genius-spirit** [comment]
PNKBizz как я могу помочь с переводом? никогда не пулреквестил.

**Comment by PNKBizz** [comment]
@all-contributors please add @ivangretsky for translation

**Comment by PNKBizz** [comment]
@all-contributors please add @ivangretsky for translation
