### ISSUE TITLE
Смена координат маркера

### ISSUE THREAD

**Issue by Seokky** [PNKBizz/vue-yandex-map#140]
Использую карту для отображения выбранного юзером адреса посредством стороннего селекта, который подтягивает координаты, благополучно скармливающиеся карте. Координаты у меня вычисляются в computed-свойстве. Компонент карты и компонент маркера используют одно и то же свойство для получения координат. Проблема в том, что при изменении координат карта успешно центрируется на них, а маркер остается там, где был. Хотя, в девтулзах я убедился, что координаты в него все-таки передаются. Что самое страшное - баг плавающий, т.к. в одном интерфейсе все окей, в другом беда.

**Comment by Seokky** [comment]
Пока решил переходом на проперти placemarks, но при использовании компонента маркера проблема актуальна.

**Comment by PNKBizz** [comment]
Значит в одном из кейсов что-то не обновляется. Попробуйте воспроизвести в песочнице, посмотрим на проблему вместе

**Comment by rustam87** [comment]
Аналогичная проблема, при смене координат маркера, маркер переставляется а вот сама карта не ценрируется по этому маркеру
 Координаты центра карты тоже нужно менять при смене координат маркера или карта сама понимает что маркер переместился и нужно переместить центр?

**Comment by PNKBizz** [comment]
@rustam87 координаты центра карты и координаты маркета не зависят друг от друга

**Comment by rustam87** [comment]
Вообщем при смены координат маркера, то маркер не двигается в нужное место, то маркер двигается но карта не центрируется по маркеру, остается в прежнем положении маркера

**Comment by PNKBizz** [comment]
@rustam87 сделайте пример в песочнице, разберемся

**Comment by rustam87** [comment]
Вот сейчас этим занимаюсь

**Comment by rustam87** [comment]
https://codesandbox.io/s/vue-template-4zez4?fontsize=14

 package.json добавить
 "vue-yandex-maps": "0.8.17"

Не получается расшарить с измененным package.json

**Comment by PNKBizz** [comment]
https://codepen.io/PNKBizz/pen/qBWQbvM

Все работает.

**Comment by rustam87** [comment]
у меня работает через раз на проекте. Попробуйте в code sandbox, https://codesandbox.io/s/vue-template-4zez4?fontsize=14

**Comment by PNKBizz** [comment]
@rustam87 я смотрел. На сандбоксе маркер вообще не реагирует. Но это скорее баг песочницы. В кодепене все работает ок, поднял локально - тоже без проблем. К сожалению помочь ничем не могу (

**Comment by rustam87** [comment]
Воспроизвел
нужно сделать динамический zoom
У каждой координаты проставить zoom и сделать разброс координат например по всей Росиии,
тогда всплывают ситации , когда маркер проставляется в нужное место, но карта ене осуществляет переход к этому маркеру. 

```
<div id="app">
    <yandex-map :coords="coord" style="height: 300px; width: 100%;" :zoom="zoom" :controls="[]">
      <ymap-marker marker-id="1" marker-type="placemark" :coords="coord"/>
    </yandex-map>
    <button @click="changeCoordinates">Сменить координаты</button>

    <div>{{coord}}</div>
  </div>
```

```
new Vue({
  el: '#app',
  data() {
    return {
      coord: [54.315059, 43.957921],
      zoom: 10,
      settings: {
        apiKey: "",
        lang: "ru_RU",
        coordorder: "latlong",
        version: "2.1"
      },
      coordinates: [
        {
          lat: 54.315059,
          lon: 43.957921,
          zoom: 12
        },
        {
          lat: 53.315059,
          lon: 42.957921,
          zoom: 15
        },
        {
          lat: 54.315059,
          lon: 45.957921,
          zoom: 10
         
        },
        {
          lat: 53.315059,
          lon: 41.957921,
          zoom: 18
        },
        {
          lat: 56.915059,
          lon: 43.157921,
          zoom: 10
        }
      ]
    };
  },

  methods: {
    changeCoordinates() {
      var min = 1;
      var max = 5;
      var random = parseInt(Math.random() * (+max - +min) + +min, 10);
      console.log(random);
      var marker = this.coordinates[random];
      this.coord = [marker.lat, marker.lon];
      this.zoom = marker.zoom;
    }
  },
})
```

**Comment by rustam87** [comment]
Так что скажете?
