### ISSUE TITLE
Нет возможности менять layout кластера

### ISSUE THREAD

**Issue by VanishMax** [PNKBizz/vue-yandex-map#142]
Яндекс Javascript API позволяет выбирать между [тремя layout'ами кластера](https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/ClusterPlacemark-docpage/#ClusterPlacemark__param-options.balloonContentLayout):

- 'cluster#balloonTwoColumns' 
- 'cluster#balloonCarousel'
- 'cluster#balloonAccordion'
И плюс: к ним еще есть свои настройки, что полезно было бы иметь во vue-yandex-map.

**Comment by PNKBizz** [comment]
Принято. Реализую в одном из следующих билдов

**Comment by VanishMax** [comment]
Отбой. Перечитав документацию к АПИ и разобравшись в коде библиотеки, нашел решение:
В clusterOptions добавляем `clusterBalloonContentLayout: 'cluster#balloonAccordion'` (на примере аккордеона). А для использования возможностей аккордеона (balloonAccordionShowIcons, к примеру) пишем `clusterBalloonAccordionShowIcons: false` в опции, соответственно.

**Comment by PNKBizz** [comment]
Отлично. Спасибо, что разобрались.

**Comment by PNKBizz** [comment]
Реализовано в версии 0.8.11.
