### ISSUE TITLE
Не грузится карта в мобильном Firefox на Ios 12.

### ISSUE THREAD

**Issue by karambafe** [PNKBizz/vue-yandex-map#145]
Привет!  Спасибо за отличный плагин :)

Столкнулся с проблемой загрузки карты в мобильном Firefox для Ios.
Подключение стандартное:
```
<yandex-map
   :settings="mapSettings"
   :coords="[coordX,coordY]"
   :controls="['zoomControl', 'routeEditor']"
   :style="{ width: '100%', height: '300px' }"
   zoom="17"
   @map-was-initialized="handleInit"
   @map-initialization-started="handleStart"
>
  <ymap-marker
    :coords="[coordX,coordY]"
     marker-type="placemark"
     marker-id="ymap-marker"
  />
</yandex-map>
```

Везде все отлично работает кроме мобильного FF на ios. Пробовал на iphone 8, 8+ и 10, версия ios 12.

События map-initialization-started и map-was-initialized не вызываются, единственное что смог отловить в sentry:
`TypeError: undefined is not an object (evaluating 'this.myMap.container.fitToViewport')`

Буду рад любой помощи :)

**Comment by PNKBizz** [comment]
Могу вам только посоветовать подебажить самому... Склонируйте репозиторий, внутри есть папка `examples`, подключите напрямую index.js и попробуйте отловить ошибку именно в этом браузере.
