### ISSUE TITLE
Синхронный coords

### ISSUE THREAD

**Issue by 1001v** [PNKBizz/vue-yandex-map#148]
Здравствуйте. Нельзя ли добавить атрибуту coords поддержку модификатора .sync? Для этого при изменении координат карты внутри компонента yandex-map необходимо генерить событие "update:coords" с payload в виде координат.

**Comment by PNKBizz** [comment]
Добрый день. Опишите для чего вам нужен такой кейс?

**Comment by 1001v** [comment]
@PNKBizz для управления положением карты программно снаружи компонента.

**Comment by PNKBizz** [comment]
Так а зачем вам эмитить апдейт из компонента? Меняйте координаты и все. https://vue-yandex-maps.github.io/examples/#%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%80%D0%B0-%D0%BF%D0%BE-%D0%BAn%D0%B8%D0%BA%D1%83

**Comment by 1001v** [comment]
@PNKBizz потому что пользователь может руками сдвинуть карту, и мы получаем неконсистентные данные снаружи компонента

**Comment by PNKBizz** [comment]
Вот теперь я вас понял. Да, ок. Реализую в следующем билде. Или можете сделать PR с этой фичей для ускорения процесса.

**Comment by 1001v** [comment]
@PNKBizz к сожалению пока нет времени. На самом деле поддержка sync нужна для большинства атрибутов, которые могут быть изменены картой, например zoom.

**Comment by PNKBizz** [comment]
Да, как-то не задумывался об этом. Спасибо за идею.
