### ISSUE TITLE
"Invalid attempt to spread non-iterable instance"

### ISSUE THREAD

**Issue by artemerschow** [PNKBizz/vue-yandex-map#149]
Пару дней назад внезапно перестали собираться проекты с подключенной vue-yandex-map. Думал мой косяк, но даже взял чистый проект, подключил карту и в консоли та же самая ошибка сборки:

> patch/node_modules/vue-yandex-maps/dist/vue-yandex-maps.js:1
> (function (exports, require, module, __filename, __dirname) { function t(e){return(t="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(t){return typeof t}:function(t){return t&&"function"==typeof Symbol&&t.constructor===Symbol&&t!==Symbol.prototype?"symbol":typeof t})(e)}function e(t,e){for(var r=0;r<e.length;r++){var o=e[r];o.enumerable=o.enumerable||!1,o.configurable=!0,"value"in o&&(o.writable=!0),Object.defineProperty(t,o.key,o)}}function r(t,e,r){return e in t?Object.defineProperty(t,e,{value:r,enumerable:!0,configurable:!0,writable:!0}):t[e]=r,t}function o(t){return function(t){if(Array.isArray(t)){for(var e=0,r=new Array(t.length);e<t.length;e++)r[e]=t[e];return r}}(t)||function(t){if(Symbol.iterator in Object(t)||"[object Arguments]"===Object.prototype.toString.call(t))return Array.from(t)}(t)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance")}()}f
> SyntaxError: Unexpected token export

Не знаете что такое и как побороть?

**Comment by PNKBizz** [comment]
А можете чистый проект с этой ошибкой выложить и кинуть ссылку на репозиторий? Или архивом, как удобно.

**Comment by artemerschow** [comment]
[ssr.zip](https://github.com/PNKBizz/vue-yandex-map/files/3402041/ssr.zip) (подключена в ssr/src/pages/index.vue)
Сейчас сообразил, что этот шаблон проекта тоже с ssr, как и мой. Голый vuejs-templates/webpack с картой собирается без проблем

**Comment by PNKBizz** [comment]
Ок, посмотрю

**Comment by PNKBizz** [comment]
@artemerschow скачал ваш архив, установил зависимости, собрал. Ошибок нет...

**Comment by artemerschow** [comment]
Когда localhost:5054 открываете в консоли (в этом проекте и на страницу выводит ошибки) всё нормально?

**Comment by PNKBizz** [comment]
Это модуль только для клиента. У вас он подключается во время серверного рендеринга. В документации есть описание подключения в Nuxt. Вы можете подключать у себя, проверяя, исполняется ли код на клиенте.
