### ISSUE TITLE
Ошибка с SSR

### ISSUE THREAD

**Issue by Multoryan** [PNKBizz/vue-yandex-map#153]
Здравствуйте, столкнулся с проблемой при обновлении.
Использовал vue-yandex-maps версии 0.7.15, все хорошо работает.

Обновляю пакет до последней версии 0.8.14 и получаю ошибку примерно следующего содержания:

```
[vue-router] Failed to resolve async component default: SyntaxError: Unexpected token export
[vue-router] uncaught error during route navigation:
/srv/http/node_modules/vue-yandex-maps/dist/vue-yandex-maps.js:1
(function (exports, require, module, __filename, __dirname)
....
SyntaxError: Unexpected token export
...
```

Причем если переходы со страницы на страницу то все нормально, но если зайти по ссылке то SSR выдает лог, описанный выше.

Были ли какие то изменения, которые могли принести такие последствия?

Используется vue-server-renderer, не nuxt

**Comment by PNKBizz** [comment]
Добрый день!
Да, сейчас модуль билдится с использованием `ES modules`, поэтому его исполнение на сервере приведет к ошибке. Нужно запускать модуль на клиенте.
