### ISSUE TITLE
Определение центра из множества объектов

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#154]
Всем привет!

Нарисовалась карта с центром по умолчанию. 
После, делаю запрос на сервер, и получаю множество точек для placemark. 
Данное множество точек могут не попадать в область видимости уже отрисованной карты.

Как отцентровать карту по заданному множеству точек и вычислить значение для zoom, чтобы все помещалось на карте?

**Comment by igvnv** [comment]
Если точки уже отрисованы на карте, то можно получить прямоугольную область, в которую они входят и отцентровать карту по ней:

```
map.setBounds(map.geoObjects.getBounds());
```

Если есть только координаты, то можно воспользоваться утилитой `bounds` и передать в неё список точек:

```
let pointsList = [[30, 60], [35, 50]];
map.setBounds(ymaps.util.bounds.fromPoints(pointsList));
```

`map.setBounds` не только центрирует карту, но и устанавливает необходимый зум.

**Comment by PNKBizz** [comment]
@igvnv Спасибо за участие! )

**Comment by araimbekoff** [comment]
@igvnv , Лучший!
Спасибо! ))
