### ISSUE TITLE
Адаптация под nuxt [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered

### ISSUE THREAD

**Issue by cvaize** [PNKBizz/vue-yandex-map#155]
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/62128222-66035b00-b2ed-11e9-92b4-4cb3d615b587.png)

**Comment by cvaize** [comment]
Работает только так 
![image](https://user-images.githubusercontent.com/26907947/62128410-cd210f80-b2ed-11e9-8a84-56c65d75e74f.png)

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/guide/#nuxt-module?

**Comment by cvaize** [comment]
@PNKBizz Да я настроил так

**Comment by cvaize** [comment]
![image](https://user-images.githubusercontent.com/26907947/62128532-107b7e00-b2ee-11e9-92fb-ddfac58763f8.png)

**Comment by PNKBizz** [comment]
Хорошо

**Comment by cvaize** [comment]
@PNKBizz Ошибка появляется с подключением через modules

**Comment by PNKBizz** [comment]
Ок, посмотрю

**Comment by cvaize** [comment]
@PNKBizz Буду очень благодарен

**Comment by wiklz** [comment]
Просто попытался хотя бы example запустить
![image](https://user-images.githubusercontent.com/36482119/64852518-351f8100-d622-11e9-876a-dba1212cdba1.png)

**Comment by KevichVinc** [comment]
Ошибка так же появляется, если подключено по https://vue-yandex-maps.github.io/guide/#nuxt-module
<img width="1440" alt="Screenshot 2021-09-24 at 16 58 12" src="https://user-images.githubusercontent.com/42380658/134687200-83a1f4a9-4a4f-4b6b-a802-8b96ae2288c1.png">
<img width="664" alt="Screenshot 2021-09-24 at 17 01 40" src="https://use
<img width="486" alt="Screenshot 2021-09-24 at 17 02 49" src="https://user-images.githubusercontent.com/42380658/134687555-e90046c1-2af1-402b-bdbb-f886a911e79a.png">
r-images.githubusercontent.com/42380658/134687516-b0b653be-9970-4d50-95b5-ba71ef10a68c.png">
