### ISSUE TITLE
Проблема валидации prop coords маркера с типом Polyline

### ISSUE THREAD

**Issue by Deluss** [PNKBizz/vue-yandex-map#156]
Для построения маркера с типом Polyline, coords передается в виде массив с массивами
Array of arrays [ [latitude, longitude], [...] ] (из документации)
Но в компоненте валидатор настроен следующим образом
```
coords: {
    type: Array,
    required: true,
    validator(val) {
        return !val.filter(item => isNaN(item)).length
    }
}
```
Соответственно, в моем случае item это массив и isNaN вернет true. Поэтому при том, что всё работает и строится, в консоли всегда ошибка 'Invalid prop: custom validator check failed for prop "coords".'

**Comment by PNKBizz** [comment]
Косяк, спасибо!
Починю
