### ISSUE TITLE
Добавьте пожалуйста события actionend, ....

### ISSUE THREAD

**Issue by cvaize** [PNKBizz/vue-yandex-map#160]
https://tech.yandex.ru/maps/archive/doc/jsapi/2.0/ref/reference/Map-docpage/#ariaid-title3

**Comment by cvaize** [comment]
Считаю целесообразным добавить часть событий

**Comment by cvaize** [comment]
sizechange, typechange, boundschange, actionend

**Comment by cvaize** [comment]
На данный момент их использовать можно вот так 
![image](https://user-images.githubusercontent.com/26907947/62934577-50f2f580-bdde-11e9-9ef9-b6bf4b3a72b1.png)

**Comment by PNKBizz** [comment]
Привет! Да, я посмотрю как лучше это сделать.
