### ISSUE TITLE
(Баг/Предложение) Двойная отрисовка точек при изменении

### ISSUE THREAD

**Issue by cvaize** [PNKBizz/vue-yandex-map#161]
При изменении данных происходит двойная отрисовка, при этом и это ВАЖНО, данные полностью перезаписываются, даже имея одинаковый id. Нужно не перезаписывать все данные, а удалять и добавлять. Эта операция будет менее производительна, поэтому тут можно добавить параметр для этого. 
![image](https://user-images.githubusercontent.com/26907947/63095471-c7c9f300-bf84-11e9-9f94-358d51dd20da.png)
![image](https://user-images.githubusercontent.com/26907947/63095430-a6690700-bf84-11e9-8df6-f97a8732ffb5.png)
![image](https://user-images.githubusercontent.com/26907947/63095508-ddd7b380-bf84-11e9-859f-0b7d43e37ea9.png)
![image](https://user-images.githubusercontent.com/26907947/63095686-49218580-bf85-11e9-9448-96fb23d79df2.png)

**Comment by PNKBizz** [comment]
Согласен, в этом отношении нужен рефакторинг. Как только появится достаточно времени - я обязательно это сделаю.

**Comment by PNKBizz** [comment]
Проверьте в версии 0.9.0
