### ISSUE TITLE
Не отрисовываются иконки меток при добавлении их циклом v-for

### ISSUE THREAD

**Issue by d-a-m** [PNKBizz/vue-yandex-map#162]
Здравствуйте. Пытаюсь добавить на карту несколько меток через v-for:
`<ymap-marker
                v-for="office in this.officesList"
                :key="office.id"
                :coords="office.coordinates"
                :balloon-template="balloonTemplate"
                :icon="this.markerIcon"
                marker-id=office.id
                marker-type="placemark"
            />`

Метки на карту добавляются, но не подтягивается шаблон для метки. Шаблон балуна, при этом, работает. Кроме того, в консоли получаю ошибку:

> Uncaught ReferenceError: ymaps is not defined

На строчке https://github.com/PNKBizz/vue-yandex-map/blob/master/src/YMap.js#L111

При этом, если в ручную добавлять несколько маркеров на карту, т.е. несколько компонентов <ymap-marker>, то всё ок, и иконки метки и балуна отрисовываются как надо.

**Comment by PNKBizz** [comment]
Сделайте пример в песочнице, пожалуйста

**Comment by d-a-m** [comment]
Пример: https://codepen.io/d-a-m/pen/xxKOVOy

**Comment by PNKBizz** [comment]
`:icon="markerIcon"`. В темплейте не нужно указывать `this`

**Comment by d-a-m** [comment]
Да, спасибо. Тем не менее, ошибка осталась.

> Uncaught ReferenceError: ymaps is not defined

**Comment by devmansurov** [comment]
> `:icon="markerIcon"`. В темплейте не нужно указывать `this`

Всё равно циклом не удаётся отобразить маркеры на карте. Что делать всё таки?
