### ISSUE TITLE
Как использовать в typescript?

### ISSUE THREAD

**Issue by mtdst** [PNKBizz/vue-yandex-map#165]
Подскажите как использовать в typescript?

**Comment by PNKBizz** [comment]
К сожалению не работал с TS и пока не планирую

**Comment by SlavMAK** [comment]
Тем кто наткнется на это, прежде чем решит проблему:
Достаточно просто объявить модуль. Для этого создайте файл vue-yandex-maps.d.ts с содержимым:
declare module 'vue-yandex-maps';
