### ISSUE TITLE
Не срабывает @click в маркере

### ISSUE THREAD

**Issue by San4aus** [PNKBizz/vue-yandex-map#167]
Приветствую, пытался прописать событие @click для маркера, однако событие не отрабатывается в методе. Пробовал отследить в консоле, но ничего не приходит.

Также ещё вопрос по поводу ballonTemplate. Скопировал ваш пример с сайта и запустил у себя, отрабатывает корректно, однако в консоле появилась ошибка:

> TypeError: ymaps.templateLayoutFactory is undefined

И сразу же ещё вопрос по балуну, можно ли передавать как-то туда свои данные (объект например)?

P.S. Заранее благодарен за ответ!

**Comment by AsuRaHan** [comment]
тоже присоединяюсь к вопросу по поводу отслеживания клика по маркеру.

**Comment by mrswylet** [comment]
Отвечаю на счет события `@click`.
Для того, что бы подписаться на событие, нужно воспользоваться пропсом callbacks - это объект, где ключом является имя события, а значением - callback-функция, напр.
 ```
{ 
    click: function() {...},
    contextmenu: anotherFunction 
}
```

[Список событий](https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/GeoObject-docpage/#events-summary) 
Скорее всего вам долго не отвечали, т.к. этот момент отражен в документации. 

На счет остального, в данный момент пояснить не могу.

P.S.: На сколько мне известно, не хорошо в одном Issues задавать несколько вопросов. Один Issues - один вопрос.

**Comment by PNKBizz** [comment]
@mrswylet спасибо за ответ
@San4aus по поводу балуна и тд - создайте лучше отдельное issue с песочницей, чтоб было наглядно. Не понял, что вы хотите
