### ISSUE TITLE
Использование `ymap` до создание карты

### ISSUE THREAD

**Issue by mrswylet** [PNKBizz/vue-yandex-map#170]
Очень часто, при создании карты, не известны координаты центра. Для таких случаев предусмотрен ymap.geocode, который может возвратить координаты города или, например, конкретного дома, и уже после мы создаем карту с данными координатами.

Проблема в том, что до создании карты, в системе нет возможности обратится к ymap.

**Comment by PNKBizz** [comment]
Привет!
Прошу прощения за delay, очень много работы помимо (
В ближайших планах ( ~пара недель ) сделать сплит плагина с возможностью отдельного подключения скрипта и карты. Тогда можно будет подключать скрипт и работать с геокодером

**Comment by mrswylet** [comment]
@PNKBizz у вас есть планы, идеи как это реализовать? 
Я сейчас пробую это сделать. Буду рад помочь и принять участие

**Comment by PNKBizz** [comment]
https://github.com/PNKBizz/vue-yandex-map/issues/134

**Comment by mrswylet** [comment]
@PNKBizz я не увидел ваш ответ и уже предложил реализацию донной фичи [Pull request](https://github.com/PNKBizz/vue-yandex-map/pull/171). Посмотрите, устроит ли вас данное решение.

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/en/guide/#ymaps-loader
