### ISSUE TITLE
В версии 0.8.17, удаляются все точки при обновлении и снова отрисовываются, предлагаю решение, нужна помощь с кластерами

### ISSUE THREAD

**Issue by cvaize** [PNKBizz/vue-yandex-map#173]
В версии 0.8.17 при обновлении любого количества точек удаляются все точки карты и снова отрисовываются. Это плохая практика. Например у меня на карте было 300 меток и перерисовать все, занимало до 4 секунд. Мне удалось сделать перерисовку только изменившихся точек в моем проекте. Я использовал marker_id, чтобы определить какие точки следует удалить и отрисовать новые точки. Я не решаюсь сделать pull request  так как мой код подходит только для обычных точек, он не учитывает кластеры и любые другие структуры карты. Кто работал с кластерами и другими структурами yandex map, можете помочь мне?

**Comment by PNKBizz** [comment]
Привет! Сейчас пилю 9-ю версию с раздельной загрузкой лоадера и другими улучшениями. Планирую выкатить сегодня-завтра и давай тогда сделаешь PR, а я доработаю для кластеров и тд, ок?

**Comment by cvaize** [comment]
@PNKBizz Спасибо, сейчас оформлю

**Comment by cvaize** [comment]
@PNKBizz Сделал пул реквест. https://github.com/PNKBizz/vue-yandex-map/pull/174

**Comment by cvaize** [comment]
Давай настроим eslint, я могу помочь

**Comment by PNKBizz** [comment]
@cvaize Подтяни мастер. Я как раз линтер прикрутил. И обнови PR

**Comment by cvaize** [comment]
Окей

**Comment by cvaize** [comment]
@PNKBizz Хочешь взглянуть на проект на котором используется этот код, на его производительность? Там больше 300 точек

**Comment by PNKBizz** [comment]
Работал с проектом, в котором было овер 2000 точек. Было больно ) Как раз в это время добавил useObjectManager в плагин. Стало лучше ) С твоими улучшениями будет еще лучше )

**Comment by cvaize** [comment]
Работаю над исключениями линтера, подожди немного

**Comment by PNKBizz** [comment]
Ок. Я сегодня все равно вливать не буду. Завтра утром со свежей головой сяду и все посмотрю. Спасибо!

**Comment by cvaize** [comment]
Внес изменения https://github.com/PNKBizz/vue-yandex-map/pull/174 , обязательно посмотри TODO, в том участке нужно твое внимание, так как я не рассматривал другие ситуации связанные с удалением. И обязательно проверь на работоспособность, я мог не учесть чего либо. Спасибо!

**Comment by cvaize** [comment]
Я вот этого не учел. Предлагаю оставить твой вариант, удаления всех точек в качестве опции. Типа hardUpdate, это может пригодиться

**Comment by cvaize** [comment]
Кстати, чем обусловлен выбор правил для eslint? Мне нравятся standard правила. Ровные отступы, отсутствие ";". Как по мне их легче читать. Я могу помочь с настройкой IDE phpstorm, для авто форматирования
![image](https://user-images.githubusercontent.com/26907947/66803532-4ddcc880-ef39-11e9-84bb-6cbbf855518d.png)

![image](https://user-images.githubusercontent.com/26907947/66803155-3e10b480-ef38-11e9-8bcd-f6d80cccc1ae.png)

**Comment by PNKBizz** [comment]
Привет!
Изучил твой PR. В процессе нашел более элегантный способ отслеживать удаление маркеров - через хук `beforeDestroy`. Сейчас занимаюсь этим вопросом, опираясь на твой код. Думаю потребуется пара-тройка дней, чтоб выкатить рабочее решение.
Спасибо огромное!

**Comment by cvaize** [comment]
О `beforeDestroy ` маркеров, об этом я и не подумал, действительно отличная идея, учитывай наличие нескольких карт на странице, + там есть точки которые через параметр `placemarks ` карты  передаются. Может привести к единому формату? Только через теги передавать и убрать у карты `placemarks ` параметр?

**Comment by karambafe** [comment]
@PNKBizz есть примерные сроки нового релиза? Тоже очень жду этой фичи :)

**Comment by PNKBizz** [comment]
@karambafe Да, уже все готово. Пишу e2e тесты, чтоб проверить все возможные случаи (кластеры, ObjectManager и проч.). Думаю до конца месяца бцдет новый релиз.

**Comment by PNKBizz** [comment]
Проверьте в версии 0.9.0
