### ISSUE TITLE
При рэндере карты с маркерами выдает постоянно ошибку "ymaps is not defined"

### ISSUE THREAD

**Issue by KubaiDoLove** [PNKBizz/vue-yandex-map#175]
1. Создать vue-yandex-map с маркерами
2. Открыть консоль/Sentry
3. Падает ошибка "ReferenceError": "ymaps is not defined"

**Comment by PNKBizz** [comment]
Сделайте пример в песочнице, пожалуйста.

**Comment by KubaiDoLove** [comment]
@PNKBizz Обновил зависимости, ошибка пропала, но появилась новая "Cannot read property 'createClass' of undefined", но вроде такой issue уже был оформлен

**Comment by PNKBizz** [comment]
Проверьте в версии 0.9.0
