### ISSUE TITLE
Доступ к `loadYmap` через экземпляр `vue`

### ISSUE THREAD

**Issue by mrswylet** [PNKBizz/vue-yandex-map#176]
Нужна возможность, что бы можно было обращаться к `loadYmap` через экземпляр `vue`, например: `Vue.loadYmap()` и(или) `this.$loadYmap()`.
На сколько я понимаю, этого будет достаточно: 
```js
const install = function (Vue, options = {}) {
    Vue.prototype.$loadYmap = Vue.loadYmap = loadYmap;
    YMapPlugin.pluginOptions = options;
    Vue.component('yandex-map', YMapPlugin);
    Vue.component('ymap-marker', Marker);
};
```

**Comment by PNKBizz** [comment]
А зачем это нужно?

**Comment by mrswylet** [comment]
@PNKBizz что бы получить доступ к loadYmap, если vue и плагин vue-yandex-map используется без сборки, а подключается, например, с CDN
