### ISSUE TITLE
При импорте функции loadYmap возникает ошибка. NuxtJs

### ISSUE THREAD

**Issue by orfeeen** [PNKBizz/vue-yandex-map#178]
Пытаюсь в default/layout.vue на nuxtjs (версия: 2.9.0) импортировать loadYmap. 
` import { loadYmap } from 'vue-yandex-maps'`
Выдает следующее: 
`Unexpected token export`

В чем может быть проблема?

**Comment by orfeeen** [comment]
Версия vue-yandex-maps последняя (0.8.18)

**Comment by orfeeen** [comment]
Решил проблему, путем выноса инициализации плагина из modules секции nuxt.config.js в отдельный файл plugins/vue-yandex-maps.js. 

`import Vue from 'vue'
import YmapPlugin from 'vue-yandex-maps'
import { loadYmap } from 'vue-yandex-maps'

const settings = {
  apiKey: '',
  lang: 'ru_RU',
  coordorder: 'latlong',
  version: '2.1'
}

Vue.use(YmapPlugin, settings)

export default ({app}) => {
  app.loadYmap = loadYmap(settings)
}`

// default.vue
`mounted () {
      this.$loadYmap()
 },`

Но, я считаю, что это костыль.

**Comment by PNKBizz** [comment]
Привет! Посмотрю, с Нукстом не проверял работоспособность.
