### ISSUE TITLE
Можно ли отловить событие по клику на кнопку внутри балуна?

### ISSUE THREAD

**Issue by voroncv** [PNKBizz/vue-yandex-map#18]
У меня внутри балуна есть кнопка, можно ли по ней отловить клик? Если будет не сложно покажите на примере. Или хотя бы клик по самому балуну. Заранее спасибо.

**Comment by f1uder** [comment]
> 
> 
> У меня внутри балуна есть кнопка, можно ли по ней отловить клик? Если будет не сложно покажите на примере. Или хотя бы клик по самому балуну. Заранее спасибо.

Смотри - в балун передается строка, которую Vue не парсит, поэтому о существовании методов он ничего не знает. То есть через переменную к методу обратиться не получится. Костыльнуть можно вот таким способом:

<button onclick="javascript: document.querySelector('.button').click();">changePm</button>

это кнопка в темплейте, а

<button @click="changeIcon" class="button">changePm</button>

кнопка в твоем шаблоне компонента, которую видит Vue (можно сделать display: none)
Но еще раз повторюсь - это костыль
Еще почитаю доку Я.Карт, возможно у них предусмотрены кнопки в балунах и методы для них.
