### ISSUE TITLE
ymapMarker created after map init not showing

### ISSUE THREAD

**Issue by antoinematyja** [PNKBizz/vue-yandex-map#184]
Hi,

I'm trying to use the `<ymap-marker>` component to generate markers for an array of places which are loaded asynchronously. However it seems like creating `<ymap-marker>` after the map initialization doesn't trigger anything.

I created a codepen:
https://codepen.io/Owumaro/pen/LYYqrRK
I used a `setTimeout` to fake an async loading. After the timeout, there are 3 ymap-markers but they are not showing.

The problem is that the drawing of the markers is handled by the `Map` component, however the map is not watching its default slot to get new `ymap-marker`.

The map component reads its `ymap-marker`s  at creation (using `this.$slots.default`), but if a `ymap-marker` is created after, it will not be known by the map.

Maybe the `ymap-marker` should register itself at creation to the parent `Map`. I'm not sure of how the map keeps track of its children `ymap-marker` currently.

Another solution would be to delegate the creation of markers to the `ymap-marker` component itself. I also use [vue-googlemaps](https://github.com/Akryum/vue-googlemaps) which works that way:
https://github.com/Akryum/vue-googlemaps/blob/master/src/components/Marker.js#L96
As you can see the marker component gets the map reference and creates the map marker by calling the google maps method. This also allows each marker to be independent and would simplify a lot of code here. But that would be a big change.

What do you think ?

Thanks,

**Comment by malyshevarman** [comment]
надо добавить Events для карты, 
myMap.container.fitToViewport();

**Comment by antoinematyja** [comment]
Thanks for the answer,

Do you mean calling this manually every time ymap-markers are added ?

This is against the principle of using vue components : update data and delegate the rest to the components.

**Comment by malyshevarman** [comment]
согласен), тогда ждем ответа разработчика

**Comment by PNKBizz** [comment]
@antoinematyja Yeah. It is a bug. I deleted an observer, but forgot to implement marker creation in created hook. I'll fix it tomorrow and will think about your another issue #183

**Comment by antoinematyja** [comment]
Thanks !

Also note that the last solution proposed in this issue would also solve #183 .

**Comment by PNKBizz** [comment]
@antoinematyja replacing logic into markers - is a good idea and it is in my roadmap. But i haven't a time to implement it for now (

**Comment by antoinematyja** [comment]
Ok, good to hear !

I'll work on a PR if I find the time too...

**Comment by malyshevarman** [comment]
получается еще не устранили проблему?, есть еще такая проблема, при смене zoom, ели я выбираю область, или регион, я передвигаю карту по координатам, и у каждого региона свой зум, почему то он иногда косячит, а именно зум сработает а координаты оставит на месте
