### ISSUE TITLE
Ymap-marker добавить slot 

### ISSUE THREAD

**Issue by Georgeek** [PNKBizz/vue-yandex-map#187]
Здравствуйте!
Планируется ли добавление slot'ов в ymap-marker?
Хочу добавить компонент в ballon с элементами js'а.
Нашел в issue костыльные решения, но они некрасивые :)

**Comment by PNKBizz** [comment]
Добрый день!
Да, я подумаю над этим. Спасибо за идею.

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/en/examples/#balloon-slot-in-marker

**Comment by PaVel-58** [comment]
Здравствуйте! Мне нужно реализовать две вещи: 1) открытие балуна при наведении на метку. 2) метка в роли ссылки. Реально ли это вообще сделать?  Балун вставлен при помощи slot="balloon". Заранее спасибо
