### ISSUE TITLE
Multiple <ymap-marker> children not working

### ISSUE THREAD

**Issue by antoinematyja** [PNKBizz/vue-yandex-map#189]
Hi again,

Thanks for your work on the 0.10 release.
However I'm still having a few issues 😢  In fact when I tried to create a codepen to show my issue, I ran into another issue : I can't have multiple `<ymap-marker>`s inside a `<ymap>`, only the first one works. Here is the codepen :

https://codepen.io/antoinematyja/pen/BayaWqZ

As you can see, only the first `ymap-marker` is displayed.
If you comment the first `ymap-marker` (with `marker-id="user"`), the next one is displayed.

Thanks for the help,

**Comment by PNKBizz** [comment]
Hi! 
Looks like it is a Vue issue
https://codepen.io/PNKBizz/pen/zYxYQbr

**Comment by antoinematyja** [comment]
Oh I always thought that self closing tags were just a shortcut and weren't changing anything... Good to know !
Thanks and sorry for the wrong issue 😅

**Comment by PNKBizz** [comment]
I spent all this morning for this )))
https://github.com/vuejs/vue/issues/10887#issuecomment-561087845
All is ok )
