### ISSUE TITLE
Пример использования callback

### ISSUE THREAD

**Issue by voroncv** [PNKBizz/vue-yandex-map#19]
Привет. В новой версии Вы добавили callback для маркеров. Можете показать на небольшом примере как это работает? Скажем событие balloonopen

**Comment by PNKBizz** [comment]
Привет! Например таким образом: атрибут у маркера будет :callbacks="{ balloonopen: openHandler }", а в методах родительского компонента определяете openHandler, methods: { openHandler() { console.log('balloon opened') } }

**Comment by voroncv** [comment]
Привет. Спасибо большое за ответ! Но есть другая проблема, как мне передать модель одного балуна в функцию openHandler? Если делаю :callbacks="{ balloonopen: openHandler(model) }" то ничего не работает при клике на конкретный

**Comment by PNKBizz** [comment]
Смотрите, при указании коллбэка, вы пишете { balloonopen: openHandler(model) }, а нужно { balloonopen: openHandlel }, а уже в методах вы можете указать openHandler(event) { const model = event.target; console.log (model) }
В коллбэк передается кастомный эвент от Я.Карт

**Comment by voroncv** [comment]
Пробовал по вашему коду, const model в консоли мне возвращается как undefined

**Comment by PNKBizz** [comment]
Да, черт, поскольку это кастомный эвент нужно cons model = event.originalEvent.target
