### ISSUE TITLE
Marker not updating anymore after other marker update

### ISSUE THREAD

**Issue by antoinematyja** [PNKBizz/vue-yandex-map#190]
Hello again 😅 

Back to my original issue :

https://codepen.io/antoinematyja/pen/eYmYwQW

It's kind of difficult to reproduce.
I have 1 marker for the user geolocation, and a list of markers with points of interest.
If I update the list of markers, then the user marker cannot be updated anymore.

To reproduce it with my codepen:
- first, try to change the lat of the user marker with the last buttons, it works fine
- then, click on the "switch set" button (it will change the list of markers)
- then, try again to change the lat of the user marker, the value will change but the marker on the map will not

I guess something wrong happens when the list is destroyed, we are losing the user marker at the same time.

Thanks again,

**Comment by PNKBizz** [comment]
Ok! I'll check it
