### ISSUE TITLE
Search callback

### ISSUE THREAD

**Issue by Yuriy13** [PNKBizz/vue-yandex-map#192]
Добрый день.
Такой вопрос, у меня карта покрыта полигонами, у которых есть доп атрибуты, условно: "название зоны", "давление в зоне", по клику на ту или иную зону, я могу достучаться до её параметров и получить эти данные, но вот я не нашел, или не могу разобраться по поводу строки поиска, есть ли вообще у неё какой - либо callback, и как я в принципе могу, по найденному городу из строки поиска определить в какую он зону попадает? Спасибо.

У самого яндекса, есть функция проверки на попадание точки в полигон, https://tech.yandex.ru/maps/jsbox/2.1/delivery_zones но как прикрутить её сюда, никак не пойму

**Comment by PNKBizz** [comment]
Ну так в примере, что вы приводите есть и колбэк зоны поиска и все остальное. Это же просто работа с АПИ. Плагин тут уже ни при чем )
