### ISSUE TITLE
Ghost markers

### ISSUE THREAD

**Issue by antoinematyja** [PNKBizz/vue-yandex-map#193]
Hi,

This should be my last issue 😇
This one is hard to reproduce too : when markers are updated quickly, sometimes an old marker is not deleted.

Here is an example:
https://codepen.io/Owumaro/pen/BayygaP
Under the map is a list of items corresponding to the markers, when hovered the marker text changes. If you swing your mouse on them, markers are rapidly updated, and sometimes some markers are not refreshed correctly:

![image](https://user-images.githubusercontent.com/9961462/70218125-b2025880-1742-11ea-8fe6-04154d9c66b0.png)

If you update markers again after that, the unwanted ghosts are correctly deleted, so the code has not lost track of them. They are just not deleted at the right time.

Thanks,

**Comment by PNKBizz** [comment]
Seems like problem inside Yandex Map, but i'll research this issue

**Comment by BogdanovArt** [comment]
https://codepen.io/bogdanovart/pen/poJaGaP
this problem still exists. It's probably tied with marker add changes since the bug is missing in 0.8 versions
