### ISSUE TITLE
метод fitToViewport

### ISSUE THREAD

**Issue by Evdiso** [PNKBizz/vue-yandex-map#194]
Добрый день, при изменении контейнера, карта не растягивается, нашел, что нужно вызывать метод fitToViewport. Собственно, каким способом я могу вызвать этот метод в данном компоненте?

**Comment by muvbed** [comment]
:options="{ autoFitToViewport: 'always' }" можно так, если для vue-yandex-maps

**Comment by muvbed** [comment]
Если кого интересует, то можно таким способом:
:options="{ autoFitToViewport: 'always' }"
