### ISSUE TITLE
Определение местоположения пользователя

### ISSUE THREAD

**Issue by Exte4nd** [PNKBizz/vue-yandex-map#197]
Дефолтный метод в инстансе карты geolocation.get() почему то undefined 
как получить местоположение пользователя?

**Comment by PNKBizz** [comment]
@Exte4nd создайте пример в песочнице, пожалуйста

**Comment by GordonBreazz** [comment]
> Дефолтный метод в инстансе карты geolocation.get() почему то undefined
> как получить местоположение пользователя?
НУжно обращатся не к инстансу карты а к статическому объекту обявленному в библиотеке
вот так будет работать, но нужен API Key

`    initHandler(obj) {
      this.map = obj
      this.userPosition = ymaps.geolocation.get()
      console.log('userPosition',ymaps.geolocation)
      this.userPosition.then(
        function(result) {
         // Добавление местоположения на карту.
           this.map.geoObjects.add(result.geoObjects)
        },
        function(err) {
          console.log('Ошибка: ' + err)
        }
      );     
      
    }`
