### ISSUE TITLE
this.$ymapEventBus.initMap is not a function

### ISSUE THREAD

**Issue by alxdoronin** [PNKBizz/vue-yandex-map#21]
Добрый день. Карта и объекты отрисовываются, но Vue выкидывает ошибку.

`[Vue warn]: Error in callback for watcher "coords": "TypeError: this.$ymapEventBus.initMap is not a function"`

**Comment by PNKBizz** [comment]
Спасибо, сейчас посмотрю!

**Comment by PNKBizz** [comment]
Fixed in v0.5.2
