### ISSUE TITLE
Нулевые значения в "markerFill" и "markerStroke"

### ISSUE THREAD

**Issue by alxdoronin** [PNKBizz/vue-yandex-map#22]
Если передать **0** в качестве значения для **width** или **opacity** в объектах **markerFill** и **markerStroke**, то это приведет к тому что будет присвоено значение по умолчанию, так как **0** будет воспринят как **false**:

`fillOpacity: myMarkers[i].markerFill && myMarkers[i].markerFill.opacity ||  '1',`

Стоит сделать проверку на число, хотя бы так:

`fillOpacity: myMarkers[i].markerFill && parseInt(myMarkers[i].markerFill.opacity) >= 0 ? myMarkers[i].markerFill.opacity : '1',`

Еще вопрос. Мне необходимо добавить изображение на фон полигона. Есть ли способ сделать это в данный момент или придется добавить строчку и расширить объект **markerFill**?

`fillImageHref: myMarkers[i].markerFill && myMarkers[i].markerFill.imageHref || ''`

**Comment by PNKBizz** [comment]
Отлично, спасибо! Да, нужно расширять. Хочешь - сделай PR, я вмержу и выкачу релиз + правки по первой баге с warning'ами

**Comment by PNKBizz** [comment]
Или сам добавлю строчки )

**Comment by alxdoronin** [comment]
Лучше сам) Может у тебя будет более изящная проверка на число.

**Comment by PNKBizz** [comment]
)))) Нед. Ок, спасибо, сейчас все будет

**Comment by PNKBizz** [comment]
Fixed in v0.5.2

**Comment by alxdoronin** [comment]
Принципиально ничего не изменилось))

`parseFloat(myMarkers[i].markerStroke.width) || 1`

Если **width** равен нулю, то левый операнд будет равен **false,** а результат единице.

**Comment by PNKBizz** [comment]
Shame on me... В спешке вчера залил...

**Comment by PNKBizz** [comment]
Fixed in v0.5.3
