### ISSUE TITLE
Как получить массив всех маркеров на карте?

### ISSUE THREAD

**Issue by Romulus92** [PNKBizz/vue-yandex-map#220]
Успешно создаю несколько placemarks на карте с помощью v-for

```
<yandex-map 
	class='map' 
	:zoom='9' 
	:controls='[]' 
	:coords="[55.76, 37.64]"
	>
	<ymap-marker
		class='ymap-marker'
		v-for='(place, index) in places'
		marker-type='Placemark'
		@click='balloonOpen($event, index)'
		:marker-id='index' 
		:balloon-template="balloonTemplate(place.name, place.adress, place.phone)" 
		:icon="markerIcon"
		:coords='place.coords' 
		:key='index'
	>
        </ymap-marker>
</yandex-map>
```

В документации написано:

> По умолчанию маркеры добавляются на карту через GeoObjectCollection

Не понимаю как мне получить доступ к этой коллекции, думаю стоит такой случай занести в примеры документации. У меня к каждому маркеру предусмотрен элемент внешнего интерфейса, я хочу чтоб при клике на элемент открывался балун соответствующего маркера.

Эта проблема только часть моей задачи, но всё же, надеюсь на помощь, если нужна доп.инфа, то предоставлю.

**Comment by PNKBizz** [comment]
https://tech.yandex.ru/maps/jsapi/doc/2.1/ref/reference/GeoObjectCollection-docpage/
