### ISSUE TITLE
Component Vue внутри balloonTemplate

### ISSUE THREAD

**Issue by ipirm** [PNKBizz/vue-yandex-map#221]
Здравствуйте,Мне нужно использовать свой компонент Vue ,как темплейт для баллона мой код ниже:
               ymap-marker
                        v-else
                        v-for="(item,index) in address"
                        :key="index"
                        :marker-id="index"
                        :coords="[item.lat, item.lng]"
                        :balloonTemplate="balloonTemplate"
                ></ymap-marker

Мой код внутри computed как в примере:
        balloonTemplate() {
                return `  <MapPopupSlider :data="mapPopupData"/>`
            }

В итоге я получаю просто такой тег: ymaps>  <mappopupslider :data="mapPopupData"</mappopupslider</ymaps

Вне карты компонент рендириться как нужно.
Как я могу это использовать? Писать html внутри самого Баллона я не могу, там есть слайдер , который так же не будет рендерится

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/guide/Marker.html#slots
https://vue-yandex-maps.github.io/examples/#%D0%B8%D1%81%D0%BF%D0%BEn%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81n%D0%BE%D1%82%D0%B0-%D0%B1%D0%B0n%D1%83%D0%BD%D0%B0-%D0%B2-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%80%D0%B5
