### ISSUE TITLE
В каком месте происходит инициализация объекта vue-yandex-map

### ISSUE THREAD

**Issue by GordonBreazz** [PNKBizz/vue-yandex-map#224]
Не понимаю в каком месте происходит инициализация  объекта vue-yandex-map. Подключал локально, глобально. И так и так не работает. Хотя в девтулс объект есть. Работает только подключение через CDN. 

Что я делаю не так 
`import 'material-design-icons-iconfont/dist/material-design-icons.css'
import Vue from 'vue'
import App from './App.vue'
import router from './router'
import vuetify from './plugins/vuetify'
import ymapPlugin from 'vue-yandex-maps'

const settings = {
  apiKey: '########################',
  lang: 'ru_RU',
  coordorder: 'latlong',
  version: '2.1'
}

Vue.config.productionTip = false
Vue.use(ymapPlugin, settings)

new Vue({
  router,
  vuetify,
  render: h => h(App)
}).$mount('#app')
`

**Comment by PNKBizz** [comment]
Если в тулзах объект есть и в консоли нет ошибок - возможно Я.Карты не подгружаются. Посмотрите вкладку network

**Comment by GordonBreazz** [comment]
Весьма не информативные  примеры. Если внедрять карту в приложение которое собирает CLI ничего не работает. При подключении через плагин что то идёт не так и объект создаётся с ключами undefined. Если подключать через компоненты объекты не инициалируется.

**Comment by PNKBizz** [comment]
Ок, создайте пример в репозитории и киньте ссылку. Я посмотрю

**Comment by GordonBreazz** [comment]
Пожалуйста https://github.com/GordonBreazz/vue-map-test

**Comment by GordonBreazz** [comment]
Нашёл проблему. В проекте стоял линтер с авто исправлениями. Как только отключил сразу решил проблему. Ещё стоит в документации указать ключевую роль атрибута  coords. Без него карта падает. Vue.use(ymapPlugin, settings) не срабатывает, нужно координаты передать явно в директиве Data объекта Vue.
