### ISSUE TITLE
В документации нет информации о работе с Object Mananger

### ISSUE THREAD

**Issue by Sonit90** [PNKBizz/vue-yandex-map#225]
#82 
При использовании опции use-object-manager, для каждого маркера перестают работать события @click.
Также не понятно, как получить сам объект Object Manager.
Плюс без использования ObjectManager при динамическом добавлении\удалении меток, иногда некоторые метки остаются на карте, хотя Vue devtools не видит объектов. Даже динамическая смена :key не спасает.

**Comment by sffr-dev** [comment]
> без использования ObjectManager при динамическом добавлении\удалении меток, иногда некоторые метки остаются на карте, хотя Vue devtools не видит объектов. Даже динамическая смена :key не спасает.

Можете сделать пример в песочнице?

**Comment by PNKBizz** [comment]
> При использовании опции use-object-manager, для каждого маркера перестают работать события @click.

Это особенность работы Object Manager

> Также не понятно, как получить сам объект Object Manager.

getGeoObjects у карты

> Плюс без использования ObjectManager при динамическом добавлении\удалении меток, иногда некоторые метки остаются на карте, хотя Vue devtools не видит объектов. Даже динамическая смена :key не спасает.

Можете сделать пример в песочнице?
