### ISSUE TITLE
Как поместит router-link  внутри balloon-template?

### ISSUE THREAD

**Issue by dilovar-91** [PNKBizz/vue-yandex-map#230]
Как поместит router-link  внутри balloon-template?

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/examples/#%D0%B8%D1%81%D0%BF%D0%BEn%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81n%D0%BE%D1%82%D0%B0-%D0%B1%D0%B0n%D1%83%D0%BD%D0%B0-%D0%B2-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%80%D0%B5

Только вместо кнопки - ссылка, а вместо `alert` - `$router.push`
