### ISSUE TITLE
Ghost markers

### ISSUE THREAD

**Issue by BogdanovArt** [PNKBizz/vue-yandex-map#231]
https://codepen.io/bogdanovart/pen/poJaGaP
this problem still exists. It's probably tied with marker add changes since the bug is missing in 0.8 versions

_Originally posted by @BogdanovArt in https://github.com/PNKBizz/vue-yandex-map/issues/193#issuecomment-598080961_

**Comment by PNKBizz** [comment]
Ok, thanks. I'll research this problem

**Comment by PNKBizz** [comment]
Please check with latest version
