### ISSUE TITLE
Как отслеживать события из поля поиска?

### ISSUE THREAD

**Issue by Alex-Sokolov** [PNKBizz/vue-yandex-map#235]
Требуется добавлять маркер на карту при выборе результата поиска. Это возможно сейчас реализовать? В списке отслеживаемых событий нет связанных с полем поиска адреса.

**Comment by kosuha606** [comment]
Как вариант получить объект карты. вот так
```js
<yandex-map  @map-was-initialized="loadInitialMarkers">
```
в коде компонента
```js
methods: {
loadInitialMarkers(myMap) {
// Тут можно работать с апи myMap
}
}
```

Получив myMap уже можно повесить обработчики событий думаю на выбор варианта из поиска, и дальше уже куда-нибудь в массив маркеров добавить координаты нового маркера. Наверное так, нужно читать апи по поиску в картах

**Comment by Alex-Sokolov** [comment]
Спасибо! Получилось :)
