### ISSUE TITLE
Открытие балуна по клику на кнопку?

### ISSUE THREAD

**Issue by SeMax1337** [PNKBizz/vue-yandex-map#241]
![загруженное](https://user-images.githubusercontent.com/48476180/80470330-6f9d1a80-8974-11ea-9040-adf3be699687.png)
Здравствуйте, как по клику на кнопки слева - открывать соответствующие балуны справа на карте?

**Comment by PNKBizz** [comment]
Нужно в геообъектах карты находить маркер с нужным `id` и вызывать у него метод открытия балуна. Думаю как-то так
