### ISSUE TITLE
Подключение карты

### ISSUE THREAD

**Issue by marysal** [PNKBizz/vue-yandex-map#243]
Подключал все по инструкции, но карты не до конца инитяться https://prnt.sc/sd03g3

Может случайно знаете, что это может быть?

**Comment by astrotrain55** [comment]
Почему закрыто без комментария? У меня такая же проблема, интересно, что я делаю не так.

**Comment by PNKBizz** [comment]
Проверяйте родительский элемент. Скорее всего высоту нужно установить
