### ISSUE TITLE
Отображение описание BalloonBody при кластеризации

### ISSUE THREAD

**Issue by g1nc** [PNKBizz/vue-yandex-map#244]
При кластеризации точек, BalloonHeader отрисовывается в html-safe режиме
<img width="312" alt="Снимок экрана 2020-05-12 в 2 37 29 PM" src="https://user-images.githubusercontent.com/8670057/81683127-5a3ceb80-945e-11ea-9643-2dba1aee4076.png">
<img width="559" alt="Снимок экрана 2020-05-12 в 2 37 16 PM" src="https://user-images.githubusercontent.com/8670057/81683130-5c9f4580-945e-11ea-9d98-38722a22b2c7.png">

**Comment by PNKBizz** [comment]
Посмотрю что можно сделать

**Comment by g1nc** [comment]
Посмотрите пожалуйста, не решит ли это проблему?
[Тык](https://github.com/PNKBizz/vue-yandex-map/pull/233)

**Comment by PNKBizz** [comment]
Да, я видел ваш реквест. В ближайшее время постараюсь найти время, чтоб проверить его на совместимость. Не хотелось бы сломать отображение у других юзеров

**Comment by anton4ik8374** [comment]
@PNKBizz 
Доброго времени суток.
Возникла  аналогичная проблема как и у @g1nc .
![gg](https://user-images.githubusercontent.com/41378355/88202085-06663400-cc51-11ea-81c7-ca3298592755.PNG)

**Comment by PNKBizz** [comment]
@anton4ik8374 до конца недели постараюсь посмотреть как решить проблему. Думаю, как сделать это аккуратно и безопасно.

**Comment by gkhabada** [comment]
Ну так решили проблему, @PNKBizz ?

**Comment by PNKBizz** [comment]
@gkhabada Предложенный PR слишком открыт для всяческих инъекций. Поэтому пока в подвешенном режиме

**Comment by PNKBizz** [comment]
Добавил в версии 0.11 через пропс `use-html-in-layout`
