### ISSUE TITLE
Не меняется цвет иконки

### ISSUE THREAD

**Issue by NikitaLem** [PNKBizz/vue-yandex-map#247]
Привет! Нашёл проблему из-за которой нельзя менять цвет дефотной иконки.
![image](https://user-images.githubusercontent.com/35275071/83224861-a3a07100-a1a8-11ea-9ba0-a814adc23e2c.png)

У marker отсутствует и glyph и color.

![image](https://user-images.githubusercontent.com/35275071/83224963-e3675880-a1a8-11ea-8052-ad66d9d11e7d.png)

Из-за этого утилитка не работает.
Можно поправить, пожалуйста?

**Comment by NikitaLem** [comment]
Удалось поменять цвет. Но не хватает примеров в документации.

**Comment by PNKBizz** [comment]
Сделайте пулл-реквест )

**Comment by kriptograf** [comment]
> Удалось поменять цвет. Но не хватает примеров в документации.

Не подскажете, как удалось поменять цвет?
