### ISSUE TITLE
Не отображается карта

### ISSUE THREAD

**Issue by ivansteff** [PNKBizz/vue-yandex-map#249]
Пишу проект на nuxt.js. Подключаю модуль в соответствии с [инструкцией](https://vue-yandex-maps.github.io/guide/#%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0).

В разметке карта есть, на странице не отображается.
![image](https://user-images.githubusercontent.com/31563237/84251770-7774e080-ab16-11ea-8594-e163a567105e.png)

Здесь находил схожие вопросы, ответы мне не помогли.

**Comment by PNKBizz** [comment]
Добрый день! Воспроизведите пример в песочнице, пожалуйста. Или создайте репозиторий с примером

**Comment by ivansteff** [comment]
@PNKBizz создал закрытый репозиторий, что бы не светить ключ для апи. Отправил Вам приглашение

**Comment by PNKBizz** [comment]
Ок, посмотрю и отпишусь вам

**Comment by ivansteff** [comment]
@PNKBizz  спасибо, буду ждать.
### P.S.
Находил схожие вопросы здесь.
Использовал правильные ответы, но это мне не помогло.
[Ответ 1
](https://github.com/PNKBizz/vue-yandex-map/issues/59#issuecomment-617359777)[Ответ 2
](https://github.com/PNKBizz/vue-yandex-map/issues/53#issuecomment-377427410)[Ответ 3
](https://github.com/PNKBizz/vue-yandex-map/issues/53#issuecomment-449712663)

**Comment by ivansteff** [comment]
Нашёл способ: применить лайфхак с добавлением переменной типа `Boolean` в  `mounted`. Как оказалось карта загружалась раньше чем загружался сервер. Пробовал указать условие в самом теге `<yandex-map>` не прокатило, перенёс в тег выше, все заработало!
@PNKBizz спасибо за Ваше потраченное время.


```
<div v-if="showMap">
<yandex-map
    :coords="[54.62896654088406, 39.731893822753904]"
></yandex-map>
<div>

-----------
	data () {
		return {
			showMap: false
		}
	},
-----------

mounted() { this.showMap = true }
```
