### ISSUE TITLE
Как задать масштаб карты?

### ISSUE THREAD

**Issue by dronowar** [PNKBizz/vue-yandex-map#25]
Как получить объект карты чтобы установить область видимости по расположению всех точек на карте?
Обычно после загрузки карты делаю.
myMap.setBounds(myMap.geoObjects.getBounds())

**Comment by PNKBizz** [comment]
В релизе 0.5.4 добавлен event для компонента карты `map-was-initialized`, payload которого - ссылка на map instance, с которым вы можете работать на свое усмотрение =)
Эмиттится после инициализации карты.
