### ISSUE TITLE
Обновление данных во vue представлении при использовании loadYmap

### ISSUE THREAD

**Issue by cryptoprof** [PNKBizz/vue-yandex-map#250]
Добрый день! Спасибо за отличный модуль, прежде всего
Вопрос у меня в следующем - как можно обновить переменную во vue, когда срабатывает event клика на карту? Вот мой код
```
async mounted() {
            const settings = {lang: 'ru_RU'};
            await loadYmap(settings);
            var geolocation = ymaps.geolocation,myPlacemark,
                myMap = new ymaps.Map('map', {
                    center: this.cords,
                    zoom: 10,
                    controls: ['geolocationControl']
                }, {
                    searchControlProvider: 'yandex#search'
                });

            geolocation.get({
                provider: 'browser',
                mapStateAutoApply: true
            }).then(function (result) {
                // Если браузер не поддерживает эту функциональность, метка не будет добавлена на карту.
                createPlacemark(result.geoObjects);
            });
            // Слушаем клик на карте.
            myMap.events.add('click', function (e) {
                var coords = e.get('coords');
                // Если метка уже создана – просто передвигаем ее.
                if (myPlacemark) {
                    myPlacemark.geometry.setCoordinates(coords);
                }
                // Если нет – создаем.
                else {
                    myPlacemark = createPlacemark(coords);
                    myMap.geoObjects.add(myPlacemark);
                }
            });

            // Создание метки.
            function createPlacemark(coords) {
                return new ymaps.Placemark(coords, {
                    iconCaption: 'Место заявки'
                }, {
                    preset: 'islands#violetDotIconWithCaption',
                    draggable: true
                });
            }
        },
        methods: {
            hello(coords) {
                this.cords = coords.get('coords');
            }
        }

```
Метка добавляется на карту, но если я хочу обновить координаты, которые у меня хранятся во Vue в переменной this.cords, то это срабатывает только при условии передачи метода this.hello() 
```
myMap.events.add('click',this.hello);
```
координаты обновляются, но метка при этом не добавляется на карту. Я подключаю loadYmap т.к. в дальнейшем мне потребуется геолокация. Я видел у Вас отличный готовый пример с получением координаты клика на карте, я его просто хотел дополнить геолокацией. Извиняюсь если ошибся в формулировках- Vue не так давно начал изучать. Спасибо заранее!

**Comment by PNKBizz** [comment]
Не очень понял проблему. Создайте пример в песочнице, посмотрю и отпишусь вам

**Comment by cryptoprof** [comment]
Спасибо, https://codesandbox.io/s/zen-yonath-s4lgy?file=/src/App.vue
Суть в чем, если коротко
```
myMap.events.add('click', function (e) {
    ...
    this.hello(coords);
}
```
Так я не могу вызвать свой метод во Vue, потому как не передается контекст как я понял, но в event'е происходит добавление/перемещение маркера по карте+я хотел со временем добавить геолокацию, в зависимости от которой метка изменит координаты.
Передав же свой метод таким образом:
`myMap.events.add('click',this.hello);`
Функция отработает, но не появится метка на карте. Я конечно дико извиняюсь, если что-то неправильно объясняю, может конечно вопрос вовсе не по адресу. Просто хотелось понять как вызвать свои методы при возникновении события на карте. В документации я такого не нашел, поэтому увидел пример в API яндекс карт

**Comment by cryptoprof** [comment]
Я извиняюсь, разобрался. Контекст передается 3им параметром. Таким образом чтобы сработал метод при наступлении события click по карте, нужно передать this
```
// Слушаем клик на карте.
            myMap.events.add('click',function (e) {
                var coords = e.get('coords');
                // Если метка уже создана – просто передвигаем ее.
                if (myPlacemark) {
                    myPlacemark.geometry.setCoordinates(coords);
                }
                // Если нет – создаем.
                else {
                    myPlacemark = createPlacemark(coords);
                    myMap.geoObjects.add(myPlacemark);
                } 
              //мой метод
              this.hello(coords)
            },this);
```
Может пригодится новичкам)
