### ISSUE TITLE
Как правильно получить переменную ymaps и провести маршрут между несколькими точками?

### ISSUE THREAD

**Issue by Lihander** [PNKBizz/vue-yandex-map#251]
Добрый день! Столкнулся с такой проблемой, что не получается получить переменную **ymaps** .

```
<template>
  <div class="base-map">
    <yandex-map
      ref="map"
      :settings="settings"
      class="ymap"
      :coords="coords[0] || [0, 0]"
    >
      <ymapMarker
        v-for="(point, index) in coords"
        :key="index"
        :marker-id="index"
        :coords="point"
      />
    </yandex-map>
  </div>
</template>

<script>
const settings = {
  apiKey: process.env.YANDEX_KEY,
  lang: 'ru_RU',
  coordorder: 'latlong',
  version: '2.1'
}

import { yandexMap, ymapMarker, loadYmap } from 'vue-yandex-maps'
export default {
  name: 'BaseMap',
  components: { yandexMap, ymapMarker },
  props: {
    coords: {
      type: Array,
      required: true
    }
  },
  data() {
    return {
      settings: settings
    }
  },
  async mounted() {
    await loadYmap(settings)
    console.log(window.ymaps)
  }
}
</script>
```

Вроде сделал все как указано в документации, но переменная ymaps остается undefined. В чем может быть проблема?

Также не нашел, как построить маршрут между несколькими точками на карте. Как я понял это надо делать, как раз через переменную ymaps? Есть ли какие-нибудь примеры кода, как это правильно сделать?

**Comment by EliotRaven** [comment]
та же проблема, "ReferenceError: ymaps is not defined" постоянно, причем у меня даже не ssr обычная spa.

**Comment by sffr-dev** [comment]
@EliotRaven @Lihander сделайте пример в песочнице

**Comment by PNKBizz** [comment]
@Lihander @EliotRaven сделайте пожалуйста пример в песочнице

**Comment by EliotRaven** [comment]
> @Lihander @EliotRaven сделайте пожалуйста пример в песочнице

к сожалению не могу перенести весь проект на песочницу

**Comment by EliotRaven** [comment]
в идеале бы получить инстанс карты, но на хук onLoad мы получаем его только порезаный(((
меня сейчас интересует функционал расчета дистанции от меня до маркера. как это можно реализовать?

**Comment by Lihander** [comment]
@PNKBizz Так подойдет? https://codesandbox.io/s/frosty-sound-yry0w?file=/src/components/BaseMap.vue

**Comment by EliotRaven** [comment]
[image: image.png]

вт, 16 июн. 2020 г. в 17:37, Lihander <notifications@github.com>:

**Comment by PNKBizz** [comment]
@Lihander  проблема скорее всего в ключе апи. Попробуйте просто убрать его и проверить работу. 
@EliotRaven `ReferenceError: ymaps is not defined` - ошибка линтера, нужно прописать `ymaps` в глобальные переменные

**Comment by EliotRaven** [comment]
> @Lihander проблема скорее всего в ключе апи. Попробуйте просто убрать его и проверить работу.
> @EliotRaven `ReferenceError: ymaps is not defined` - ошибка линтера, нужно прописать `ymaps` в глобальные переменные

вариант добавления ее в глобал не помог

к примеру мне нужно в кнопку без карты отрисовать растояние от меня до конкретной локации, как это сделать?

**Comment by Elena-Kho** [comment]
Проблема та же - не могу получить доступ к работе с инстансом карты, делаю по документации https://vue-yandex-maps.github.io/guide/Map.html#events, слушая событие map-was-initialized. В итоге ymaps в консоли есть, обратиться к API не получается. Можете пояснить, в чем проблема и привести примеры работы с API через инстанс карты?
**App.vue**
`<template>
  <div id='app'>
    <yandex-map
      :settings="settings"
      :coords="coords"
      zoom="7"
      style="width: 100%; height: 400px"
      @map-was-initialized='mapInitialized'
    >
    </yandex-map>
  </div>
</template>

<script>


export default {
  data() {
    return {
      coords: [57.626559, 39.893804],
      settings: {
        apiKey: '',
        lang: 'ru_RU',
        myMap: null,
        myRouter: null
      },
    }
  },

  mounted() {
    //loadYmap(this.settings).then(response => {
    //console.dir(ymaps);
    //})
  },
  methods: {
    mapInitialized: function () {
      console.dir(ymaps);
      console.dir(ymaps.multiRouter);

      this.myMap = ymaps;
      console.dir(myMap);

      this.myRouter = ymaps.multiRouter;
      console.dir(myRouter);
    }
  }
}
</script>`

**main.js**
`import Vue from 'vue'
import App from './App.vue'
import YmapPlugin from 'vue-yandex-maps'
import { loadYmap } from 'vue-yandex-maps';
Vue.use(YmapPlugin)

new Vue({
  el: '#app',
  render: h => h(App)
})`

**Comment by EliotRaven** [comment]
> Проблема та же - не могу получить доступ к работе с инстансом карты, делаю по документации https://vue-yandex-maps.github.io/guide/Map.html#events, слушая событие map-was-initialized. В итоге ymaps в консоли есть, обратиться к API не получается. Можете пояснить, в чем проблема и привести примеры работы с API через инстанс карты?
> **App.vue**
> `
> 
> <script> export default { data() { return { coords: [57.626559, 39.893804], settings: { apiKey: '', lang: 'ru_RU', myMap: null, myRouter: null }, } }, mounted() { //loadYmap(this.settings).then(response => { //console.dir(ymaps); //}) }, methods: { mapInitialized: function () { console.dir(ymaps); console.dir(ymaps.multiRouter); this.myMap = ymaps; console.dir(myMap); this.myRouter = ymaps.multiRouter; console.dir(myRouter); } } } </script>`
> **main.js**
> `import Vue from 'vue'
> import App from './App.vue'
> import YmapPlugin from 'vue-yandex-maps'
> import { loadYmap } from 'vue-yandex-maps';
> Vue.use(YmapPlugin)
> 
> new Vue({
> el: '#app',
> render: h => h(App)
> })`

![image](https://user-images.githubusercontent.com/25608846/88793430-6d31a300-d1a5-11ea-9a21-ba5d5867a2e9.png)

**Comment by EliotRaven** [comment]
все оказалось тривиально просто

**Comment by Elena-Kho** [comment]
> все оказалось тривиально просто

Пожалуйста, поподробнее) Я инстанс карты получаю не через loadYmap, а через событие map-was-initialized. Переменную ymaps в консоли я вижу, а к API через нее обратится не получается. Если делаю через loadYmap и функцию в mounted, как в вашем скрине,  та же история.

**Comment by PNKBizz** [comment]
@Elena-Kho может есть смысл поизучать API Я.Карт для начала? И если хотите какой-то помощи - сделайте пример в песочнице

**Comment by Elena-Kho** [comment]
> все оказалось тривиально просто

Помогли. Спасибо)

**Comment by ChaosDIV** [comment]
Вроде сделал все как указано в документации, но переменная ymaps остается undefined. В чем может быть проблема?

`import { yandexMap, loadYmap } from "vue-yandex-maps";

const settings = {
  apiKey: "",
  lang: "ru_RU",
  coordorder: "latlong",
  version: "2.1",
};

var ymaps = null;

далее по коду всё как в примере выше`

последняя строчка решает проблему, так как загрузка переменной асинхронна, она просто не успевает подгрузится, но ее вполне можно сделать определённой еще до загрузки, хоть и null.
