### ISSUE TITLE
 Warning с eslint

### ISSUE THREAD

**Issue by sokolovdm** [PNKBizz/vue-yandex-map#255]
Добрый день. Установил карту, все четко, но в консоли постоянно летит ворнинг.
Как лечить?

WARNING in ./node_modules/vue-yandex-maps/dist/vue-yandex-maps.esm.js
Module Warning (from ./node_modules/eslint-loader/dist/cjs.js):
Failed to load config "@vue/airbnb" to extend from.
Referenced from: /Users/mac/Documents/project/node_modules/vue-yandex-maps/.eslintrc.js
 @ ./src/components/sections/Contact.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/sections/Contact.vue?vue&type=script&lang=js&) 70:0-56 90:19-28 91:20-30
 @ ./src/components/sections/Contact.vue?vue&type=script&lang=js&
 @ ./src/components/sections/Contact.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/components/pages/Index.vue?vue&type=script&lang=js&
 @ ./src/components/pages/Index.vue
 @ ./src/router/index.js
 @ ./src/app.js
 @ ./src/entry-client.js
 @ multi webpack-hot-middleware/client ./src/entry-client.js

**Comment by PNKBizz** [comment]
Можете кинуть ссылку на ваш проект?
