### ISSUE TITLE
Отрисовка маршрутов для всех точек

### ISSUE THREAD

**Issue by ElnasAyupov** [PNKBizz/vue-yandex-map#257]
Добрый день.
У меня есть массив координат начал и концов путей.
Хотелось бы, чтобы на карте отрисовались пути для всех маршрутов.
Т.е., например у меня 3 разных маршрута, Москва Калининград, Ижевск Можга, Архангельск Североуральск, и мне нужно чтобы на карте были все 3 маршрута сразу.

**Comment by PNKBizz** [comment]
Почитайте документацию для Я.Карт
