### ISSUE TITLE
Работа с  API Я.Карт через инстанс карты по событию map-was-initialized

### ISSUE THREAD

**Issue by Elena-Kho** [PNKBizz/vue-yandex-map#259]
Не получается работать с  API Я.Карт через инстанс карты по событию map-was-initialized. Ошибка [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'MultiRoute' of undefined". Что я делаю не так? Очень не хватает в документации примеров работы с API за рамками маркеров.
https://codesandbox.io/s/nervous-butterfly-z8h2f?file=/src/App.vue

**Comment by PNKBizz** [comment]
По ссылке пустой темплейт. Реализуйте в нем ваш кейс

**Comment by Elena-Kho** [comment]
> По ссылке пустой темплейт. Реализуйте в нем ваш кейс

Сохранила. Видно теперь?

**Comment by PNKBizz** [comment]
У вас не подключены карты + криво настроен проект, кидает ошибки

**Comment by Elena-Kho** [comment]
> У вас не подключены карты + криво настроен проект, кидает ошибки

Вообще-то все подключено... Пересохранила main.js  песочнице. Я-то не вижу в песочнице ошибок кроме 'myRouter' is assigned a value but never used. (no-unused-vars) eslint

**Comment by PNKBizz** [comment]
Ну в общем у вас в качестве нагрузки для события `map-was-initialized` прилетает инстанс карты, а `ymaps` при этом находится в глобальной области видимости.

**Comment by Elena-Kho** [comment]
А как достучаться из до ymaps и всех его API? Можете пример какой-нибудь дать? Очень не хватает примера.

**Comment by PNKBizz** [comment]
`mapInitialized() { const myRouter = new ymaps.multiRouter.MultiRoute... }`
Вот так должно работать

**Comment by Elena-Kho** [comment]
> mapInitialized() { const myRouter = new ymaps.multiRouter.MultiRoute... }

Должно. Но не работает... (сохранила в песочнице)

**Comment by PNKBizz** [comment]
А как вы поняли, что не работает?

**Comment by Elena-Kho** [comment]
> А как вы поняли, что не работает?

Ошибки 
'myRouter' is assigned a value but never used. (no-unused-vars) eslint
**'ymaps' is not defined. (no-undef) eslint**

**Comment by PNKBizz** [comment]
Это ошибки линтера. При чем здесь плагин?

**Comment by Elena-Kho** [comment]
> Это ошибки линтера. При чем здесь плагин?

Пусть линтера, а что не так в коде, почему ошибки?

**Comment by PNKBizz** [comment]
'myRouter' присвоен, но не используется. (no-unused-vars) eslint
'ymaps' не определен. (no-undef) eslint

Елена, я больше не смогу отвечать вам, прошу прощения
