### ISSUE TITLE
v0.3.0 ошибка wather coords

### ISSUE THREAD

**Issue by lavodka** [PNKBizz/vue-yandex-map#26]
Error in callback for watcher "coords": "TypeError: Cannot read property '$emit' of undefined"

Появляется при любом взаимодействии с компонентом, в котором использованы Яндекс Карты.
При обновлении данных, реактивность отсутствует, ошибок нет.

**Comment by PNKBizz** [comment]
Привет!
А почему не обновитесь до последней версии?

**Comment by lavodka** [comment]
@PNKBizz обновлял до последней, 0.5.4

Там ошибка с initMap.

**Comment by PNKBizz** [comment]
@lavodka а в чем заключается ошибка? можно тест-кейс? Прошу прощения за долгое молчание, завал на работе (

**Comment by lavodka** [comment]
@PNKBizz 

> [Vue warn]: Error in callback for watcher "coords": "TypeError: Cannot read property 'initMap' of undefined"

**Comment by PNKBizz** [comment]
@lavodka проверьте последний релиз, пожалуйста (0.5.5). Ошибок быть не должно
