### ISSUE TITLE
Big size of library (not minified)

### ISSUE THREAD

**Issue by KamilOcean** [PNKBizz/vue-yandex-map#27]
May be we should minify file, becaurse it's weight more than `vue-resource` and `vue-router` together.

Может подумаем о минификации, потому что модуль весит больше чем `vue-resource` и `vue-router` вместе взятые
![screenshot_150](https://user-images.githubusercontent.com/16609819/33011301-a066ae22-cdee-11e7-81c9-e6dc0fe70b2a.png)

**Comment by PNKBizz** [comment]
PR вмержил. Спасибо!

**Comment by KamilOcean** [comment]
Круто, спасибо) а ты опубликуешь на npm минифицированную версию? =)
Не забудь только собрать перед publish)

**Comment by PNKBizz** [comment]
@KamilOcean тебе спасибо! )
Конечно опубликую. Войдет в след релиз.

**Comment by PNKBizz** [comment]
готово)
