### ISSUE TITLE
Планируется ли использование LoadingObjectManager

### ISSUE THREAD

**Issue by krkaa** [PNKBizz/vue-yandex-map#271]
Возникла необходимость отрисовать 4500 объектов, в следствии чего падает производительность. В [доке](https://tech.yandex.ru/maps/jsapi/doc/2.1/dg/concepts/loading-object-manager/about-docpage/) предлагют использовать данный инструмент

**Comment by blondinekatze** [comment]
У меня падает уже при отрисовке 2к объектов в видимой области карты. На телефонах тормозит особенно сильно

**Comment by PNKBizz** [comment]
Пока нет времени на новые фичи. Если сделаете PR - буду очень благодарен!

**Comment by AlexeyCaTHaR** [comment]
Использовал в проекте просто ObjectManager. При перекате с кластера правки минимальные 3к+ точек не делают проблем

**Comment by sinneren** [comment]
> Использовал в проекте просто ObjectManager. При перекате с кластера правки минимальные 3к+ точек не делают проблем

а как именно? 
```
<yandex-map
          ymap-class="map-current"
          use-object-manager
          :coords="mapCenter"
          :init-without-markers="false"
          :zoom="mapZoom"
          :controls="[]"
          :cluster-options="mapClusterOptions"
          @map-was-initialized="handleMapInit"
        >
          <ymap-marker
            v-for="point in points"
            :key="point.id"
            :coords="[point.latitude, point.longitude]"
            :marker-id="point.id"
            :icon="getPointIcon(point)"
            cluster-name="pointsCluster"
          />
</yandex-map>
````
use-object-manager стоит, 4500 точек. карта умирает. при этом ymap-marker 4500 раз пишется в ноду еще. Что-то не так делаю?

**Comment by AlexeyCaTHaR** [comment]
> > Использовал в проекте просто ObjectManager. При перекате с кластера правки минимальные 3к+ точек не делают проблем
> 
> а как именно?
> 
> ```
> <yandex-map
>           ymap-class="map-current"
>           use-object-manager
>           :coords="mapCenter"
>           :init-without-markers="false"
>           :zoom="mapZoom"
>           :controls="[]"
>           :cluster-options="mapClusterOptions"
>           @map-was-initialized="handleMapInit"
>         >
>           <ymap-marker
>             v-for="point in points"
>             :key="point.id"
>             :coords="[point.latitude, point.longitude]"
>             :marker-id="point.id"
>             :icon="getPointIcon(point)"
>             cluster-name="pointsCluster"
>           />
> </yandex-map>
> ```
> 
> use-object-manager стоит, 4500 точек. карта умирает. при этом ymap-marker 4500 раз пишется в ноду еще. Что-то не так делаю?

https://cathar.ru/map/ = посмотреть
https://cathar.ru/map/object_manager_filter.js = сам скриптик

**Comment by sinneren** [comment]
> По аналогии ставится у плагина

ну как нативно делать-то я знаю, а тут не понимаю, то есть ymap-marker компонент НЕ использовать, так?

**Comment by AlexeyCaTHaR** [comment]
Возможно, нужно смотреть, как он добавляет точку.
Мы не использовали компонент точки, сначала генерировали коллекцию точек

```
window[`marks-${this.uniqId}`].features.push({
    "type": "Feature",
    "id": n,
    "geometry": {
      "type": "Point",
      "coordinates": [
        placemark.coordinates.lat,
        placemark.coordinates.lon
      ]
    },
    "properties": {
      "type": placemark.mapType,
      "balloonContent": balloonLayout,
    },
    "balloon ": pointOptions,
    "options": {
      ...pointOptions
    },
  }
```
)

и потом добавляли 

`map.geoObjects.add(window[`mapPointObject-${this.uniqId}`]);`

**Comment by sinneren** [comment]
Это всё нативщина и так понятно, удалил компонент маркера и ничего не работает.
