### ISSUE TITLE
Отсутвует пример с Polyline

### ISSUE THREAD

**Issue by diamondskrt** [PNKBizz/vue-yandex-map#273]
Указываю координаты как в документации, но вовзращает Bad Request

**Comment by PNKBizz** [comment]
Сделайте пример в песочнице, пожалуйста

**Comment by diamondskrt** [comment]
> Сделайте пример в песочнице, пожалуйста

https://codepen.io/dzhan-dawydow/pen/yLJJBbN

**Comment by sffr-dev** [comment]
Почему `mark-type`?

**Comment by PNKBizz** [comment]
Не `mark-type`, а `marker-type`
