### ISSUE TITLE
Need map support when working with TS

### ISSUE THREAD

**Issue by Domovikx** [PNKBizz/vue-yandex-map#274]
Need map support when working with TS
$ npm install @types/vue-yandex-maps
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2fvue-yandex-maps - Not found
npm ERR! 404
npm ERR! 404 '@types/vue-yandex-maps@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by PNKBizz** [comment]
Поддержки TS пока в планах нет
