### ISSUE TITLE
Получение адреса по геокординатам

### ISSUE THREAD

**Issue by amitx-code** [PNKBizz/vue-yandex-map#278]
Как получить адрес по гео координатам при нажатии на клавишу
```
 <yandex-map
                ref="ymaps"
                :coords="coords"
                zoom="12"
                :scroll-zoom="true"
                style="width: 100vw; height: 100%"
                @click="onClick"
                :controls="controls"
                :settings="settings" >   </yandex-map>
```

          methods: {
            onClick(e) {
        
                console.log(e.get('coords'))
               // координаты есть как узнать адрес?
         

          
            },

**Comment by PNKBizz** [comment]
https://yandex.com/dev/maps/geocoder/
