### ISSUE TITLE
loadYmap срабатывает рано в в двух разный компонентах

### ISSUE THREAD

**Issue by Pinegin** [PNKBizz/vue-yandex-map#283]
Привет, классный плагин не нарадуюсь. Спасибо.

Сейчас начал пользоваться функцией loadYmap. Однако заметил одну проблему.
Есть два компонента корорым нужен экземпляр ymaps. В обоих идёт подключение в моунт loadYmap.
И один из компонентов рано начинает работу, до появления ymaps.

https://github.com/PNKBizz/vue-yandex-map/blob/410f3e62e7a1a3b5cbd6475eb3d86152dac657db/src/utils.js#L200

так как первый компонент уже установил script.

возможно что то подобное:

```
if (window.ymaps) return res();
    
if (document.getElementById('vue-yandex-maps')) {
   emitter.$on('scriptIsLoaded', res);
   return
}
```

**Comment by PNKBizz** [comment]
Привет! Спасибо за отзыв и за issue. Справедливое замечание. Если будет от вас PR - с удовольствием вмержу, либо на след неделе сам добавлю.

**Comment by Pinegin** [comment]
Нет проблем!

https://github.com/PNKBizz/vue-yandex-map/pull/284

**Comment by PNKBizz** [comment]
Супер! )

**Comment by sffr-dev** [comment]
v0.10.10

**Comment by PNKBizz** [comment]
v0.10.10
