### ISSUE TITLE
Кастомизация балуна

### ISSUE THREAD

**Issue by captain-zsa** [PNKBizz/vue-yandex-map#291]
Сейчас есть вариант делать clusterBalloonLayout, но это по сути тоже самое, что и слотом передавать балун (или я ошибаюсь?)
Хотелось бы иметь возможность именно кастомизировать сам балун через balloonLayout как это сделано тут: https://yandex.ru/dev/maps/jsbox/2.1/balloon_autopan/

Возможно это уже есть, но чет либо я тупой либо лыжи не едут. Может быть сам повожусь и напишу, запилив пулреквест, но пока времени нету к сожалению...

**Comment by PNKBizz** [comment]
Сейчас полностью переписываю плагин. Буду иметь ввиду ваше пожелание

**Comment by katokdoescode** [comment]
@PNKBizz Не нашел в документации, сейчас можно менять лэйаут балуна, или только передать в него слот/разметку?
