### ISSUE TITLE
Кастомизация вида кластера

### ISSUE THREAD

**Issue by kava13** [PNKBizz/vue-yandex-map#292]
В документации я не нашел ни единого способа чтобы как-то кастомизировать кластер, но не в своем коде я нашел следующий момент:

```
<yandex-map
     ...
     :cluster-options="settings.clusters"
     ...
>
...
data() {
    return {
          clusters: {
          markers: {
            preset: 'islands#darkGreenClusterIcons',
          }
        },
    } 
}
```

И благодаря этому иконка кластера стала зеленой.

Каким образом можно это понять? Есть ли где-то еще какая-то документация?

**Comment by fsRoman** [comment]
> Каким образом можно это понять? Есть ли где-то еще какая-то документация?

https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/option.presetStorage.html

**Comment by kava13** [comment]
Но почему об этом нет ни слова в документации vue-yandex-map? Я думаю, стоит упомянуть о такой возможности
