### ISSUE TITLE
Сlustering support

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#3]
When you make clustering support))

**Comment by araimbekoff** [comment]
В общем, когда сделаете поддержку кластеризации? )) 
Было бы прикольно!
Яндекс-карты рулят!

**Comment by PNKBizz** [comment]
Сорян, сейчас большой завал. Надеюсь скоро руки дойдут до плагина, буду дальше расширять функционал, в том числе и кластерами. Спасибо за фидбэк )

**Comment by PNKBizz** [comment]
Добавлено в версии 0.2
