### ISSUE TITLE
Добавить функционал конструктора карт 

### ISSUE THREAD

**Issue by bigperson** [PNKBizz/vue-yandex-map#30]
Добрый день.
Было бы очень полезно добавить возможность сделать с помощью данного пакета полноценный конструктор карт, аналогичный https://yandex.ru/map-constructor

То есть необходимо добавить возможность создавать:
- Метки
- Полилини
- Многоугольники

У при добавлении и изменении вызывать события, для получения данных по объектам допустим в json формате. У каждого объекта иметь возможность менять оформление и контент.

**Comment by PNKBizz** [comment]
@bigperson Добрый!
Ну метки, полилини и многоугольники вы можете создавать уже сейчас, указывая соответствующий marker-type. Эмит событий можно добавить, как и динамическое изменение контента.
Или вы имеете ввиду именно добавление объектов на карту пользователем?

**Comment by bigperson** [comment]
@PNKBizz Да имею ввиду динамическое добавление объектов на карту самим пользователем. http://prntscr.com/hfqoao

**Comment by PNKBizz** [comment]
Ок, буду над этим работать!

**Comment by ArtemZubarev** [comment]
@PNKBizz привет! Каким образом можно добавить событие клика на карту?

**Comment by araimbekoff** [comment]
Меня тоже этот вопрос интересует. При клике по карте получать координаты lat, lng.
Кааак? Неужели никак?

**Comment by araimbekoff** [comment]
событие на карте:
получаем ссылку через 
        @map-was-initialized="initHandler"
а на полученном объекте делаем, например:

initHandler(obj){
obj.events.add('click', function(e){console.info(e.get('coords'))})
...
}

**Comment by ArtemZubarev** [comment]
@ArtemZubarev @araimbekoff круто спасибо!

**Comment by fynduck** [comment]
Добрый день.
Есть какой то способ чтоб автоматически определять цент и зум карты в зависимости от меток?

**Comment by PNKBizz** [comment]
@fynduck компонент карты кидает событие `map-was-initialized` после инициализации в котором в качестве payload передает ссылку на инстанс карты. Дальше делаете с ним что угодно: https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/Map-docpage/#setBounds

**Comment by fynduck** [comment]
@PNKBizz Спасибо, не сразу нашел но хотя бы знал где копать ;)
