### ISSUE TITLE
Не работает дефолтное определение местоположения в мобилке

### ISSUE THREAD

**Issue by AlekseiRachkov** [PNKBizz/vue-yandex-map#300]
В консоли показывает на проблему с правами

Решение проблемы достаточно простое, в settings требуется добавить еще поле {
      apiKey = '',
      lang = 'ru_RU',
      version = '2.1',
      coordorder = 'latlong',
      debug = false,
      enterprise = Boolean
    } 
    и в зависимости от значения заменять дефолтную строку с `https://api-maps.yandex.ru`  на `https://enterprise.api-maps.yandex.ru` file utils.js

**Comment by daniluk4000** [comment]
Поддерживаю. Нужна поддержка корпоративных Я.Карт

@PNKBizz сделать PR?

**Comment by PNKBizz** [comment]
@daniluk4000 Было бы отлично

**Comment by daniluk4000** [comment]
@PNKBizz готово

Также немного поправил стиль доки

**Comment by PNKBizz** [comment]
Исправлено в версии 0.10.12
