### ISSUE TITLE
Не отображаются маркеры в инстансе карты после колбека @map-was-initialized

### ISSUE THREAD

**Issue by Escham** [PNKBizz/vue-yandex-map#302]
Я использую компонент яндекс карты, внутри которого находятся компоненты-маркеры, они перебираются обычным v-for и выводят несколько маркеров на карту. Проблема в том, что ни в mounted, ни в @map-was-intialized не отображаются эти метки. Их просто не существует в этот момент. 

Подскажите, существует ли какой-либо калбек или способ, который возвращает инстанс карты вместе с присутсвующими маркерами на карте? Мне нужно у определенного маркера после загрузки страницы открыть содержимое балуна. Сейчас это можно решить добавлением setTimeout в калбеке map-was-initialized. Но это решение как-то не очень. 

https://prnt.sc/17b71is

**Comment by playsetler** [comment]
> Сделайте пример в песочнице, если еще актуально

Зачем тебе пример если конкретно спрашивают про инстанс карты? вы когда нормальные карты на vue сделаете? сидите там штаны протираете, не можете нормальную работу со своими же картами сделать, упыри

**Comment by PNKBizz** [comment]
Уважаемый @playsetler, я не знаю когда они нормальные карты на Vue сделают. Наверное когда протрут штаны. Или всю кровь из вас выпьют. Если у вас есть желание сделать лучше - PR всегда приветствуется. Я же поддерживаю и развиваю этот плагин в свободное от работы и семьи время, которого очень мало. И требовать чего-либо вы можете только от того, кто вам что-то должен.
