### ISSUE TITLE
Неккоректное отрисовка маркеров на карте

### ISSUE THREAD

**Issue by astreiko-egor** [PNKBizz/vue-yandex-map#308]
Добрый день, столкнулся с проблемой, при работе с динамическим массивом, карта не всегда отрисовывает нужное количество маркеров.
Изначально все работает правильно:
Количество отрисованныхх маркеров = количеству компонентов ymap-marker:
![изображение](https://user-images.githubusercontent.com/31217430/130423183-c5c17ed3-d46d-4b52-b94b-942ea6a8ff46.png)
![изображение](https://user-images.githubusercontent.com/31217430/130423230-57332a0f-966b-4990-9165-ec3f128448a8.png)
Но после того, как массив с данными обновляется, происходит вот такая картина:
![изображение](https://user-images.githubusercontent.com/31217430/130423412-4cc15ff5-66b6-4b67-ad93-ef59cf6d70f5.png)
![изображение](https://user-images.githubusercontent.com/31217430/130423433-29041606-3b7b-47e2-84f7-ab46b9230a77.png)
Вызов компонентов
`
<yandex-map class="v-map__mapping"
                  :coords="coords"
                  zoom=11
                  :settings="settings"
                  :controls="[]"
                  :options="{ minZoom: '10', maxZoom: '10'}"
                  :use-object-manager="false"
                  :show-all-markers="true">
        <ymap-marker
            v-for="(item, index) in coordsMarker"
            :key="parseInt(item.id)"
            :marker-id="parseInt(item.id)"
            :coords="[item.x, item.y]"
            :icon="markerIcon"
            @click="onClickMarker(item.popup)"
        />
      </yandex-map>
`

Массив координат выглядит так:
`coordsMarker = [
{
id:"66",
popup: {},
x:"55.867427088252",
y:"37.483733058349",
},
{
id:"68",
popup: {},
x:"55.840899994976",
y:"37.495359746033",
}
]`

Проблема частично решается, если в компоненте **ymap-marker** вместо item.id использовать index, который формирует цикл v-for.

Как решить данную проблему ?

**Comment by PNKBizz** [comment]
Добрый вечер! Можете воспроизвести пример в песочнице?

**Comment by astreiko-egor** [comment]
> 
> 
> Добрый вечер! Можете воспроизвести пример в песочнице?

Киньте пожалуйста ссылку на какой именно вам это воспроизвести

**Comment by PNKBizz** [comment]
Да в какой удобнее. https://codesandbox.io/ например

**Comment by astreiko-egor** [comment]
> 
> 
> Да в какой удобнее. https://codesandbox.io/ например

https://codesandbox.io/s/happy-ives-2qtbw
Сначала выберите москва - САО - Ховрино - м. Беломорская - Улица Беломорская, 23 - отобразит правильно
Химки - Улица Калинина, 11 - не правильно, если смотреть через vue devtools там должен находится только один маркер

**Comment by pwnz22** [comment]
Всем привет,

У меня такой же баг. Передаю данные через `props` в компонент и когда фильтрую массив отрисовка неккоретно происходит, хотя в `devtools` правильное кол-во маркеров

**Comment by astreiko-egor** [comment]
> 
> 
> Да в какой удобнее. https://codesandbox.io/ например

Подскажите, будут ли какие то изменения в плагине или лучше поискать другой плагин для проекта, так как сроки не резиновые

**Comment by PNKBizz** [comment]
В эти выходные планирую заняться этой задачей. Очень мало свободного времени, к сожалению

**Comment by pwnz22** [comment]
есть update?)

**Comment by PNKBizz** [comment]
Работаю над этим. Основная работа почти все время занимает. Если есть возможность сделать PR с фиксом - буду очень признателен

**Comment by silencerspirit** [comment]
@astreiko-egor 
Ваша проблема решается уникальным :key для `ymap-marker`. А вы используете index. Поскольку ваш массив динамический(длина), то и :key должен быть уникальный. https://codesandbox.io/s/wonderful-cloud-rewmu?file=/src/App.vue - ваш пример в рабочем состоянии.

**Comment by PNKBizz** [comment]
@silencerspirit Спасибо!

**Comment by daniluk4000** [comment]
@PNKBizz Так или иначе, даже при таком раскладе маркеры почему-то перерендериваются при изменении любых данных в компоненте. Вот пример: https://codesandbox.io/s/thirsty-sammet-t7sktx?file=/src/App.vue:1563-1581

Тут, при вводе чего угодно в инпут вверху, карта каждый раз обновляется. На большом количестве объектов это фатальное поведение, приводящее к тормозящему браузеру.

**Comment by igorwebtech** [comment]
Проблема актуальная, вариант  https://codesandbox.io/s/wonderful-cloud-rewmu?file=/src/App.vue вроде рабочий, но иногда проскакивает

**Comment by daniluk4000** [comment]
@igorwebtech сейчас задачу разбираем в рамках #373, там более глобальный баг вынес на обсуждение

**Comment by igorwebtech** [comment]
Отлично, задача решается аналогичная фильтруется массив и карта так же не корректно выводит маркеры, при этом в компоненте массив который нужно. Готов так же протестировать различные варианты.

**Comment by daniluk4000** [comment]
@igorwebtech проблема с ре-рендером скорее всего будет исправлена в #380
