### ISSUE TITLE
Почему не происходят изменения при push/splice?

### ISSUE THREAD

**Issue by dev-smith** [PNKBizz/vue-yandex-map#31]
Почему при push в массив маркеров карта не перерисовывается? 
`
this.placemarks.push({
    coords: [57.8, 35.8]
});
`

И возможно ли изменять параметры уже добавленных на карту маркеров?

**Comment by PNKBizz** [comment]
Привет! 
Посмотрю, что можно сделать

**Comment by PNKBizz** [comment]
@dev-smith исправил проблему с отсутствием реакции на изменение placemarks

> возможно ли изменять параметры уже добавленных на карту маркеров?

Если мы говорим о массиве маркеров, который передается через атрибут placemarks, то поведение стандартное для реактивных объектов во Вью. Если вы имеете ввиду маркеры как компоненты, то на данный момент реализовано слежение за координатами объекта. В планах расширить реакцию на изменение других свойств.
