### ISSUE TITLE
Динамическая загрузка данных в балун

### ISSUE THREAD

**Issue by lapshinmr** [PNKBizz/vue-yandex-map#311]
Всем привет.

Не понял как можно реализовать загрузку данных в балун по клику на маркер? Т.е. нажимаем на маркер, пошел запрос на сервер, и затем балун отображает динамический контент. 

Пробежался по всем issues и документации, но так и не понял как это реализовать. Балун остается пустым.

На данным момент через key заставляю маркер сделать re-render, а на click-эвент повесил логику загрузки данных. При этом делаю event.preventDefault в эвенте. Но в таком случае приходится кликать два раза на маркер, чтобы второй раз отобразился динамический контент.

Балун создается через слот, потому что там есть логика. Но в нем как будто нет реактивности. Re-render самого балуна не приводит к успеху.

Какая логика должна быть в общем?

Или может есть способо вызвать click-эвент по маркеру программно? Тогда у меня получился бы своего рода отложенный клик.

Буду благодарен за помощь. Третий день уже бьюсь.

**Comment by PNKBizz** [comment]
Добрый день! Воспроизведите проблему в песочнице, там посмотрим. Только с минимальной логикой, достаточной для вывода проблемы

**Comment by lapshinmr** [comment]
Вот минимальный пример https://codepen.io/lapshinmr/pen/yLXGoRm 

У себя в проекте, чтобы обновить балун, я добавляю ключ к маркеру по типу :key="balloonText". Но, когда происходит загрузка данных, и ключ обновляется, балун закрывается. Т.е. мне его надо как-то заново открыть. Со стороны пользователя, нужен второй клик. Но если я открываю его через `this.myMap.balloon.open(...)`, то балун все равно не обновленный.

**Comment by PNKBizz** [comment]
Я понял проблему. Дело в том, что при инициализации маркера под капотом происходит вот такая штука `const BalloonContentLayoutClass = ymaps.templateLayoutFactory.createClass(this.$slots.balloon[0].elm.outerHTML);`, т.е. создается балун из рендера, переданного в слот. И реактивность пропадает. Если вам нужно динамически менять контент в балуне - придется делать это нативными средствами Я.Карт

**Comment by lapshinmr** [comment]
Понял. Спасибо за помощь. Буду копать тогда в сторону API карт.
