### ISSUE TITLE
"export 'h' (imported as 't') was not found in 'vue'

### ISSUE THREAD

**Issue by daniluk4000** [PNKBizz/vue-yandex-map#317]
Обновились до версии 0.11.0, появилась эта ошибка. Откат до 0.10.12 помог. Сама карта при этом работает - просто как Warning сыпется. В коде ничего не менялось у нас.

![изображение](https://user-images.githubusercontent.com/10450717/137631014-2bac1c95-77c9-4071-8ece-9c244553f56e.png)

**Comment by PNKBizz** [comment]
Да, сделано было для работы с Vue 3. Немного доработаю и катну обновление на днях. Спасибо!

**Comment by PNKBizz** [comment]
Пофиксил в версии 0.11.1

**Comment by daniluk4000** [comment]
@PNKBizz here we go again, в 0.11.3
![изображение](https://user-images.githubusercontent.com/10450717/151774616-89bde037-d4d5-4199-91b2-607af3c42843.png)
