### ISSUE TITLE
Параметры для массива placemarks

### ISSUE THREAD

**Issue by MikeChugunov** [PNKBizz/vue-yandex-map#32]
Ребят, я не совсем пойму как добавить точку на карту с balloon, hintText и т.д.

Если с компонентом всё ок, то в data.placemarks при добавлении объекта следующего вида:
```js
placemarks: [
{
    coords: [54.8, 39.8],
    balloon: {
        header: 'Test baloon',
        body: 'Test body'
    },
    hintContent: 'test hint',
    clusterName: "1",
    icon: 'cinema',
    color: 'green',
    callbacks: { click: function() {
        console.log("click");
    }}
},
...
]
```

работают только координаты и callback. Насчет clusterName не уверен. 
Пробовал balloon добавлять и в properties и в options - без толку.

**Comment by MikeChugunov** [comment]
Нашел что это делается в виде
```
coords: [54.8, 39.8],
properties: {
    balloonContentHeader: 'balloonContentHeader',
    balloonContentBody: 'balloonContentBody',
    balloonContentFooter: 'balloonContentFooter',
    clusterCaption: '<strong><s>Еще</s> одна</strong> метка',
    hintContent: '<strong>Текст  <s>подсказки</s></strong>'
},
```
добавить бы в документацию :)

**Comment by PNKBizz** [comment]
@MikeChugunov спасибо! Добавил последним коммитом в ридми ссылку на описание экземпляра в документации Я.Карт.
