### ISSUE TITLE
Маркеры не убираются с карты в Vue 3  

### ISSUE THREAD

**Issue by TurningTide** [PNKBizz/vue-yandex-map#329]
https://codesandbox.io/s/vue-yandex-maps-vue3-forked-lhcgr?file=/src/App.vue

В данном примере имеются 2 кнопки, по клику на которые меняется условие отображения маркеров в свойстве computed. Новые маркеры успешно рендерятся на карте, но старые маркеры остаются на своих местах. Причем, в дереве компонентов отображается верное количество маркеров.

**Comment by PNKBizz** [comment]
Спасибо! Буду разбираться

**Comment by PNKBizz** [comment]
Пофиксил в версии 0.12.1 (текущий `next`)
