### ISSUE TITLE
вызов метода компонента по клику на кнопку в балуне

### ISSUE THREAD

**Issue by Matthew-Risedale** [PNKBizz/vue-yandex-map#33]
есть компонент, в нем подключаю карты, можно ли как-то по кнопке на балуне вызывать метод из самого компонента?

например по клику на button вызывать selectShop
(в скриншоте оставил только касающийся сабжа код)

![screen shot 2017-11-29 at 20 48 04](https://user-images.githubusercontent.com/11299517/33390347-b4e84c98-d546-11e7-8824-e792a8cb5d64.png)

**Comment by PNKBizz** [comment]
@Matthew-Risedale привет!
Смотри - в балун передается строка, которую Vue не парсит, поэтому о существовании  методов он ничего не знает. То есть через переменную к методу обратиться не получится. Костыльнуть можно вот таким способом:

`<button onclick="javascript: document.querySelector('.button').click();">changePm</button>` 

это кнопка в темплейте, а 

`<button @click="changeIcon" class="button">changePm</button>`

кнопка в твоем шаблоне компонента, которую видит Vue (можно сделать display: none)
Но еще раз повторюсь - это костыль
Еще почитаю доку Я.Карт, возможно у них предусмотрены кнопки в балунах и методы для них.

**Comment by Matthew-Risedale** [comment]
Костыльно, конечно, но it works!!!! спасибо большое

**Comment by PNKBizz** [comment]
Не за что ) Будем искать некостыльный способ )

**Comment by artem0071** [comment]
А как в этом костыльном варианте можно передать параметр?

**Comment by bigperson** [comment]
@PNKBizz Есть ли сейчас нормальное решение? Или как можно передать параметры через костыль?

**Comment by antongloom** [comment]
Добрый день, а не подскажете способ на оборот, есть сторонний button в template и при нажатии на него должен открыться bollon) Заранее спасибо)
