### ISSUE TITLE
Как во vue 3 вызвать метод destroy()?

### ISSUE THREAD

**Issue by Wordpost** [PNKBizz/vue-yandex-map#333]
Не понимаю, как работает карта во vue3
Код из примера документации не работает, выдает ошибку
`export default defineComponent({
setup() {
    const dataMap = reactive({
      onClickYmap(e: any) {
        console.log(e.get('coords'))
      },
      return { t, ...toRefs(dataMap) }
    })
})

runtime-core.esm-bundler.js?5c40:217 Uncaught TypeError: e.get is not a function
    at onClickYmap (Index.vue?22a2:853)
    at callWithErrorHandling (runtime-core.esm-bundler.js?5c40:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?5c40:163)
    at HTMLElement.invoker (runtime-dom.esm-bundler.js?830f:301)`
Как пользоваться методами?

**Comment by PNKBizz** [comment]
Не понял вопроса

**Comment by Wordpost** [comment]
Создаю карту через компонет как на примире, есть карта, есть метки, все работает.
Провожу нужные мне манипуляции на карте и после чего нужно уничтожить созданный мной экземпляр карты.
Каким образом можно вызвать метод карты destroy() чтобы уничтожить ее, если этого не сделать, то приложение начинает глючить, когда нажимаешь на ссылки  в меню для перехода по страницам

**Comment by PNKBizz** [comment]
Думаю вам лучше обратиться к документации Я.Карт
