### ISSUE TITLE
Как заставить vue2-scrollbar работать в балуне (Nuxt)

### ISSUE THREAD

**Issue by forumgm18** [PNKBizz/vue-yandex-map#334]
Использую Nuxt.
Проблема в следующем: В дизайне балуна для метки используется scrollbar. Много контента надо выводить.
В качестве плагина для скролла используется https://github.com/BosNaufal/vue2-scrollbar
Через слот маркера (slot="balloon") не работает ((
Пробовал так:
`<template lang="pug">
 yandex-map.yamap(
   :settings="yamapSettings"  
   :coords="yamapCoords"
   :controls="yamapControls"
   :zoom="yamapZoom"
   )
   ymap-marker( 
     marker-id="123"
     :coords="yamapCoords"
     :icon="markerIcon"
     @mouseenter="yamapMouseEnter"
     @mouseleave="yamapMouseLeave"
     )
     v-yamap-baloon(slot="balloon")

</template>
`
Компонент v-yamap-baloon:

`<template lang="pug">
  .baloon
    .baloon-title Заголовок
    .baloon-body
      scroll-bar.baloon-scrollbar
        .baloon-scroll-content Тут дофига контента

</template>

<script>
import ScrollBar from 'vue2-scrollbar'
  export default {
    components: { ScrollBar },
  }
</script>
`

В доке указывается что в слот передается только визуальная часть. Соответственно плагин не работает ((
Как заставить vue2-scrollbar работать в балуне? Или как стилизовать стандартный скролл ymaps?
Если можно то пример.

**Comment by PNKBizz** [comment]
Попробуйте воспользоваться [атрибутом карты](https://vue-yandex-maps.github.io/guide/Map.html#attributes) balloon-component
