### ISSUE TITLE
Не критично: Ошибка в IE, Object doesn't support this action

### ISSUE THREAD

**Issue by MikeChugunov** [PNKBizz/vue-yandex-map#34]
Использую babel-polyfill, однако в консоли осел ругается на: 
```
 Error in callback for watcher "placemarks": "TypeError: Object doesn't support this action"
```
Watcher-а в моем инстансе у Vue для placemarks нет, только в data пустой массив в начале, потом делаю что-то вроде
```js
let self = this;
//какой-то аякс код
self.map.placemarks.push(newPlacemark);
```

Ругается то он ругается, но ничего при этом не ломается, т.е. метки выводит без проблем.

![capture](https://user-images.githubusercontent.com/9898585/33476530-be8011c2-d69b-11e7-99f3-631fbf572ac2.PNG)

**Comment by PNKBizz** [comment]
@MikeChugunov спасибо!
Посмотрю, что там опять ИЕ не поддерживает =)

**Comment by jt3k** [comment]
ну чё посмотрели ? 
У мекня в другом проекте так же ломается и карта не показывается
