### ISSUE TITLE
Как скрыть balloon на мобильных устройствах?

### ISSUE THREAD

**Issue by devmansurov** [PNKBizz/vue-yandex-map#342]
Я хотел скрыть balloon на мобильных устройствах (это когда balloon перемещается вниз автоматически) но у меня не получилось. Как можно это осуществить напримую через API Яндекс Карты или прямо через этот же плагин?

**Comment by PNKBizz** [comment]
К сожалению не могу подсказать, нужно копать в АПИ Я.Карт
