### ISSUE TITLE
Кастомная иконка маркера

### ISSUE THREAD

**Issue by NooBiToo** [PNKBizz/vue-yandex-map#343]
Хотелось бы иметь возможность подключать svg иконку маркера и иметь возможность через стили задавать цвет маркера
Есть такая возможность?

**Comment by alex-wdmg** [comment]
Это возможно через свойство `icon` у `ymap-marker`, пример:

`<ymap-marker  :icon="this.markerIcon" />`

`markerIcon: {
      layout: 'default#image',
      imageHref: require('@/assets/svg/map-pin.svg'),
      imageSize: [43, 43],
      imageOffset: [0, 0],
      contentOffset: [0, 15],
      contentLayout: '<div>$[properties.iconContent]</div>'
}`

По-поводу "задавать цвет стилями" не очень понятно. Яндекс.Карты отрисовывает это в canvas. Но цвет маркера можно менять применяя различный layout, подробнее в [документации](https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/option.presetStorage.html).

**Comment by NooBiToo** [comment]
Спасибо, буду пробовать

**Comment by NooBiToo** [comment]
а можно ли их использовать инлайново?
`
<ymap-marker
                :coords="coord"
                :marker-id="index"
                :key="index"
                icon-layout="default#imageWithContent"
                :icon-image-size="[0, 0]"
                :icon-image-offset="[0, 0]"
                icon-content-layout='<div style="background: red; width: 50px; color: #FFFFFF; font-weight: bold;">123</div>'
              />
`
