### ISSUE TITLE
Карта из примера не отображается (проблема с высотой)

### ISSUE THREAD

**Issue by PersonaA** [PNKBizz/vue-yandex-map#35]
Создал в песочнице проект:
https://codesandbox.io/s/6lym8o6xx3

Вставил код из примера. Компоненты карты имеют высоту `0`.

**Comment by sazarkin** [comment]
Последний комит изменил логику
Выглядит так, что теперь нужно иметь класс
```css
  .ymap-body 
    width: 100%
    height: 100%
```
https://codesandbox.io/s/2oyx22lpvn

**Comment by PNKBizz** [comment]
Так точно.

<yandex-map> has a class ymap-container and child element with class ymap-body, where rendering map instance.
