### ISSUE TITLE
this.myMap is undefined Vue 3

### ISSUE THREAD

**Issue by icrazymob** [PNKBizz/vue-yandex-map#355]
TypeError: can't access property "panTo", this.myMap is undefined
Ставил @next версию. Что с глобальной установкой, что через компонент локально - одинаково. Причем карта появляется, работает, но выдается эта ошибка и крашится дальнейший рендеринг остальных компонентов. Абсолютно голая карта с передачей только apikey и coords как центра.

**Comment by avgulyaev** [comment]
У меня та же проблема с Vue 2.6.14 + Nuxt 2.15.8.

TypeError: this.myMap is undefined
Uncaught TypeError: e is null

**Comment by PNKBizz** [comment]
Обновил обе версии

**Comment by avgulyaev** [comment]
Спасибо! Всё работает!
