### ISSUE TITLE
Zoom a map on load to show all points

### ISSUE THREAD

**Issue by PersonaA** [PNKBizz/vue-yandex-map#36]
Is possible to zoom a map on load to show all points?

https://tech.yandex.ru/maps/jsbox/2.1/clusterer_create

```
myMap.setBounds(clusterer.getBounds(), {
  checkZoomRange: true
});
```

**Comment by PNKBizz** [comment]
https://github.com/PNKBizz/Inlearno-test/blob/master/src/pages/map.vue

see string 42

**Comment by PersonaA** [comment]
Thanks!
