### ISSUE TITLE
При импорте грузится еще один экземпляр vue

### ISSUE THREAD

**Issue by rideorgtfo** [PNKBizz/vue-yandex-map#37]
- При импорте
`import YmapPlugin from 'vue-yandex-maps'`
подгружается еще один экземпляр библиотеки. Это можно заметить по 2м сообщениям _"You are running Vue in development mode."_
- При импорте исходника
`import YmapPlugin from 'vue-yandex-maps/src/index.js'` все нормально.

**Comment by PNKBizz** [comment]
Привет! Спасибо, посмотрю.

**Comment by veresnikov** [comment]
+1. Такая же штука происходит.

**Comment by PNKBizz** [comment]
fix in v0.6.3
Спасибо за репорты, друзья!
