### ISSUE TITLE
Как установить кастомный макет балуна кластера «Карусель»

### ISSUE THREAD

**Issue by dmshutof** [PNKBizz/vue-yandex-map#372]
Не удается вставить контент внутрь слайда балуна

[Пример на codepen](https://codepen.io/dmitrij-shutow/pen/vYWbZpO)

Подскажите пожалуйста, каким образом это можно реализовать? Что я делаю не так?

**Comment by PNKBizz** [comment]
Вы изменяете опции кластера после его инициализации. Он уже этого не видит. Вам нужно получить объект кластера с карты и изменить его опции напрямую.

**Comment by dmshutof** [comment]
> Вы изменяете опции кластера после его инициализации. Он уже этого не видит. Вам нужно получить объект кластера с карты и изменить его опции напрямую.

Спасибо! А не подскажете, как получить объект? Только начал разбираться с картами, много чего не понимаю еще

**Comment by PNKBizz** [comment]
https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/map.GeoObjects.html
