### ISSUE TITLE
Дублирующаяся отрисовка маркеров на карте

### ISSUE THREAD

**Issue by daniluk4000** [PNKBizz/vue-yandex-map#373]
Поведение примерно описано в задаче #308. 

Из свежего: https://codesandbox.io/s/thirsty-sammet-t7sktx?file=/src/App.vue:1563-1581

При вводе чего угодно в поле ввода (input наверху страницы) маркеры почему-то отрисовываются заново. На огромной карте это приводит к проблемам в производительности и даже к дубликатам, если используются кластеры.

Лучше всего проблема видна вот тут при использовании Firefox: https://av.ru/i/072281/

Откройте наличие в магазинах -> на карте -> начните вводить что-то в поиск посимвольно, например, "удальцова" или какую-то белиберду, не сильно важно, главное быстро. Я могу гарантировать, что маркеры не изменяются, там стоит задержка в полсекунды на это. Я также ставил задержку в секунду и вообще ставил маркеры на константу - при вводе чего угодно в инпут шел ре-ренден. 

Сразу скажу, я не смог разобраться с ходу, как это исправить, там вероятно достаточно сложная логика.

**Comment by PNKBizz** [comment]
Ок, возьму в приоритете. Версия Вью - 2?

**Comment by daniluk4000** [comment]
Ага

Спасибо заранее!

**Comment by daniluk4000** [comment]
Я тут нашел время и подебажил

Багу вызывает $watch, а затем objectComparison. В watch прилетают события на 2 пропса, которые абсолютно одинаковы. objectComparison явно должен отсеивать не одинаковые объекты, но не делает этого.

А не делает почему:

![изображение](https://user-images.githubusercontent.com/10450717/161490385-02f3264c-d2a1-4256-bfb1-b4a8ea1c6f1c.png)

А если пришла функция?

**Comment by daniluk4000** [comment]
@PNKBizz странный прикол. Я тут заметил, что мы давным-давно обновились, но ничего не поменялось.

Я глянул прям исходники пакета и там нет моих изменений.

![изображение](https://user-images.githubusercontent.com/10450717/172160277-72848eda-b5cf-49da-b2ee-f6a791767412.png)

**Comment by daniluk4000** [comment]
@PNKBizz я все перепроверил

![изображение](https://user-images.githubusercontent.com/10450717/172332642-ba00ce5b-51ad-49f2-87f1-7243fd863315.png)

**Comment by daniluk4000** [comment]
@PNKBizz ping

**Comment by PNKBizz** [comment]
Проверь в версии .11, пожалуйста

**Comment by daniluk4000** [comment]
@PNKBizz работает великолепно, спасибо)
