### ISSUE TITLE
Что то поломалось?

### ISSUE THREAD

**Issue by artem0071** [PNKBizz/vue-yandex-map#38]
Раньше все работало нормально, но примерно в декабре вышло обновление и все полетело.
Подумал что я где то накосячил и в итоге просто удалил
Сейчас вновь понадобился данный компонент, но он так и не заработал

Начал разбираться, но ошибки так и не нашел. Но их и нет в консоли.
Подумал может у меня в проекте проблема со стилями или какой то код не дает показать карту.

В итоге создал чистый новый проект, установил только данный плагин. Выключил все браузерные модули(такие как adBlock и остальные)

Скопировал пример из read.me, но в итоге все равно не заработало. Ошибок как не было в консоли, так они и не появились.

В DOM видно что все вставилось, но ничего не показывается
![2018-01-13 14 36 34](https://user-images.githubusercontent.com/21971875/34905681-2fde3e1c-f86f-11e7-8b9d-b1771d1df44b.png)
![2018-01-13 14 35 39](https://user-images.githubusercontent.com/21971875/34905682-2ffa05b6-f86f-11e7-8123-3e97763fa531.png)

Вот весь код:
`<template>
  <div id="app">

    <yandex-map
      :coords="[54.62896654088406, 39.731893822753904]"
      zoom="10"
      style="width: 600px; height: 600px;"
      :behaviors="['ruler']"
      :controls="['trafficControl']"
      :placemarks="placemarks"
      map-type="hybrid"
      @map-was-initialized="initHandler"
    >

      <ymap-marker
        marker-type="placemark"
        :coords="[54.7, 39.7]"
        hint-content="Hint content 1"
        :balloon="{header: 'header', body: 'body', footer: 'footer'}"
        :icon="{color: 'green', glyph: 'cinema'}"
        cluster-name="1"
      ></ymap-marker>

      <ymap-marker
        marker-type="placemark"
        :coords="[54.6, 39.8]"
        hint-content="Hint content 1"
        :balloon="{header: 'header', body: 'body', footer: 'footer'}"
        :icon="{color: 'green', glyph: 'cinema'}"
        cluster-name="1"
      ></ymap-marker>

      <ymap-marker
        marker-type="circle"
        :coords="[54.62896654088406, 39.731893822753904]"
        circle-radius="1600"
        hint-content="Hint content 1"
        :marker-fill="{color: '#000000', opacity: 0.4}"
        :marker-stroke="{color: '#ff0000', width: 5}"
        :balloon="{header: 'header', body: 'body', footer: 'footer'}"
      ></ymap-marker>

    </yandex-map>

  </div>
</template>
<script>

  import { yandexMap, ymapMarker } from 'vue-yandex-maps'

export default {
  name: 'app',
  components: {
    yandexMap, ymapMarker
  },
  data() {
    return {
      placemarks: [
        {
          coords: [54.8, 39.8],
          properties: {}, // define properties here
          options: {}, // define options here
          clusterName: "1",
          callbacks: { click: function() {} }
        }
      ]
    }
  },
  methods: {
    initHandler(){}
  }
}
</script>
<style>
</style>
`

**Comment by PNKBizz** [comment]
Привет!
дело скорее всего в стилях. Раньше были инлайновые width и hight по 100%, но я решил их удалить в пользу навешивания класса.
`<yandex-map>` has a class `ymap-container` and child element with class `ymap-body`, where rendering map instance.
То есть, чтобы сделать все как раньше - пропишите класс 

```CSS
.ymap-body {
  width: 100%;
  height: 100%;
}
```

Отпишите, если поможет - я закрою ишью

**Comment by artem0071** [comment]
Да, помогло
Спасибо большое!

**Comment by PNKBizz** [comment]
Не за что )

**Comment by hetsketch** [comment]
@PNKBizz было бы неплохо добавить эту инфу в readme. Думаю, что не я один тупил и не понимал, что не так)

**Comment by PNKBizz** [comment]
@hetsketch Да, я сейчас работаю над релизом, в котором будет возможность определять свой класс. Тогда все и исправлю

**Comment by hetsketch** [comment]
@PNKBizz круто! Так держать 😀

**Comment by hunty** [comment]
потратил много часов чтобы найти решение) в доках ныне это нет, а yamap-class почему-то не работает с %.

**Comment by PNKBizz** [comment]
@hunty Не очень понял о чем вы...

**Comment by hunty** [comment]
есть родительский блок, который имеет высоту 50% от родителя. При указании стиля для класс указанного через **yamap-class** в 100% по ширине и высоте, карта не показывается. Работает только со значениями в px. Карта так же не показывается, если задавать  через определение стиля для класса
` .ymap-container {
  width: 100%;
  height: 100%;
}`
В моем случае, рабочей оказалась такая комбинация:
`    .ymap-container {
        height: 100%;
        width: 100%;
    }
    .ymap-body {
        width: 100%;
        height: 100%;
    }`

**Comment by PNKBizz** [comment]
@hunty `ymap-class`

**Comment by hunty** [comment]
Все верно, опечатался. Стиль задается через него корректно, но не отрабатывает как надо.

**Comment by PNKBizz** [comment]
создайте пример в песочнице, пожалуйста
