### ISSUE TITLE
Error in mounted hook: "TypeError: this.addMarker is not a function"

### ISSUE THREAD

**Issue by Nick-Anikin-dev** [PNKBizz/vue-yandex-map#386]
`<yandex-map  :controls="['zoomControl']" :zoom="mapZoom" :coords="mapCoords" :settings="mapSettings">
              <ymap-marker v-for="complex of complexesCards"
                           :coords="[complex.longitude,complex.latitude]"
                           :marker-id="complex.id"
                           :hint-conten="complex.name"
                           :icon="{
                            layout: 'default#image',
                            imageHref: cameraAccident,
                            imageSize: [43, 55],
                            imageOffset: [-22, -55],
                            contentOffset: [-22, -55],
                            contentLayout: '<div>$[properties.iconContent]</div>'
                         }"
              />
            </yandex-map>`

**Comment by PNKBizz** [comment]
Сделайте пример в песочнице
