### ISSUE TITLE
changeble markers

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#39]
"Ура! Пишу на русском! )))"

Приветствую!
Вчера хотел прикрутить эту карту. Больно она нравится моему руководству (в плане того, как выглядит она на yandex.ru/maps).

И вот вчера столкнулся с проблемой:
Я расположил единственный маркер на карте по определенной позиции и и дал центровые коорд-ты на карте. 
При клике на карту, я хочу, чтобы маркер поменялся. Делал я это тем, что координаты маркера задавал через data:{coords:[lng, lat]}
Кликнув на карту, и получив новые координаты, я изменил значения coords, но вместо ожидаемого - ошибка. (((

И вообще, предусмотрена ли возможность реактивной смены местоположения элементов на карте?

Спасибо!

**Comment by PNKBizz** [comment]
Привет! 
Да, есть проблема ((( С последними исправлениями занес ошибку. Спасибо
Тесты нужны ((( А вот времени на них нет совсем...

**Comment by araimbekoff** [comment]
Хорошо, будем ждать исправлений!

**Comment by PNKBizz** [comment]
@araimbekoff исправлено в версии 0.6.4
