### ISSUE TITLE
loadYmap не передается  apiKey в ymaps

### ISSUE THREAD

**Issue by kit52** [PNKBizz/vue-yandex-map#390]
Использую пример из документации для получения глобального ymap для геокодирования и не работает геокод тк в ymaps не передаются почему-то мои настройки

`<template>
  <yandex-map v-if="coordsGetter" :coords="coordsGetter" :zoom="zoom" @map-was-initialized="mapLoaded"
    :controls="controls" ref="map2">
    <ymap-marker v-if="marker.coords" :key="marker.id" :marker-id="marker.id" :coords="marker.coords"></ymap-marker>
    <ymap-marker v-if="selectedSearchPlace.value" :key="selectedSearchPlace.data.fias_id"
      :marker-id="selectedSearchPlace.data.fias_id"
      :coords="[selectedSearchPlace.data.geo_lat, selectedSearchPlace.data.geo_lon]">
    </ymap-marker>
  </yandex-map>
</template>

<script setup >
import { yandexMap, ymapMarker, loadYmap } from "vue-yandex-maps";
import { useDeliveryStore } from "@/store/deliveryStore.js";
import useDelivery from "@/hooks/useDeliveryStore.js";
import { onMounted, ref } from "vue"
const { coordsGetter } = useDelivery()

const map2 = ref(null)

const controls = ["zoomControl"];
const zoom = 10;
const settings = {
  lang: "ru_RU",
  coordorder: "latlong",
  version: "2.1",
  apiKey: "7f037fcc-21f0-4c1b-ad6e-1f292ef45a2f"
};
let marker = ref(null);
let myMap = ref(null);

const delivery = useDeliveryStore();
const { selectedSearchPlace } = useDelivery()

function mapLoaded(e) {
  const maps = map2.value.myMap
  myMap.value = e;
  delivery.mapSetter(map2.value.myMap);
  myMap.value.events.add('click', (e) => {
    const coords = e.get('coords')
    marker.value = {
      id: "1",
      coords: coords,
    }
  })
}
// function onClick(e) {
//   console.log('click')
//   this.coords = e.get('coords');
// }
onMounted(async () => {
  await loadYmap({ ...settings });
  console.log(window.ymaps);
})

</script>
<script>
export default {
  name: "DeliveryMap"
}
</script>
<style scoped>
</style>`

**Comment by kit52** [comment]
Воспроизвести там нет возможности. Как я понял проблема была в том, что после инициализации карты через компонент и последующей через loadMap  ключ не передавался. Решение. Запустил loadYmap в родительском компоненте карт.

**Comment by playsetler** [comment]
> Воспроизвести там нет возможности. Как я понял проблема была в том, что после инициализации карты через компонент и последующей через loadMap ключ не передавался. Решение. Запустил loadYmap в родительском компоненте карт.

Что значит запустил в родительском компоненте карт? Не судьба сразу наглядно показать? Я не понимаю таких людей, либо вообще не отвечают если нашли решение, либо херню ответят понятную только им
