### ISSUE TITLE
options карты не реактивен

### ISSUE THREAD

**Issue by 1001v** [PNKBizz/vue-yandex-map#395]
Привет. У компонента <yandex-map/> есть проперти options. Как видно по исходному коду, options передается в конструктор карты при ее создании. После этого компонент никак не реагирует на возможное изменение options. Возможный сценарий использования options в реактивном виде это изменение опции restrictMapArea. Без реактивности приходится вызывать options.set у инстанса карты.

**Comment by PNKBizz** [comment]
Думаю это очень узкий кейс, который легко обходится способом, который вы описали
