### ISSUE TITLE
Актуальна ли текущая версия для Vue3 + TypeScript?

### ISSUE THREAD

**Issue by lakkinzimusic** [PNKBizz/vue-yandex-map#396]
Добрый день, спасибо за Вашу работу! 
Подскажите, пожалуйста, текущую версию  (0.12.3) можно считать рабочей для связки Vue3 + TypeScript?

Установка: 
`npm install vue-yandex-maps@next`
Версия vue - 3.2.37, compositionApi
Задекларирован модуль vue-yandex-maps.d.ts
Компонент карты зарегистрирован локально

Неизменно получаю **warning** 
`Unhandled error during execution of render function `
**+ ошибку**
`Uncaught (in promise) TypeError: this.$slots.default is not a function`

Несмотря на ошибку,  в режиме develop карта отображается, доступ к инстансу через @map-was-initialized имеется
В продакшне карта не отображается. 

Можно ли ожидать в ближайшем будущем свежую документацию? И в какую сторону я могу двигаться для разрешения этой проблемы?

Спасибо!

**Comment by NextStepOfEvolution** [comment]
Тоже столкнулся с этой ошибкой. 
Хотел дать пользователю добавить свой маркер на чистой  #карте.

**Comment by daniluk4000** [comment]
Да, аналогично, без маркеров не пашет

Типизации у этой библиотеки вообще нет. Надо будет как нибудь в свободное время прикрутить, а то тоже уже есть потребность

**Comment by PNKBizz** [comment]
@daniluk4000 @lakkinzimusic Ребята, есть наработка пакета полностью на TS. В выходные опубликую как бету. Последний раз ее трогал 4 месяца назад. С тех пор многое поменялось в жизни, совершенно нет времени довести до ума. Если есть желание - можем совместными усилиями доделать до нормального вида.

**Comment by daniluk4000** [comment]
@PNKBizz я люблю TS и приводить всё к TS. Буду рад помочь :)

**Comment by Flashantik** [comment]
Ошибка возникает если на карту ничего не передано. Попробуйте передать хотя бы пустую строку так, и ошибка пропадет. Ошибка возникает из-за того что не переданно никакого default слота 


```
No error 
<yandexMap :settings="ySettings" :coords="[55.751244, 37.618423]">
  <!--  -->
</yandexMap>

error 
<yandexMap :settings="ySettings" :coords="[55.751244, 37.618423]">
</yandexMap>
```

> Да, аналогично, без маркеров не пашет
> 
> Типизации у этой библиотеки вообще нет. Надо будет как нибудь в свободное время прикрутить с пул реквестом, а то тоже уже есть потребность
> 
> Но у автора явно завал сейчас

**Comment by daniluk4000** [comment]
@PNKBizz поделишься наработками? Может в какую-то отдельную ветку кинуть

Либо я могу с нуля порефачить

**Comment by PNKBizz** [comment]
@daniluk4000 В субботу выложу бету

**Comment by PNKBizz** [comment]
Всем привет! Выложил бету на TS. Нужны доработки по документации (в том числе английской версии), тестам. Буду благодарен за поиск проблем, ошибок и вообще проверке работоспособности. Новые фичи будут добавляться по необходимости и запросам. 
В общем - [вэлкам](https://github.com/PNKBizz/vue-yandex-maps)
