### ISSUE TITLE
Подключение в Nuxt

### ISSUE THREAD

**Issue by mr4eshir** [PNKBizz/vue-yandex-map#4]
По возможности, сделайте поддержку ssr, или напишите в документации, как подключить плагин в Nuxt. Если следовать алгоритму на сайте Nuxt для подключения client-side only плагинов, попадаю на ошибки разных мастей, самая безобидная из которых - сайт работает, но карта не отображается, а в консоли пишет про отличия деревьев VNode и ClientNode.

**Comment by PNKBizz** [comment]
Привет! Как раз сейчас разбираюсь с Нукстом. Обязательно сделаю полную поддержку ssr

**Comment by PNKBizz** [comment]
Привет! Не мог бы ты проверить работу с Nuxt версии 0.3.0? Я там кое-что поменял, а самому проверить пока не получается... Спасибо )

**Comment by mr4eshir** [comment]
Сегодня-завтра проверю.

**Comment by PNKBizz** [comment]
@mr4eshir спасибо!

**Comment by mr4eshir** [comment]
Карта успешно появилась на странице. Правда, консоль ругается, что деревья нодов рассинхронизировались. Но, главное, карта появилась. :-)

**Comment by PNKBizz** [comment]
@mr4eshir отлично! Как только дойду до изучения Нукста, поправлю полностью =) Еще раз спасибо за репорт и помощь в тестировании

**Comment by mr4eshir** [comment]
Возможно, присоединюсь. Сам сейчас активно изучаю Вью/Нукст.

**Comment by PNKBizz** [comment]
@mr4eshir буду очень рад любой помощи =)
