### ISSUE TITLE
Ошибка стилей

### ISSUE THREAD

**Issue by Apupenchik** [PNKBizz/vue-yandex-map#40]
При использовании версии 6.0.0 и выше, высота дочерних блоков ".ymap-body" устанавливается как 0px, хотя в style передано "height: 245px". Только ".ymap-container" принимает правильное значение.

Рендер:
```html
...
<section class="ymap-container" style="width: 100%; height: 245px;">
  <div id="yandexMap68318" class="ymap-body">
    <ymaps class="ymaps-2-1-60-map" style="width: 1920px; height: 0px;">
      <ymaps class="ymaps-2-1-60-map ymaps-2-1-60-i-ua_js_yes ymaps-2-1-60-map-bg-ru ymaps-2-1-60-islets_map-lang-ru" style="width: 1920px; height: 0px;">
...
```
Vuejs:
```javascript
<template>
    <yandex-map
            :coords="[55.0, 40.0]"
            zoom="11"
            style="width: 100%; height: 245px;"
    ></yandex-map>
</template>
<script>
    export default {}
</script>
```

**Comment by PNKBizz** [comment]
Привет! Попробуй назначить стиль `width: 100%; height: 245px;` классу `ymap-body` у себя в стилях

**Comment by Apupenchik** [comment]
Это помогло, но хотелось бы просто передавать стили компоненту, ибо он мне нужен в нескольких местах проекта и с разными размерами.

**Comment by PNKBizz** [comment]
@Apupenchik тогда попробуйте  классу `ymap-body` у себя в стилях назначить `width: 100%; height: 100%;` и стилями задавать высоту контейнеру

**Comment by Apupenchik** [comment]
@PNKBizz Спасибо, но вот только я не пойму это я накосячил со стилями или рендерится так как и должно?

**Comment by PNKBizz** [comment]
Рендерится так, как и должно ) Просто в отдельных случаях захардкоженные стили ширины и высоты по 100% у элемента, который сейчас имеет класс `ymap-body` очень осложняли верстку...
