### ISSUE TITLE
Как добавить Polygon на карту?

### ISSUE THREAD

**Issue by killbox** [PNKBizz/vue-yandex-map#41]
Как добавить Polygon на карту?
Буду благодарен за небольшой пример.

**Comment by PNKBizz** [comment]
Я так понимаю основной вопрос в указании координат? 
```JavaScript
:coords="[[[54.6, 39.7], [54.71, 39.82], [54.52, 39.68]]]" // треугольник без внутреннего контура
```
или
```JavaScript
:coords="[[[54.6, 39.7], [54.71, 39.82], [54.52, 39.68]], [[54.598, 39.706], [54.621, 39.736], [54.55, 39.691]]]" // треугольник c внутренним контуром
```

**Comment by killbox** [comment]
а как добавить обработчик для создания полигона вручную? типа draw

**Comment by PNKBizz** [comment]
@killbox а вот это пока никак... либо курить доки Yandex Maps и работать напрямую с инстансом карты

**Comment by killbox** [comment]
было бы отлично, но вот не удалось получить Ymaps в своем компоненте...

**Comment by PNKBizz** [comment]
После инициализации компонент yandex-map кидает event `map-was-initialized` со ссылкой на инстанс
