### ISSUE TITLE
Zoom и setBounds

### ISSUE THREAD

**Issue by Frallen** [PNKBizz/vue-yandex-map#412]
При инициализации карты мне необходимо показать все точки которые доступны, я ставлю zoom, он показывает нужный зум на пару сек, и потом делает зум и точки игнорируется. Я решил что мне необходим `@map-was-initialized` и   `map.setBounds(map.geoObjects.getBounds());` . Но тут появилась проблема в `map` нет метода `setBounds`. 

Я решил проверить в песочнице, но там тоже нет этого метода, что делать?

[`codesandbox`](https://codesandbox.io/s/vue-template-forked-jy18b5?file=/src/App.vue:1056-1065)
@PNKBizz

**Comment by dsvitnev** [comment]
Как это нет?
https://yandex.ru/dev/maps/jsapi/doc/2.1/ref/reference/Map.html#method_detail__setBounds
Всё есть, всё работает
Прочитайте документацию метода, если границы не устанавливаются, тогда ловите промис с ошибкой, выводите в консоль и смотрите в чём дело
Отпишитесь потом о своём прогрессе
