### ISSUE TITLE
Nuxt Uncaught TypeError: Cannot read properties of null (reading 'offsetWidth')

### ISSUE THREAD

**Issue by Ffinnis** [PNKBizz/vue-yandex-map#416]
У меня на сайте две карты, одна работает нормально, а с этой проблемы.

`<div v-if="isMapCanBeLoaded && isMounted" class="apartment-map">
          <yandex-map :coords="apartment?.location">
            <ymap-marker marker-id="home" :coords="apartment?.location" />
          </yandex-map>
        </div>`

`mounted(): void {
      this.isMounted = true;
  }`

ClientOnly пробовал, нет идей почему так происходит

UPD: Проблема появляется только если открывать страницу в новом табе или сразу по ссылке, но, увы, мне нужно, чтобы открытие было в новом табе

**Comment by PNKBizz** [comment]
Приведите пример всего компонента
