### ISSUE TITLE
Behavior scrollZoom

### ISSUE THREAD

**Issue by vokuev** [PNKBizz/vue-yandex-map#42]
Добрый день, добавляю в параметры карты: :behavior="['scrollZoom']" , но не появляется прокрутка мышкой

`<yandex-map
                            :coords="cities[selectedCity].coords"
                            zoom="10"
                            style="width: 100%; height: 600px;"
                            :cluster-options="{
                                1: {clusterDisableClickZoom: true}
                              }"
                            :controls="['trafficControl', 'routeEditor']"
                            :behavior="['scrollZoom']"
                            :placemarks="placemarks" //
                            map-type="map"></yandex-map>`

**Comment by PNKBizz** [comment]
Привет! Проверьте в версии 0.6.10.
Там была ошибка, не связанная с этой фичей, но устранив ее - проверил, все работает.
Отпишитесь, если будет все ок

**Comment by vokuev** [comment]
Да, все работает! Спасибо
