### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by nestle49** [PNKBizz/vue-yandex-map#425]
```
import { loadYmap } from 'vue-yandex-maps'

export default {
  async mounted() {
    await loadYmap({ ...settings, debug: true });


```
Это дает ошибку

Работает так:

```
const yandexMapsUtils = require('vue-yandex-maps/src/utils');

await yandexMapsUtils.loadYmap({ ...settings, debug: true });
```

**Comment by PNKBizz** [comment]
Какая версия пакета?

**Comment by nestle49** [comment]
"vue-yandex-maps": "^0.12.3"

Да в общем-то, любая, я пробовал и последнюю без @next.

Проект на vue3 + vite, при обновлении страницы тупо отдает 404

Проблема в импорте 
`import { loadYmap } from 'vue-yandex-maps'`
При переходе на страницу с картой с другой страницы заводится, при первоначальной загрузке страницы с картой или обновлении 404

Я сперва подумал о том, что вероятно импорт происходит на сервере, а должен только на клиенте и это вызывает ошибку гидрации, либо просто обращение идет в лоадере к сущностям, существующим только на клиенте, но нет. Когда я обернул весь компонент в v-if="isMounted", на мое удивление, проблема не исчезла

Вот рабочий вариант
```
const yandexMapsUtils = (await import('vue-yandex-maps/src/utils'));

await yandexMapsUtils.ymapLoader({
        apiKey: '',
        lang: 'ru_RU',
        coordorder: 'latlong',
        enterprise: false,
        version: '2.1',
        debug: true
    });
```

А еще в процессе была обнаружена дополнительная ошибка: если записать карту в реактивную переменную, а затем добавить на нее multiRoute, это вызовет ошибку. Если переменная не реактивная, все ок

Вот псевдокод, воспроизводится с примерами из документации
```
const map = ref<ymaps.Map | null>(null);

map = new globalThis.ymaps.Map(...);

const referencePoints = [
    'Калининград, улица Грига, 1',
    'Калининград, Пионерская улица, 68А',
    'Калининград, улица Фрунзе, 26',
    'Калининград, Пролетарская улица, 83'
];

const multiRoute = new globalThis.ymaps.multiRouter.MultiRoute({
        referencePoints,
        params: {
            viaIndexes: [1, 2] // temp

        }
    }, {
        wayPointDraggable: true,
        routeStrokeWidth: 3,
        routeStrokeColor: 'F96857',
        routeStrokeOpacity: 1,
        routeActiveStrokeOpacity: 1,
        routeActiveStrokeColor: 'F96857',
        viaPointIconRadius: 8,
        viaPointIconFillColor: '#f96857',
        viaPointActiveIconFillColor: '#f96857',
        viaPointDraggable: true,
        preventDragUpdate: true,
        boundsAutoApply: true,
        wayPointVisible: false
    });
    
    map.geoObjects.add(multiRoute);
```

Для исправления я просто убрал реактивность
`let map: ymaps.Map | null = null;`

**Comment by PNKBizz** [comment]
Попробуйте использовать версию `@beta`. Она только для Vue3 + написана на TS.
А в целом весь плагин - это чисто клиентская история. При запуске на сервере будут ошибки

**Comment by nestle49** [comment]
@PNKBizz 

@beta - то есть версия сейчас не стабильна? Можно ли ожидать стабильную?

В общем, @beta ситуацию не изменила, по-прежнему куча ошибок, даже при использовании только на клиенте.

Хотя можно было ожидать проверку на стороне пакета, что код выполняется на клиентской стороне, но проблема даже совершенно не в этом, а в первую очередь в том, что взаимодействовать с картой через реактивную переменную нельзя

Cоответственно такой код

`const map = ref<ymaps.Map | null>(null);`

Превращает карту в нерабочую

`let map: ymaps.Map | null = null;`

Такой работает с горем пополам

И вот таким импортом

```
const yandexMapsUtils = (await import('vue-yandex-maps/src/utils'));

await yandexMapsUtils.ymapLoader({
        apiKey: '',
        lang: 'ru_RU',
        coordorder: 'latlong',
        enterprise: false,
        version: '2.1',
        debug: true
    });
```

**Comment by nestle49** [comment]
Any ideas?

**Comment by nestle49** [comment]
upd: `ref` не будет работать с инстансом карты, потому что вызывает глубокое (deep) преобразование, вместо этого необходимо использовать `shallowRef()`

`const map = shallowRef<ymaps.Map | null>(null);`
