### ISSUE TITLE
У маркера нет options?

### ISSUE THREAD

**Issue by artem0071** [PNKBizz/vue-yandex-map#43]
Нужно было создать опцию у маркера 'draggable'
Но как выяснилось у него нет такой опции, но есть для массива 'placemarks'

Или я что то не так сделал?

Пытался так:
`<ymap-marker
        marker-type="placemark"
        :options="{draggable:true}"
        :coords="[54.62896654088406, 39.731893822753904]"
      ></ymap-marker>`

**Comment by PNKBizz** [comment]
Привет! Да, пока что у маркера нет такой возможности. Постараюсь реализовать в ближайшем релизе

**Comment by PNKBizz** [comment]
Теперь есть =)
