### ISSUE TITLE
Проблема с отображением маркеров в одном пункте

### ISSUE THREAD

**Issue by vokuev** [PNKBizz/vue-yandex-map#44]
Добрый день, после обновления, как я понимаю, появилась такая проблема, если по одному адресу расположены несколько мест, то при нажатии на них появляются ошибки в консоли и отображение перестает работать как и с другими точками так и вообще с картой.

Вот так выглядит если точка одна : https://yadi.sk/i/mdnWYQi03S5fPm

Если много то все падает с ошибками: https://yadi.sk/i/b-tfeiKY3S5fVe

Ошибки: https://yadi.sk/i/ptuNQ-mW3S5fJk

**Comment by PNKBizz** [comment]
Привет! 
Спасибо, проверю!

**Comment by vokuev** [comment]
Ну как? Удалось воспроизвести ошибку?

**Comment by PNKBizz** [comment]
@vokuev не получается воспроизвести. Попробуй с последней версией или кинь код посмотреть

**Comment by PNKBizz** [comment]
https://codepen.io/anon/pen/XZpgyK
обрати внимание на cluster-options -> layout
