### ISSUE TITLE
@map-was-initialized не работает

### ISSUE THREAD

**Issue by twentytwo777** [PNKBizz/vue-yandex-map#441]
<YandexMap
            :settings="settings"
            :coordinates="coordinates"
            :controls="controls"
            :zoom="zoom"
            @map-was-initialized="initHandler"
        >
            <YandexMarker :coordinates="coordinates" marker-id="123" />
        </YandexMap>
        
        ивент не срабатывается

**Comment by oLNidfwworld** [comment]
Ты не один! Я с тобой!!
