### ISSUE TITLE
Balloon-template

### ISSUE THREAD

**Issue by NicolayKR** [PNKBizz/vue-yandex-map#446]
Подскажите пожалуйста, как правильно передавать функцию для создания balloon?

**Comment by NicolayKR** [comment]
Если быть более точным, то ваша новая версия для vue3 "vue-yandex-maps@beta", не совсем понимаю и нет ни в примерах, ни в документации как правильно передать наполнение для balloon

**Comment by PNKBizz** [comment]
[Вот здесь](https://vue-yandex-maps.github.io/new-docs/examples/custom-balloon.html) есть пример маркера с кастомным балуном. Имя слота - component.

**Comment by NicolayKR** [comment]
Спасибо большое! 
Можете также подсказать по поводу как правильно использовать данные значения для работы карты? 
![image](https://user-images.githubusercontent.com/52462172/218962201-b74a3940-5fba-40ed-880d-a7a8156126ff.png)

**Comment by PNKBizz** [comment]
[Вот тут пример](https://vue-yandex-maps.github.io/new-docs/examples/map-create.html#%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BA%D0%B0%D1%80%D1%82%D1%8B)
[Вот тут документация](https://vue-yandex-maps.github.io/new-docs/guide/map.html#%D0%B2%D1%85%D0%BE%D0%B4%D0%BD%D1%8B%D0%B5-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B)
