### ISSUE TITLE
Использование слота балуна в маркере

### ISSUE THREAD

**Issue by Ramsly** [PNKBizz/vue-yandex-map#447]
Привет! Не совсем понятен пример вот [тут](https://vue-yandex-maps.github.io/examples/#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%81%D0%BB%D0%BE%D1%82%D0%B0-%D0%B1%D0%B0%D0%BB%D1%83%D0%BD%D0%B0-%D0%B2-%D0%BC%D0%B0%D1%80%D0%BA%D0%B5%D1%80%D0%B5). Сделал все по примеру, но balloon перестал вообще открываться. Вот так [сделал я](https://codepen.io/Ramsly/pen/vYzLoxg), не могли бы подсказать, что не так, не совсем понимаю ошибку

**Comment by PNKBizz** [comment]
Привет! Какая версия Вью?

**Comment by PNKBizz** [comment]
Ищите у себя в коде. [Все работает](https://codepen.io/PNKBizz/pen/dyqXNMq)

**Comment by Ramsly** [comment]
> Привет! Какая версия Вью?

3

**Comment by Ramsly** [comment]
> Ищите у себя в коде. [Все работает](https://codepen.io/PNKBizz/pen/dyqXNMq)

IDE пишет, что не опознано название слота balloon.

YaMaps устанавливал через npm install vue-yandex-maps@next. Версия подходит под vue 3

**Comment by PNKBizz** [comment]
Для третьей версии Вью лучше взять vue-yandex-maps@beta и юзать [как тут](https://vue-yandex-maps.github.io/new-docs/examples/custom-balloon.html)
