### ISSUE TITLE
Что за ошибка 'e3 is not a function'

### ISSUE THREAD

**Issue by ideafm** [PNKBizz/vue-yandex-map#450]
"vue-yandex-maps": "^1.0.8",

`<yandex-map :settings="settings" :coords="coords" :zoom="4">
</yandex-map>`

> `e3 is not a function`

**Comment by ideafm** [comment]
Когда беру пример из examples, то получаю следующую ошибку 

`TypeError: Cannot read properties of undefined (reading 'map')`

**Comment by ideafm** [comment]
Что тут не так?
https://stackblitz.com/edit/nuxt-starter-qmnq1w?file=app.vue,components%2FTest.vue

**Comment by PNKBizz** [comment]
[Компонент не поддерживает SSR](https://vue-yandex-maps.github.io/new-docs/guide/#%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0)

**Comment by ideafm** [comment]
C <client-only> тоже не работает 

https://stackblitz.com/edit/nuxt-starter-czkcag?file=app.vue,components%2FTest.vue

**Comment by PNKBizz** [comment]
Точно. Обновил документацию. Спасибо за репорт

`import { YandexMap } from 'vue-yandex-maps'` - первая буква большая
