### ISSUE TITLE
Версия 0.12.4 (@next tag) идет как для Vue2

### ISSUE THREAD

**Issue by Vespand** [PNKBizz/vue-yandex-map#456]
В 0.12.4 версии пакета идет в dist сборка от 0.11.х

Как воспроизвести (nodejs 16.x.x):

- npm pack vue-yandex-maps@0.12.4
- Разархивировать vue-yandex-maps-0.12.4.tgz
- Зайти в package/examples/vue3
- npm install
- npm run serve
- В консоли ошибка «"Vue-yandex-maps: This version is only compatible with Vue 2.X. Please install vue-yandex-maps@next»

Также в dist можно увидеть код, которого в src пакета нет, предполагаю, что ошибочно был релизнут dist от другой версии
<img width="1113" alt="image" src="https://user-images.githubusercontent.com/36310479/231496315-6bc54c47-bd07-4f82-a84d-f632f0596a92.png">

**Comment by PNKBizz** [comment]
Сейчас поправлю. Но рекомендовал бы вам для Vue3 использовать @beta версию. Она уже вполне рабочая

**Comment by PNKBizz** [comment]
Проверил. Версия рабочая.

**Comment by Vespand** [comment]
@PNKBizz Спасибо за ответ, возьмем бетку.

Насчет 0.12.4 - билд рабочий, если склонировать репозиторий, собрать и запустить пример. Если взять отпаблишенную версию - то нет

Приведу пример с CDN - https://cdn.jsdelivr.net/npm/vue-yandex-maps@0.12.4/dist/vue-yandex-maps.esm.js - билд 0.12.4, в конце упоминается, что данный билд совместим только с Vue 2

<img width="858" alt="image" src="https://user-images.githubusercontent.com/36310479/231694832-f3f577e9-6968-4583-99e8-659e7f83af01.png">

**Comment by PNKBizz** [comment]
Точно. Вы были абсолютно правы. В новой версии настроил пацп для публикации релизов с автоматической сборкой, а здесь забыл, что нужно руками собирать... 0.12.6 рабочая
