### ISSUE TITLE
Ошибка при добавлении зоны на карту

### ISSUE THREAD

**Issue by SerikK** [PNKBizz/vue-yandex-map#459]
`{"type":"FeatureCollection","metadata":{"name":"фыв"","creator":"Yandex Map Constructor","description":"Используем эту карту"},"features":{}}`
 `window.ymaps.geoQuery(json).addToMap(this.myMap);`

Выходит ошибка

`full-4f66b8183ca86244a65c4d7cd4348b0d8bad24ab.js:1452 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at full-4f66b8183ca86244a65c4d7cd4348b0d8bad24ab.js:1452:113`

**Comment by PNKBizz** [comment]
Версия карт?
Нужен пример в песочнице для воспроизведения ошибки

**Comment by SerikK** [comment]
Сорри я применил на nuxt другую версию
