### ISSUE TITLE
Проверка грамматики в Readme =)

### ISSUE THREAD

**Issue by PNKBizz** [PNKBizz/vue-yandex-map#46]
Я тот еще англичанин, так что если бы кто-то подкорректировал мою писанину - я был бы благодарен =)

**Comment by ivangretsky** [comment]
Готов посмотреть. Где можно увидеть русский оригинал?

**Comment by ivangretsky** [comment]
Предложение в силе, если что))

**Comment by PNKBizz** [comment]
@ivangretsky было бы круто, в отношении новой документации. Все файлы с русской версией - в папке docs. Можете сделать подпапку `en` и туда добавить перевод, а я уже запилю i18n.
Thanx )
