### ISSUE TITLE
Не работает использование слота балуна в маркере Vue 3

### ISSUE THREAD

**Issue by Irina2512** [PNKBizz/vue-yandex-map#461]
Здравствуйте, пытаюсь в качестве балуна для маркера подставить компонент. На версии vue 2.6 работает нормально, а на vue 3 при клике на маркер ничего не происходит.
https://codesandbox.io/s/stoic-rgb-fbr7l8?file=/src/App.vue

**Comment by PNKBizz** [comment]
Добрый день! Для работы с Vue 3 используйте версию `beta`. Там же, в документации, найдете пример с компонентом в балуне.

**Comment by Irina2512** [comment]
Спасибо, все заработало)
