### ISSUE TITLE
Проверка адреса на попадание в зону 

### ISSUE THREAD

**Issue by HamasakiBrain** [PNKBizz/vue-yandex-map#462]
Всем привет,  не понял как через эту библиотеку добавить проверку на попадания в зону.
Вот мой код:
![изображение](https://github.com/PNKBizz/vue-yandex-map/assets/43117784/a340bc7e-d392-4451-be5a-916367f758ce)

Вот тут пример в яндекс апи  https://yandex.ru/dev/maps/jsbox/2.1/delivery_zones/
Спасибо за ответ

**Comment by HamasakiBrain** [comment]
up

**Comment by PNKBizz** [comment]
Вы можете сделать все как в документации Яндекса. `ymaps` у вас доступна глобально после загрузки карт

**Comment by HamasakiBrain** [comment]
А как поиск поиск делать? через ` searchContaining(coords).get(0)` почему то пишет нет такой функции.

Делаю так, `window.$maps.searchContaining(coords).get(0)` где `window.$maps` - инстанс мапы который возвращает после инициализации.
