### ISSUE TITLE
Как добавить ключ для suggest api?

### ISSUE THREAD

**Issue by SerikK** [PNKBizz/vue-yandex-map#469]
<img width="1409" alt="image" src="https://github.com/PNKBizz/vue-yandex-map/assets/3843487/fde96888-9297-4fbc-9568-4d4195f1e9cd">
С недавнего времени нужно задавать ключ для suggest
To use a suggest in JS API:

[Get the key for the suggest](https://yandex.com/dev/geosuggest/doc/en/quickstart) through your personal account.
Specify it when connecting the JS API in the format https://api-maps.yandex.ru/2.1/?lang=ru_RU&apikey=<your key for JS API>&suggest_api key=<your key for Suggest API>.
Как задать ключ для него?

**Comment by Timur3222** [comment]
Я вот так ключ добавляю, но все равно эта ошибка выходит.
    mapSettings() {
      return {
        apiKey:
          this.$store.getters['app/yandexMapKey'] +
          '&' +
          `suggest_apikey=${this.suggestApiKey}`,
      }
    },

**Comment by illi-homz** [comment]
```
Я вот так ключ добавляю, но все равно эта ошибка выходит.
mapSettings() {
  return {
    apiKey:
      this.$store.getters['app/yandexMapKey'] +
      '&' +
      `suggest_apikey=${this.suggestApiKey}`,
  }
},
``` 

мне помогло, спасибо

**Comment by yusforgithub** [comment]
Помогло, спасибо.
