### ISSUE TITLE
Как добавить обработчик события для элемента в detailedControls?

### ISSUE THREAD

**Issue by hetsketch** [PNKBizz/vue-yandex-map#48]
Вот конфиг компонента. 
```
<yandex-map
                :coords="[55.7522200, 37.6155600]"
                zoom="9"
                :controls="['zoomControl']"
                :detailedControls="{ 'searchControl': { options: { provider: 'yandex#search' } } }"
                style="width: 100%;height:500px; margin-top: 30px; margin-bottom: 0.75rem"
                @map-was-initialized="customizeMap"
              >
```
Я пытаюсь добавить обработчик после инициализации карты в методе customizeMap:
```
customizeMap(map) { 
    map.controls.get('searchControl').events.add('resultselect', function(e) {
       //instructions
    }
}
```
Но ничего не получается из-за того, что `get('searchControl')` возвращает `undefined`. Хотя `get('zoomControl')` работает. Есть идеи, как решить проблему?

**Comment by PNKBizz** [comment]
Привет!
`controls` is array of enabled map controls. **All another will be disabled**
Укажите все контролы в detailedControls. 
Если это не решит проблему - пишите, будем разбираться.

**Comment by hetsketch** [comment]
Дак у меня все контролы, которые нужны есть и на карте отобращаются. Просто я не могу получить конкретно инстанс searchControl'a.

**Comment by hetsketch** [comment]
Вроде бы починил. Глянешь, как появится время? https://github.com/PNKBizz/vue-yandex-map/pull/49

**Comment by PNKBizz** [comment]
Привет! Спасибо за PR! Вмержил, версия 0.7.8. Извини за долгое ожидание. Загруз на работе ((

**Comment by hetsketch** [comment]
@PNKBizz thanks!
