### ISSUE TITLE
Отключение скролла, доп функционал

### ISSUE THREAD

**Issue by IsakovIgor** [PNKBizz/vue-yandex-map#5]
Очень хотелось бы видеть доп функционал, в особенности такие вещи как отключение скролла -  behaviors.disable('scrollZoom')
Имхл, без нее на десктопах/ноутах прокрутка страницы с картой превращается в ад.

**Comment by PNKBizz** [comment]
Дополню функционал в ближайшее время! )

**Comment by PNKBizz** [comment]
Реализовано в версии 0.3.0
