### ISSUE TITLE
Как добавить в балун метки кнопки, привязанные к методам vue?

### ISSUE THREAD

**Issue by shrue348** [PNKBizz/vue-yandex-map#50]

**Comment by PNKBizz** [comment]
[Вы про это?](https://github.com/PNKBizz/vue-yandex-map/issues/33)

**Comment by shrue348** [comment]
да) костыль конечно но думаю сойдет
в гуглокартах например есть <gmap-info-window> и разметка делается прямо в нем

**Comment by PNKBizz** [comment]
Да, будет побольше времени - добавлю нормальный вариант

**Comment by shrue348** [comment]
может стоит костыль в описание добавить?
потому что я не нашел ту тему т к она закрыта, а народ похоже будет интересоваться

**Comment by PNKBizz** [comment]
@shrue348 Да я думаю я в ближайшее время постараюсь от этого костыля избавится в пользу нормального решения.

**Comment by AlexeyKot** [comment]
@PNKBizz не появилось ли способа поэстетичнее? :)
тоже столкнулся с тем же самым.
