### ISSUE TITLE
Проблема с Nuxt.js

### ISSUE THREAD

**Issue by mrserzhan** [PNKBizz/vue-yandex-map#53]
При юзании с nuxt.js возникает проблема типа "не могу найти родительский элемент". Проблема в том что рендеринг делается на стороне сервера с одним рандомным айди а на стороне клиента этот айди еще раз присваивается рандомно, и он же передается в яндекс карты, а тот в свой черед не может найти этот элемент. Решил тем что делаю ре-рендеринг этого элемента (карты) с родительского компонента на стороне клиента.

**Comment by PNKBizz** [comment]
Спасибо! Как только разверну освою Nuxt и SSR - сразу же разберусь в этой проблеме. Это будет быстрее, чем кажется из построения предложения =)

**Comment by jedisct1** [comment]
Hi!

Looks like I'm facing the same issue with Nuxt. Is there a workaround for this?

**Comment by Elgorm** [comment]
заключите код карты в <no-ssr>

**Comment by PNKBizz** [comment]
https://github.com/PNKBizz/vue-yandex-map#nuxt-module

**Comment by ElioLooiz** [comment]
Может быть кому-то сохраню время.
При использовании с Nuxt 3 (nuxt3@3.0.0-rc.3-27584539.9d28c0a) компонент карты не может примаунтиться при перезагрузке страницы (особенно в случе перехода с одного маршрута на другой и обратно).
С соотв. ошибкой в консоль `Cannot read properties of null (reading 'offsetWidth')`

В моем случае помогл отключение базовой анимации перехода между страницами в nuxt 3
`definePageMeta({
  pageTransition: false
})`
После отключения, при переходах между страницами, в хуке mounted возвращаются корректные размеры для корневого элемента.
