### ISSUE TITLE
How to change the language?

### ISSUE THREAD

**Issue by jedisct1** [PNKBizz/vue-yandex-map#54]
Is there a way to change the language?

I tried to add a `mapLink` property to the component, but it keeps loading the default URL in Russian.

**Comment by jedisct1** [comment]
Looks like this works with the current code in Git, but not with the version on npm which is getting old.

Closing, and hoping for a new release on npm soon!

Thanks!

**Comment by PNKBizz** [comment]
@jedisct1 version on npm updated. Sorry for delay =(
