### ISSUE TITLE
Как прокидывать настройки для controls?

### ISSUE THREAD

**Issue by dimensi** [PNKBizz/vue-yandex-map#55]
Вижу props который позволяет через массив задать нужные controls, а как указать дополнительные опции?

**Comment by gamexxx** [comment]
@nuykon пожалуйста, покажи Ваш код.

**Comment by gamexxx** [comment]
@dimensi что Вы подразумеваете под дополнительными опциями? Не могли бы Вы прислать пример из офф. документации?

**Comment by nuykon** [comment]
@gamexxx Извиняюсь, проблема была в кешировании... Все работает.
А @dimensi думаю имеет ввиду - https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/control.SearchControl-docpage/#param-parameters.options.float
мне тоже интересно, как например контрол разместить справа?

**Comment by PNKBizz** [comment]
@nuykon для этого есть аттрибут `detailed-controls`
Прошу прощения за очень долгий ответ ))
