### ISSUE TITLE
ошибка  Uncaught TypeError: Cannot read property 'toLowerCase' of undefined     

### ISSUE THREAD

**Issue by ohot2015** [PNKBizz/vue-yandex-map#56]
inception-1519300852896.js:5 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at Object.<anonymous> (VM3109 inception-1519300852896.js:5)
    at Object.<anonymous> (VM3109 inception-1519300852896.js:1)
    at VM3109 inception-1519300852896.js:1
    at w (VM3109 inception-1519300852896.js:1)
    at x (VM3109 inception-1519300852896.js:1)
    at w (VM3109 inception-1519300852896.js:1)
    at E (VM3109 inception-1519300852896.js:1)
    at Array.k (VM3109 inception-1519300852896.js:1)
    at r (VM3109 inception-1519300852896.js:1)
    at s (VM3109 inception-1519300852896.js:1)

`ym.modules.define("system.supports.css", [], function(e) {
        function t(e) {
            return "undefined" == typeof d[e] ? d[e] = n(e) : d[e]
        }
        function n(e) {
            return r(e) || r(h + a(e)) || r(p.cssPrefix + a(e))
        }
        function r(e) {
            return "undefined" != typeof i().style[e] ? e : null
        }
        function i() {
            return u || (u = document.createElement("div"))
        }
        function a(e) {
            return e ? e.substr(0, 1).toUpperCase() + e.substr(1) : e
        }
        function o(e) {
            var n = t(e);
            return n && n != e && (n = "-" + h + "-" + e),
            n
        }
        function s(e) {
            return l[e] && t("transitionProperty") ? o(l[e]) : null
        }
        var u, l = {
            transform: "transform",
            opacity: "opacity",
            transitionTimingFunction: "transition-timing-function",
            userSelect: "user-select",
            height: "height"
        }, c = {}, d = {}, p = ym.env.browser, h = p.cssPrefix.toLowerCase();
        e({
            checkProperty: t,
            checkTransitionProperty: function(e) {
                return "undefined" == typeof c[e] ? c[e] = s(e) : c[e]
            },
            checkTransitionAvailability: s
        })
    }),`

http://joxi.ru/a2XnqyoUy83y0r
![1b961408a0](https://user-images.githubusercontent.com/22836177/38559880-deaf605e-3cdc-11e8-943c-40df58053a25.jpg)

**Comment by PNKBizz** [comment]
Привет! А можно поподробнее? Как воспроизвести?

**Comment by ohot2015** [comment]
` <section class="wrap-map">
            <div id="yamaps">
                <yandex-map
                  :coords="[50, 40]"
                  zoom="16"
                  style="width: 100%; height: 100%;"
                  :placemarks="placemarks"
                  :controls="['zoomControl']"
                  :behaviors="['drag', 'dblClickZoom', 'rightMouseButtonMagnifier', 'multiTouch']"
                >
                </yandex-map>
            <div class="wave"></div>
            </div>
        </section>`

`import { yandexMap, ymapMarker } from 'vue-yandex-maps'

export default {
    name: 'AppLongrid',
    data () {
        return {
            placemarks: [{
                coords: [50,  40],
                properties:
                    {}, // define properties here
                    options: {
                        iconLayout: 'default#image',
                        iconImageHref: 'src/assets/img/logo.png',
                        iconImageSize: [30, 42],
                        iconImageOffset: [-5, -38]
                    }, // define options here
                    balloonTemplate: '<div>"Your custom template"</div>',
                    callbacks: { click: function() {} }
            }]
        }
    },
    components: { yandexMap, ymapMarker },
}
`

![1523372608571](https://user-images.githubusercontent.com/22836177/38565280-9237eb80-3ce9-11e8-8fcb-2eabb269c9fe.jpg)
![1523372540700](https://user-images.githubusercontent.com/22836177/38565282-925a0684-3ce9-11e8-8ac1-9390aef32ac2.jpg)
![1523372519978](https://user-images.githubusercontent.com/22836177/38565283-9284006a-3ce9-11e8-8d7a-2fe330c2f536.jpg)

**Comment by PNKBizz** [comment]
Спасибо! Буду разбираться

**Comment by PNKBizz** [comment]
Не смог воспороизвести
