### ISSUE TITLE
Нерабочий код в документации

### ISSUE THREAD

**Issue by bogdand92** [PNKBizz/vue-yandex-map#57]
`<ymap-marker 
      marker-type="placemark"
      :coords="[54.7, 39.7]"
      hint-content="Hint content 1"
      :balloon="{header: 'header', body: 'body', footer: 'footer'}"
      :icon="{color: 'green', glyph: 'cinema'}"
      cluster-name="1"
    ></ymap-marker>`

Судя по исходному коду этому компоненту нужен обязательный пропс marker-id. Но не в доке на Вашей странице, ни в комментах исходного кода я не обнаружил что это за поле и зачем оно нужно, более того приведенный выше код не рабочий, по причине отсутсвия этого пропса

**Comment by gamexxx** [comment]
@bogdand92 Добрый день! Этот пропс описывается в документации:
> You may define placemarks on your map by using <ymap-marker> tag or set an array of objects with placemark options through <yandex-map> attribute placemarks (interface description). You also can use both methods together.
You must define markerId for every marker on your map in any case fo setting (through map attribute placemarks or using ymap-marker components).

**Comment by PNKBizz** [comment]
@bogdand92 привет! Спасибо за замечание, код в документации поправлю. А поле нужно для создания кластеров.

**Comment by PNKBizz** [comment]
@gamexxx Верное замечание )
