### ISSUE TITLE
SSR

### ISSUE THREAD

**Issue by Caspanch** [PNKBizz/vue-yandex-map#59]
При использовании SSR, карты не будут работать, если не сделать следующее:
```
<yandex-map
    v-if="showMap"
    class="ymap"
    :coords="[54.62896654088406, 39.731893822753904]"
></yandex-map>
```
И в mounted:
`mounted() { this.showMap = true }`

**Comment by PNKBizz** [comment]
@Caspanch Три месяца работал на проекте, где использовали нативный SSR и эти карты. Проблемы не было. Возможно что-то у вас настроено не правильно.

**Comment by yusupprog** [comment]
А если я использую не nuxt, а vue-server renderer, как можно подключить? Сейчас выдает `undefined token export`

**Comment by yusupprog** [comment]
Решилл, спасибо

**Comment by KirillRomanuk** [comment]
> Решилл, спасибо

Буду очень признателен, если поделитесь решением)

**Comment by yusupprog** [comment]
```
if(process.browser){
        YmapPlugin = require('vue-yandex-maps/dist/vue-yandex-maps')
        Ymap = YmapPlugin.yandexMap;
}
```

**Comment by evgajukov** [comment]
> ```
> let YmapPlugin;
> let Ymap;
> 
> if(process.browser){
>      YmapPlugin = require('vue-yandex-maps/dist/vue-yandex-maps')
>      Ymap = YmapPlugin.yandexMap;
> }
> ```

А можно поподробнее как после Ymap использовать?

**Comment by nikitakuhta** [comment]
У меня аналогичная проблема с Nuxt SSR, как у автора issue. Если не запретить рисовать компонент yandex-map на сервере, то после загрузки вылетает ошибка:
`Uncaught TypeError: Cannot read property 'offsetWidth' of null`
Карта при этом на клиенте уже не рисуется.

Если закрыть компонент в <client-only>, или сделать хак с mounted, чтобы компонент рисовался только на фронте, то карта работает. Какие настройки искать - не понял. 
Nuxt.js v2.12.2, vue-yandex-maps v0.10.7.

<img width="886" alt="Снимок экрана 2020-04-21 в 22 12 51" src="https://user-images.githubusercontent.com/908701/79904387-408b2400-841d-11ea-90aa-da0342f1ea5b.png">

**Comment by KirillOlegovichH** [comment]
```html
<template>
  <q-no-ssr> <!-- Важно -->
        <YaMap />
  </q-no-ssr>
</template>

<script>
   components: {
    YaMap: defineAsyncComponent(() =>
      import('components/modules/YaMap.vue') /* Важно */
    )
  },
</script>
```
