### ISSUE TITLE
Ререндеринг карты

### ISSUE THREAD

**Issue by mixalleach** [PNKBizz/vue-yandex-map#6]
Привет, не подскажешь, есть ли возможность изменять положения карты и маркера на ней в зависимости от свойства coords. Например, сначала были одни значения для координат, затем после некоторых действий на странице карта и маркер на нее переместились в другую координату

**Comment by PNKBizz** [comment]
Отличное предложение. Конечно все должно быть реактивным. На днях выкачу релиз с этой фичей. Спасибо!

**Comment by mixalleach** [comment]
@PNKBizz Пока ждал твой ответ, уже сам твой компонент подпилил, и реализовал это. 
хочешь могу сделать пул реквест и доработкой?

**Comment by PNKBizz** [comment]
Конечно делай PR =)

**Comment by PNKBizz** [comment]
В общем на данный момент можно изменять координаты центра карты. Работа над маркерами в процессе.

**Comment by zhiga90** [comment]
ну и как провиджение с работой над маркерами?

**Comment by PNKBizz** [comment]
@zhiga90 есть решение, нужна реализация. Думаю в ближайшее время выкачу

**Comment by web-west** [comment]
Привет. Вижу так и нет реализации обновления маркеров. Планируете обновить?

**Comment by PNKBizz** [comment]
@web-west Да, обязательно сделаю. Думаю, что на этой неделе будет релиз. Времени не хватает совершенно =)

**Comment by PNKBizz** [comment]
Добавлена перерисовка карты, если изменилась ссылка на массив маркеров при передаче их через атрибут placemarks или при изменении координат маркера при передаче маркеров компонентами
