### ISSUE TITLE
Карта смещается в координаты инициализации, если на странице происходит рендер DOM-элемента

### ISSUE THREAD

**Issue by ezhkov** [PNKBizz/vue-yandex-map#60]
Есть карта, которая инициализируется на любых координатах. 
Есть несколько маркеров.

После инициализации центр карты выставляется таким образом, чтобы маркеры попали в область карты.

Если после этого в интерфейсе что-то отрендерить средствами Vue, то центр карты улетает в начальные координаты

Накидал пример. Нужно нажать кнопку Show

https://codesandbox.io/s/6xp551108w

**Comment by PNKBizz** [comment]
Да, при перерисовке страницы карта рисуется заново по указанным параметрам. В принципе можно добавить аттрибут для того, чтоб карта изначально рисовалась с учетом маркеров. Но пока можно делать вот так:
https://codesandbox.io/s/vvzovv1rx3
