### ISSUE TITLE
Плавное перемещение карты

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#63]
Привет!
При изменении координат центра, перемещение картинки получается рывками, что не поймёшь, откуда ты пришёл на это место. 
Как скоро будет плавность в таких делах?

**Comment by PNKBizz** [comment]
@araimbekoff Привет! Я думаю здесь вопрос скорее к Я.Картам. Не смотрел в сторону плавного перемещения. Если подскажете какое свойство смотреть, добавлю в плагин.

**Comment by araimbekoff** [comment]
Есть одна реализация:
http://jsfiddle.net/vdann/YDg62/14/ (надо нажимать на список городов внизу карты)

Было бы супер такую вещи иметь искаропки.

**Comment by PNKBizz** [comment]
@araimbekoff добавил в версии 0.7.12. Потестируйте, если не сложно

**Comment by araimbekoff** [comment]
Супер!
Сегодня должен дойти. Обязательно отпишусь

**Comment by araimbekoff** [comment]
Нет. Не работает. Может быть мы говорим о разном?
Я рисую карту. Потом, нажимаю произвольное место на карте, получаю координаты и выставляю его центром. Тогда, перемещение получается рывками, а хочется плавно, как в примере выше на два коммента.

**Comment by PNKBizz** [comment]
@araimbekoff а можешь в песочнице воспроизвести свой кейс?

**Comment by araimbekoff** [comment]
Да. Скину завтра

**Comment by araimbekoff** [comment]
https://codepen.io/araimbekoff/pen/VdNQrL

Вот же блин. Почему то в примере плавное перемещение работает. 
А в проекте нет (((

**Comment by PNKBizz** [comment]
Вот я тоже удивился ) потому что там стоит вотчер на атрибут центра карты и раньше он менял позицию через setCenter, а теперь через panTo. И тут не может быть каких-то косяков, по идее. Возможно кэш нужно почистить.

**Comment by araimbekoff** [comment]
Точно!
У меня на хроме стояло "disable cache".
Оказывается не работает оно. стрл+ф5 помогло!

Спасибо!
