### ISSUE TITLE
Перемещение карты!

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#64]
Привет!
Кажется, с последней обновой что-то пошло не так?

Пытаюсь развернуть карту, но драгом (на телефоне) вообще не реагирует карта. Как будто картинка и она просто застыла.

**Comment by araimbekoff** [comment]
Пардоньте!
Не доглядел и оставил behaviors пустым.
Можно закрыть

**Comment by PNKBizz** [comment]
@araimbekoff а что насчет перемещения-то? работает как надо? плавно?

**Comment by araimbekoff** [comment]
Плавное перемещение описывал в соседней задача. Если коротко, то я меняю карте координаты центра. И вот при смене нет плавности нет
