### ISSUE TITLE
Кастомная метка и перезагрузка карты

### ISSUE THREAD

**Issue by DmitriyWhite** [PNKBizz/vue-yandex-map#65]
Привет. Появилось две сложности по работе с плагином. 
Первое, это создание собственных меток, атрибуты, которые я использовал при написании на JS не срабатывают здесь. Пример кода, который использовал для создания кастомных меток
```

$.each(items, function(index, item) {
  var MyIconContentLayout = ymaps.templateLayoutFactory.createClass(
    '<div class="circle-marker">' +
      '<div class="circle-marker__point">' +
      '<img src="$[properties.iconContent]" alt="">' +
      "</div>" +
      '<div class="circle-marker__content">$[properties.iconCaption]</div>' +
      "</div>"
  );

  if (group.name === item.type || group.name === "all") {
    var placemark = new ymaps.Placemark(
      item.center,
      {
        balloonContent: item.name,
        iconCaption: item.name,
        iconContent: item.icon
      },
      {
        iconLayout: "default#imageWithContent",
        iconImageHref: "img/map/circle-marker.svg",
        iconImageSize: [40, 40],
        iconImageOffset: [-20, -20],
        iconContentOffset: [0, 0],
        iconContentLayout: MyIconContentLayout
      }
    );
    clusterer.add(placemark);
  }
});

```
Проблема лежит в параметре `iconContentLayout`, браузер не может отрендерить имеющейся контент (точнее он не появляется вовсе). Вопрос собственно, как использовать данный параметр, или как подключить данный HTML?

Второй вопрос заключается в перезагрузке карты. При возникновении события, связанного с метками, карта полностью обновляется. Есть возможность управлять именно метками, не затрагивая карту?

Пример, данной работы
https://codepen.io/dmitriywhite/pen/vrMLeP

**Comment by PNKBizz** [comment]
Привет!
По иконкам: кастомные картинки можно сделать сейчас при выборе `layout: 'default#image'`. Соответственно ты можешь задавать `imageHref`, `imageSize`, `imageOffset`. Свой темплейт задавать, к сожалению нельзя. Но если тебе нужен этот функционал - можешь сделать PR и я с удовольствием расширю плагин )
Пример: https://codepen.io/PNKBizz/pen/ERJLVX
По перезагрузке карты: на данный момент карта должна перезагружаться каждый раз, при изменении маркеров.

**Comment by DmitriyWhite** [comment]
Благодарю за ответ) 
Если опыта хватит, то функционал попробую сделать.

**Comment by DmitriyWhite** [comment]
В принципе удалось добавить сверстанные метки)
https://codepen.io/dmitriywhite/pen/vrMLeP

**Comment by PNKBizz** [comment]
@DmitriyWhite О! Ну тогда вообще отлично )
