### ISSUE TITLE
Cluster & Placemark

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#67]
для компоненты Placemark я описал balloon.
Все работает отлично!
Но, я бы хотел следующее:

При нажатии на кластер, мне необходимо отобразить баллуны маркеров, если они находятся крайне близко друг другу.
Если же нажимаю на отдельно стоящий маркер, то вызвать какую-нибудь функцию.

**Comment by PNKBizz** [comment]
С ходу тебе не скажу решение. Если терпит, попозже попоробую пример запилить как это сделать.

**Comment by Antontsyk** [comment]
Каким образом можно установить иконку типа 'islands#darkBlueCircleDotIcon' из стандартной документации ? ( https://tech.yandex.ru/maps/doc/jsapi/2.1/ref/reference/option.presetStorage-docpage/ )

**Comment by AlexKu777** [comment]
```
<ymap-marker
             marker-id="8"
             marker-type="placemark"
            :coords="coords"
            :icon="{layout: 'islands#darkBlueCircleDotIcon',iconContent:'8'}"
   ></ymap-marker>
```
