### ISSUE TITLE
Как получить адрес по клику на карте?

### ISSUE THREAD

**Issue by Mhiggster** [PNKBizz/vue-yandex-map#70]
При клике на карту получить адрес, lng и lat. Вот пример https://tech.yandex.ru/maps/geocoder/

**Comment by sskolobov** [comment]
Как, всё таки, это сделать?

**Comment by Mhiggster** [comment]
В колбэке события @map-was-initialized первым аргументом передается контекст карты.
А дальше по нативной схеме yandex api работаем с этим контекстом, вот пример https://tech.yandex.ru/maps/jsbox/2.1/event_reverse_geocode/
Конечно же, не лучший способ, но другого я не нашел.

**Comment by PNKBizz** [comment]
@Mhiggster почему же не лучший? Для этого и передается контекст карты. Если пытаться реализовать в компоненте все возможности Я.Карт... ну это невозможно ) Поэтому есть базовые вещи и карта, с которой можно делать все, что угодно )

**Comment by Mhiggster** [comment]
Ок) Теперь буду знать)

**Comment by Flashantik** [comment]
> Ок) Теперь буду знать)
Как вы обратились через инстанс карты к методам geocode ?? В упор их не вижу..
