### ISSUE TITLE
Не реализован LoadingObjectManager и RemoteObjectManager

### ISSUE THREAD

**Issue by TheAthlete** [PNKBizz/vue-yandex-map#72]
Здравстуйте!
Планируется ли реализация LoadingObjectManager и RemoteObjectManager?
https://tech.yandex.ru/maps/doc/jsapi/2.1/dg/concepts/many-objects-docpage/

**Comment by Elgorm** [comment]
В событии map-was-initialized подключал вручную RemoteObjectManager
```
initHandler(map) {
      const objectManager = new ymaps.RemoteObjectManager(
        'items/map?bbox=%b',
        {
          clusterHasBalloon: false,
          geoObjectOpenBalloonOnClick: false
        }
      )
      map.geoObjects.add(objectManager)
    }
```
Думаю LoadingObjectManager можно также подключить.
