### ISSUE TITLE
Не получается развернуть карту на всю страницу 

### ISSUE THREAD

**Issue by TheAthlete** [PNKBizz/vue-yandex-map#73]
Здравствуйте!
Пытаюсь реализовать пример с ObjectManager, чтобы он при открытии страницы был на всю страницу. Если указывать 
`style="width: 100%; height: 100%"`, 
карта вообще не показывается
если указывать    
 `style="width: 600px; height: 600px;"`
то карта показывается, но только в рамках этих параметров.

При этом, если реализовать пример с ObjectManager без Vue.js, на чистом JS, то карта раскрывается на всю страницу.

 Реализова пример чистого ObjectManager с помощью JS + jQuery и с помощью Vue.js + компонент vue-yandex-map: https://github.com/TheAthlete/object_manager_pure_vs_vue

Пример чистого ObjectManager - скрипт на Perl + Mojolicious::Lite -  	object_manager_pure.pl

Запускать:
```
$ # предварительно установить Mojolicious
$ cpanm Mojolicious
$ morbo -l http://*:8008 object_manager_pure.pl
```

Пример варианта  с помощью Vue.js + компонент vue-yandex-map лежит в папке object_manager_vue. В компоненте ObjectManagerVue.vue подключается карта и выводится. Если убрать стиль `style="width: 600px; height: 600px;"`, то ничего не выводится.

Как сделать аналогичный пример, как в чистом ObjectManager + JS/jQuery

**Comment by TheAthlete** [comment]
И еще вопрос - правильно я понимаю, чтобы реализовать добавление точек на карту с помощью ObjectManager, нужно данные передавать в аргумент placemarks тега <yandex-map> ?

**Comment by PNKBizz** [comment]
@TheAthlete `objectManager` включается при указании аттрибута `use-object-manager` для любого способа определения маркеров. Если у вас карта разворачивается при `style="width: 600px; height: 600px;"` и не показывается при `style="width: 100%; height: 100%"` - значит проблема в вашем CSS. Смотрите размеры контейнера, в который помещаете компонент.
