### ISSUE TITLE
Как обращаться к созданному объекту карты?

### ISSUE THREAD

**Issue by sebastian-negoro** [PNKBizz/vue-yandex-map#75]
Здравствуйте!

К примеру, мне нужно реализовать поиск по карте с помощью инструмента geocoder. Документация API Яндекс.Карт предлагает обращаться к объекту ymaps:

`var myGeocoder = ymaps.geocode("Москва");`

А как обратиться к подобным методам созданной карты через ваш плагин? Я во VueJS новичок, не могу разобраться. Спасибо.

**Comment by PNKBizz** [comment]
Привет! 
После инициализации карта кидает событие `map-was-initialized` в котором payload - это инстанс карты. Соответственно `ymaps` к этому времени должен быть у вас доступен как глобальная переменная.

**Comment by sebastian-negoro** [comment]
Ну вот я инициализирую карту по коду из вашей же документации, отображается она корректно, но вот что пишет консоль 
![image](https://user-images.githubusercontent.com/9335251/44205986-4d944200-a169-11e8-9a68-3f4c60eb8a92.png)

`<div id="map">
            <yandex-map 
              :coords="[53.22572219, 50.21399439]"
              zoom="11"
              style="width: 960px; height: 600px;"
              :cluster-options="{
                1: {clusterDisableClickZoom: true}
              }"
              :behaviors="['ruler']"
              :controls="['trafficControl']"
              map-type="map"
              @map-was-initialized="initHandler"
            ></yandex-map>
          </div>`

**Comment by PNKBizz** [comment]
В методах. Почитайте документацию по Вью. Это важно.

**Comment by sebastian-negoro** [comment]
Спасибо!
