### ISSUE TITLE
Not full instance on @map-was-initialized

### ISSUE THREAD

**Issue by khudia** [PNKBizz/vue-yandex-map#77]
As a simple example if i call method of recieved instance of map
mapInstance.geolocation  so there is undefined

Ну а если по русски то какой то не полный объект карты передается что ли и многие методы не работают. Хотя бы просто определение местоположения

**Comment by PNKBizz** [comment]
@khudia метод `geolocation` нужно вызывать не у инстанса карты, а у глобальной переменной `ymaps`

**Comment by khudia** [comment]
Спасибо. Не знал что есть глобальная переменная.
