### ISSUE TITLE
Возможно ошибка в работе компонента

### ISSUE THREAD

**Issue by skytmn** [PNKBizz/vue-yandex-map#78]
Добрый день!
В вашем же примере https://codepen.io/PNKBizz/pen/WMRwyM если включить отладку браузера Хром и нажать на балун, то откроется хинт, но как-то в сторонке, если в нем попытаться вкладки по переключить то в консоли появляются ошибки. Тоже самое если после клика по балуну менять масштаб или перемещать карту то тоже ошибки:
`Uncaught TypeError: Cannot read property 'setPosition' of null at h.applyGeometryToView (api-maps.yandex.ru/2.1.68/combine.js?callback_prefix=__jsonp_ymaps_combine&mode=release&load=_R)$;M1a:j1M7Y735v7f1D;5;4070J1F1B:4:1754) at h.onPaneClientPixelsChange (https://api-maps.yandex.ru/2.1.68/combine.js?callback_prefix=__jsonp_ymaps_combine&mode=release&load=:Z3p5h,O2T;R;S;P;Y,N;V4T2V2X16!I4u8k2R0@;U8c8b54707776728d8e712@2;4y5!6F;T0j6o!5!30RT-d:Q2u3x;(/vue/@3@42w2y5w5t.B.C2:0E:z;W2@7@8@6qk@;@@@5qv@,qh@$462-@92z@qql@:2Jqt2j3bqgqm2)3d2Zqu1j2.4m:I;i2O4n_4_C)__D_!K4;*_A_E_())3:_F3.(C_G)(),$93_$7$5$83!7T3901$u$Y$6$X$1$R3-$t$w3;3j3q$V$0$M383$$y$U$L:296:3550) at n._onClientPixelsChange (https://api-maps.yandex.ru/2.1.68/combine.js?callback_prefix=__jsonp_ymaps_combine&mode=release&load=:Z3p5h,O2T;R;S;P;Y,N;V4T2V2X16!I4u8k2R0@;U8c8b54707776728d8e712@2;4y5!6F;T0j6o!5!30RT-d:Q2u3x;(/vue/@3@42w2y5w5t.B.C2:0E:z;W2@7@8@6qk@;@@@5qv@,qh@$462-@92z@qql@:2Jqt2j3bqgqm2)3d2Zqu1j2.4m:I;i2O4n_4_C)__D_!K4;*_A_E_())3:_F3.(C_G)(),$93_$7$5$83!7T3901$u$Y$6$X$1$R3-$t$w3;3j3q$V$0$M383$$y$U$L:300:849) at s._callListeners (api-maps.yandex.ru/2.1.68/combine.js?callback_prefix=__jsonp_ymaps_combine&mode=release&load=_).46b694R*u40*A8,8;.$4(4)5Y42!Ov676Z4Y6Wx3CC6z6tE$i6Y8K4,8@3H_y_x3F5P0q7-7@3o!E*w3w3t!p2k$j$Q$@!o!s!U!F6i7r3E5W2Q!K8(8O8L6v6J,q-s6K6M!n6S7k3r6I!D7U,j,;,J,i-y6L7V,,,z,Q.a0b1113*c18*d1$1_1(1,1;1q9l1I8w8x2a0t2S2U2W2Y862126898$282$2!2(2,2i8!3c3s3u3G0C0N0W9y9B9A9D9E9F9X929-9_9*9(9)9,979899969495909@9i9z3P8i8z8Q3O3U9e3R0G30320Y030-4a3J3I(K(L$-$.$!3Z4b$*4e4f4g4h4k4l0*4s$q$z4p4x4A-k4D(M_b0)-W-X-0-1-24F-54G4K4L4O4P-_-!-.-4X0:0;410i4j4z4Z-;-Q-,_c)T)V)U)W4q):9m9n9o5E5a5y5f5p5s5O5X9p_d1d0k7R1f5-5_5(5)5,5:1v5@1h1P1K6d.!..)6m6w6A6B!g!h617N6-8p0e15!e-77J1Y!H8rb8s-32N2L:e8u1!!M3X8E8N3K8y3D0x,t5K1Q2e8A8B0o2_85248W80878X888G(S8T0h8U8V8-;)!8!zpsn*m:f,P82,U8.8*7SBD-G4E!69x2tV!b9T9M9L9N9K9O!aWX9UY:m:n9Y9H9S6!9P7m9$:l:o*0*49W9.*1*59V*29G9391*89Q8q3V;m6u60689;9qf9d5R6O5M5L8J9a9b8I9c8Zg8j8H7h.JOKLNPM3133!x052C$)$,$$3Q2G$_$(4r,C4d7b6N.Z2P$;$:(X0n2v2x79-h0m08-l$J6P3a4t)X)6_w_f_e_s_v4M-Y-V4S.I.Q,Z:a7g7j_,(N*k.W4:4N-66_0w---9-$!L9f(O(7(P(R(T(U(Y(0(1(2(3(4(5(6(80B.b.g.c3m(,(z-()B)A:b-J-)49:66:2970)` причем свойства `setPosition ` ни где нет. Просто я попытался по вашему примеру сделать на своем проекте вывод объектов с использованием вашего компонента и в моем случае такие же ошибки появились..

**Comment by PNKBizz** [comment]
Привет! Спасибо, посмотрю!

вт, 21 авг. 2018 г., 16:47 skytmn <notifications@github.com>:

**Comment by PNKBizz** [comment]
@skytmn Пофиксил в версии 0.7.15
И внес изменения в песочницу (добавил `layout` и его же добавил как дефолтный, если не задан)
Спасибо еще раз!
