### ISSUE TITLE
request new Feature

### ISSUE THREAD

**Issue by KamilOcean** [PNKBizz/vue-yandex-map#8]
Привет, очень нравится твой компонент. Может сделаем чтобы можно было как-нибудь строку скопировать из конструктора Яндекс карт. У них же есть такой сервис. Было бы круто добавить эту фичу, чтобы легко было потянуть карты с настройками из конструктора, типа сюда, да:
yandexMapScript.setAttribute('src', 'https://api-maps.yandex.ru/2.1/?lang=ru_RU');

И кстати я не нашел настройку scroll. 

Если дашь добро, то я могу реализовать это. Форкнусь от тебя.
Спасибо=)

**Comment by PNKBizz** [comment]
@KamilOcean Привет! Я буду только рад любым пулл-реквестам ) Так что, вэлкам! )

**Comment by KamilOcean** [comment]
Спасибо, прям сегодня после работы посмотрю)

**Comment by PNKBizz** [comment]
Закрыто за истечением срока давности
