### ISSUE TITLE
Use geocoder with vue/nuxt

### ISSUE THREAD

**Issue by siberiadev** [PNKBizz/vue-yandex-map#81]
Здравствуйте.
Подскажите, как можно использовать функционал Yandex Geocoder в проекте на Vue/Nuxt? из API не совсем понятно как слать запросы.
Пробовал так:
```
methods: {
			getGeodata(){
				axios.get('https://geocode-maps.yandex.ru/1.x/?format=json&geocode=Тверская+6').then(resp=>{
					this.subResult = resp;
					console.log(resp);
				}).catch(e=>{this.error = e})
			}
		},
```
По началу работало, а спустя примерно 5 запросов получил бан от Yandex Maps на локальном компе.

**Comment by Flashantik** [comment]
> Привет. Геокодер - отдельный инструмент, не имеющий никакого отношения к компоненту. Во всяком случае пока.

Получается нужно отдельно импортировать geocoder и т.д. ? Как в таком случае использовать Geocode и прочее?

**Comment by Nikitoring** [comment]
@Flashantik получилось все таки использовать геокодер? Если да, то как?

**Comment by PNKBizz** [comment]
@Nikitoring после инициализации компонента карты становится глобально доступна переменная ymaps со всеми вытекающими. В том числе и с геокодером

**Comment by AsuRaHan** [comment]
так как всетаки использовать геокодер то. нет его у меня
var geocoder = ymaps.geocoder("Москва");
       console.log(geocoder);

**Comment by PNKBizz** [comment]
https://vue-yandex-maps.github.io/en/guide/#ymaps-loader

**Comment by 4KDA** [comment]
How use? Add example please

**Comment by Nikitoring** [comment]
@NormanRDD нет. Пример предоставить не могу к сожалению. На сколько помню, можно получить доступ в mounted хуке

**Comment by NormanRDD** [comment]
> Reference in new

Я около месяца пытаюсь подключить хотябы карту, для nuxt. Всё вроде сделал, создал js файл, в плагине. Импортировал его в nuxt-config, предварительно установил через npm. Импортирую локально в компоненте, прописал ключи, но всё ровно ничего...Не могу пройти дальше ошибки maximum call stacks.

**Comment by PNKBizz** [comment]
@NormanRDD залейте код на гитхаб и киньте ссылку

**Comment by NormanRDD** [comment]
> @NormanRDD залейте код на гитхаб и киньте ссылку

https://github.com/NormanRDD/yandexTest
Буду признателен, если так же поможешь реализовать получение адреса по нажатию на карту. (Обратное геокодирование)

**Comment by NormanRDD** [comment]
до меня только что дошло что я изначально по ошибке обратился не к тому пользователю :D

**Comment by NormanRDD** [comment]
> @NormanRDD залейте код на гитхаб и киньте ссылку
Здравствуйте, отпишите пожалуйста если решите проблему.
