### ISSUE TITLE
Как фильтровать маркеры при большом их количестве?

### ISSUE THREAD

**Issue by CubaJas** [PNKBizz/vue-yandex-map#82]
Сейчас я фильтрую реактивностью arr.filter(), но при 1600+ объектов видно заметное провисание при перерендеренге. Как правильно фильтровать в Вашем компоненте?

**Comment by PNKBizz** [comment]
Привет! Во-первых рекомендую вам использовать ObjectManager, если ещё не. В доке написано как включить. В остальном - все правильно. Вы сами фильтруете объекты.

**Comment by CubaJas** [comment]
Очень сильно провисает. Попробуйте 1600+ объектов. Как мне пользоваться ObjectManajer'ом в компоненте?  true то я выставил в свойство, что дальше?

**Comment by CubaJas** [comment]
Вот таким способом как-то можно? https://tech.yandex.ru/maps/jsbox/2.1/object_manager_filter

**Comment by PNKBizz** [comment]
@CubaJas постараюсь в ближайшее время добавить ссылку на создаваемый ObjectManager в качестве второго аргумента в событии инициализации карты
