### ISSUE TITLE
'offsetWidth' of null при перемещении

### ISSUE THREAD

**Issue by idegart** [PNKBizz/vue-yandex-map#85]
Добрый день!

Накодил следующее:
```
<yandex-map
    :coords="cityCoords"
    zoom="10"
    style="width: 100%; height: 600px;"
    :controls="['zoomControl']"
  >

    <ymap-marker
      v-if="coords"
      marker-type="placemark"
      :markerId="id"
      :coords="coords"
      :options="{draggable: true}"
      :callbacks="{dragend: changePosition}"
    ></ymap-marker>

  </yandex-map>
```

Все отлично работает до момента changePosition

Почему то когда я переставляю маркер, в момент его вставки на новое место возникает следующая ошибка: `Uncaught TypeError: Cannot read property 'offsetWidth' of null`

При этом это ошибка возникает раз через раз
То срабатывает, перезагружаю страницу и уже все норм
А бывает что и без перезагрузки все нормально работает

Почти уверен что что-то не так в классах блоков в которых находится карта, но что конкретно я не понимаю..

**Comment by PNKBizz** [comment]
Привет. Спасибо, посмотрю.

**Comment by artem0071** [comment]
За это время заметил что эта ошибка возникает не от changePosition а только в том случае, если карта находится в каком нибудь блоке с if оператором

Т.е. если карта находится в 
```
<div v-if="toRender">
  <yandex-map>
</div>
```

Причем независимо от того в каком положении этот `toRender` (true или false)
Но если убрать этот блок, то все работает нормально

Еще одно замечаение
Если сначала находится на page1 где нет карты, а затем перейти на page2 где есть карта, то возникнет та самая ошибка и карта не загрузится, но если при этом вернуться на page1 и затем снова на page2 то все будет работать нормально даже если там есть условный блок

Пробовал это все в codepen сделать, но там поему то и так все нормально работает :)

**Comment by artem0071** [comment]
Так, еще кое что понял
У меня в компоненте есть "слушатель"(использую Quasar-framework) изменения размера блока (чтобы карта нормально смотрелась (что ее и ломает собственно :с ))

Так вот, не знаю каким образом, но именно он и ломал карту в последнее время (уж не знаю чем.. весь код просмотрел, ничего не понял что там может вредить..)

Но с передвижением маркера проблема осталась (там я не использовал никаких слушателей)

**Comment by artem0071** [comment]
Так, спустя какое то время все равно возникает ошибка, даже если убрать слушателя
Уже ничего не понимаю что происходит с этими картами)

**Comment by LevonXXL** [comment]
Только что вылечил у себя похожую проблему. 
Карта загружалась раньше данных с сервера. 
сделал - <yandex-map v-if="dataLoaded" .... >
переменную dataLoaded ставлю true после загрузки данных, в которых помимо прочего координаты центра карты и координаты placemarks.

**Comment by zlodes** [comment]
Тут проблема как раз с условной отрисовкой.
Вот слегка изменённый CodePen: https://codepen.io/anon/pen/QPNJoM.

**Comment by christopherblack** [comment]
Была похожая ошибка, которая при этом еще и ломала роутинг на Nuxt (не отрисовывались страницы при навигации).
Помог такой вариант с условной отрисовкой:
```html
<template>
...
<yandex-map
        v-if="pageReady"
        :coords="[55.744586, 37.643624]"
        zoom="17">
        <ymap-marker
          marker-id="1"
          marker-type="placemark"
          :coords="[55.744586, 37.643624]"
          :icon="{color: 'red'}"
          cluster-name="1">
        </ymap-marker>
      </yandex-map>
</template>
```

```javascript
<script>
data() {
    return {
      pageReady: false
    }
},
mounted() {
    this.pageReady = true;
}
</script>
```

**Comment by chiralium** [comment]
> @PNKBizz @artem0071 такая же проблема при использовании маркеров через слот, при использовании пропса placemarks, проблема вроде не возникает.
> 
> ошибка возникала, при таких условиях, имеются две страницы с картой и со списком с пагинацией, в первой карте все работает нормально маркеры меняются при пагинации, после перехода на вторую страницу карта отрисовывается, проблема возникает после изменении пагинации.
> 
> использовал с nuxtjs

Привет, как ты это решил? Похоже, у меня такая же проблема.
