### ISSUE TITLE
Как получить список меток, которые в данный момент видны на карте?

### ISSUE THREAD

**Issue by CubaJas** [PNKBizz/vue-yandex-map#86]
Собственно сабж.

**Comment by CubaJas** [comment]
> со стороны клиента или сервера?

У меня на карте 1000+ меток, когда я приближаю, соответственно в видимой области N из этой тыщи видны. Есть ли возможность получить список этих меток в этом компоненте?

**Comment by tjslash** [comment]
```javascript
let filter = group.filter((obj) => {
    return this.map.getBounds().contains(obj.getGeoPoint());
});
```

**Comment by CubaJas** [comment]
group = new YMaps.GeoObjectCollection();
как получить YMaps из компонента?

**Comment by CubaJas** [comment]
> @CubaJas это глобальная переменная. Доступна после инициализации компонента.

@PNKBizz ок, я нашёл её. Далее проблема 
`let group = new ymaps.GeoObjectCollection();
		  let filter = group.filter((obj) => {
			return this.map.getBounds().contains(obj.getGeoPoint());
		  });
		  console.log(filter)`
Говорит group.filter is not a function что и понятно, судя по тому что group объект.

**Comment by mirecl** [comment]
Решили проблему?

**Comment by alexlibre** [comment]
Присоединяюсь к вопросу
