### ISSUE TITLE
Получить ссылку на GeoObject

### ISSUE THREAD

**Issue by ShishkinDmitriy** [PNKBizz/vue-yandex-map#89]
Добрый день,

Как получить доступ к конкретному маркеру, чтобы у него вызвать в дальнейшем `myPolygon.editor.startDrawing()`?

С уважением,
Шишкин Дмитрий

**Comment by kugimiya** [comment]
Такой же вопрос относительно placemarks, как мне получить доступ "куда-то туда", чтобы выбрать активный placemark?

**Comment by araimbekoff** [comment]
у маркера есть callbacks, в который можете воткнуть ваш хендлер.

**Comment by Adyletkhan1** [comment]
@araimbekoff  
`:callbacks="{click(){selectCourier('helloo')}}"`
 пробую, не работает, на маркер кликаю, ничего не выxодит


`    <ymap-marker v-for="courier in couriersWithRightCoords(couriers)"
                 :key="courier.id"
                 :marker-id="courier.id"
                 :icon="createIcon(courier)"
                 :callbacks="{click(){selectCourier(courier)}}"
                 :coords="[courier.latitude, courier.longitude]"
    ></ymap-marker>`

Пробовал в консоли выводит просто стринг, тоже не выводит, что можно сделать?

**Comment by PNKBizz** [comment]
@Adyletkhan1 сделайте пример в песочнице
