### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by stan-b** [PNKBizz/vue-yandex-map#9]
При загрузке страницы ругается на  Uncaught ReferenceError: process is not defined at vue-yandex-maps.js:328.

**Comment by PNKBizz** [comment]
А можете показать пример использования?

**Comment by stan-b** [comment]
Просто при включении:
<script src="https://unpkg.com/vue"></script>
<script src="node_modules/vue-yandex-maps/.js"></script>

М.б., не так надо делать, я вообще на Перле пишу, vue только вчера взял в руки )

**Comment by PNKBizz** [comment]
<script src="https://unpkg.com/vue"></script> - вот это уже не работает, к сожалению (
