### ISSUE TITLE
Переинциализация карты при показе/закрытии модального окна

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#91]
Всем привет!
Заметил очень неприятную вещь:
На странице, где есть экземпляр карты, открываю модальное окно. При открытии и закрытии срабатывает @map-was-initialized. 

Это Баг или Фича? 
Как можно убрать это поведение?

В проекте используется quasar-framework

**Comment by PNKBizz** [comment]
Привет!
Ну судя по всему у вас перерисовывается страница при открытии и закрытии окна. Я думаю, что дело не в карте )
