### ISSUE TITLE
центровка карты по имеющимся маркерам

### ISSUE THREAD

**Issue by araimbekoff** [PNKBizz/vue-yandex-map#92]
Имеется карта, с определенным множеством точек.
Как можно отцентровать и настроить зум таким образом, чтобы имеющееся множество вмещалось на экран?

**Comment by PNKBizz** [comment]
Привет!
После инициализации карта кидает событие `map-was-initialized` в котором payload - это инстанс карты. С ним вы можете работать по своему усмотрению.
