### ISSUE TITLE
Постоянное центрирование карты

### ISSUE THREAD

**Issue by webivan1** [PNKBizz/vue-yandex-map#93]
Привет, возникла проблема с картой. Вот так поставил:
`
<yandex-map
                        :coords="[parseFloat(build.lat), parseFloat(build.long)]"
                        :zoom="currentZoom"
                        style="width: 100%; height: 100%;"
                        :controls="[]"
                        :scroll-zoom="false"
                        :clusterOptions="{}"
                        @map-was-initialized="initMap"
                    ></yandex-map>
`

Далее в initMap определил коллекцию `this.collection = new ymaps.GeoObjectCollection();` и добавил в неё несколько полигонов, потом добавил всю коллекцию на карту
`this.map.geoObjects.add(this.collection); this.map.setBounds(this.collection.getBounds(), { checkZoomRange: true });`

Ещё к каждому полигону добавил event при наведении, чтобы менял цвет полигона:
`polygon.events.add('mouseenter', () => {
          polygon.options.set({
            fillOpacity: this.ActiveStyleSection.fill,
            strokeOpacity: this.ActiveStyleSection.stroke
          });
        });`

И проблема была в том что при каждом изменении полигона, то есть при наведение на него карта снова центрировалась в центре всех полигонов, куда бы я карту не сместил, наведу на полигон и снова поеду к центру. Я долго искал инфу как избавиться от этого бага, может где ивент какой стоит, но решил попробовать поставить карту с нуля через `ymaps.ready(...)` и баг исчез, то есть вероятно где-то в расширении есть проблема.

**Comment by AlexKu777** [comment]
Такая же проблема с определением координат по клику.
Вывожу маркер ранее отмеченых координат, по клику нахожу координаты, которые назначются маркеру. Но вместо того, чтобы передвинуть маркер, карта резко центрируется по новым координатам. И значение масштабирования тоже сбрасывается.

**Comment by xsen** [comment]
Это из за этого кода

```javascript
    watch: {
        coordinates(newVal) {
            this.myMap.panTo && this.myMap.panTo(newVal)
        },
....
    },
```

**Comment by MamatmurodovA** [comment]
проблема ещё не решена ?

**Comment by PNKBizz** [comment]
@MamatmurodovA можете воспроизвести кейс в песочнице?

**Comment by SergeyNekrasoff** [comment]
Как в итоге центрировать карту по кластеру или маркеру, на который кликнули?
У меня всегда центрируется по значению из coords компонента yandex-maps, в который я передаю координаты первого элемента массива placemarks.

`<yandex-map
    :coords="coords"
    :controls="[]"
    :zoom="zoom"
    ref="map"
    :class="{ 'map--expanded': expands }"
    @map-was-initialized="initHandler"
    :init-without-markers="false"
    :placemarks="placemarks"
    :options="{ 
      suppressMapOpenBlock: true,
      autoFitToViewport: 'always'
    }"
    :cluster-callbacks="{ '1': { click: getDataOfCluster }}"
    :cluster-options="{
      1: { 
        clusterDisableClickZoom: false, 
        hasBalloon: false 
      }}">
      <button 
        class="btn-expand-map" 
        @click="() => this.expands = !this.expands">
        Развернуть карту
      </button>
      <ymap-marker
        v-for="(location, index) in placemarks"
        :key="index"
        :marker-id="index"
        marker-type="placemark"
        :coords="location"
        :callbacks="{ click: getDataOfCoords }"
        cluster-name="1"
        :icon="{
          layout: 'default#image',
          imageHref: require('assets/svg/marker.svg'),
          imageSize: [27, 36],
          imageOffset: [-5, -15],
        }"></ymap-marker>
  </yandex-map>`

**Comment by PNKBizz** [comment]
@SergeyNekrasoff во-первых зачем вы задаете маркеры через `placemarks`, если их же дублируете через `<ymap-marker>`?
Во-вторых - сделайте песочницу с вашим кейсом, там все и будет понятно

**Comment by SergeyNekrasoff** [comment]
@PNKBizz, убрал placemarks. Попытался воспроизвести в codesandbox, но точки так и не показались, поэтому посмотрите пожалуйста сам компонент YandexMaps https://codesandbox.io/s/codesandbox-nuxt-j5vjy

**Comment by PNKBizz** [comment]
@SergeyNekrasoff у вас там очень много всего накручено. Убрал лишнее - все центруется. https://codesandbox.io/s/codesandbox-nuxt-ol0l2

**Comment by SergeyNekrasoff** [comment]
@PNKBizz, да центрируется отлично, но у меня там было два коллбека, один на маркер, другой на кластер.

Проблема в том, что нужно получать данные кликнув и на кластер и на метку. Сецчас работает только по метке, т.е кликнув по кластеру я не получаю данные. Когда добавляют :cluster-callback с тем же методом как у метки - getDataOfCoords, то данные приходят, но центр уплывает на на координаты :coords.

**Comment by PNKBizz** [comment]
@SergeyNekrasoff попробуйте удалить все лишнее и разобраться с колбэком на кластере, а потом и на маркере

**Comment by SergeyNekrasoff** [comment]
@PNKBizz, я же написал что на маркере все ок, а cluster-callback центрирует автоматом по координатам из coords, куда бы я не кликнул. Как отключить центрирование вообще?

Вот здесь более понятнее, попробуйте кликнуть на кластер или метку и увидите куда центрируется карта: https://codesandbox.io/s/codesandbox-nuxt-1ht4k (к точке из coords)

**Comment by PNKBizz** [comment]
@SergeyNekrasoff значит что-то заставляет карту перерисовываться по старым координатам. У вас в коде слишком много всего влияет на карту. Попробуйте сделать с нуля, постепенно добавляя нужный функционал

**Comment by PNKBizz** [comment]
@SergeyNekrasoff по ссылке https://codesandbox.io/s/codesandbox-nuxt-1ht4k кластеры центрируются ок

**Comment by SergeyNekrasoff** [comment]
@PNKBizz, короче это проблема не в картах, а в том что компонент карт у меня дочерний компонент, и при отправке запроса - карта перерисовывается и центрируется, поэтому сорри))
