### ISSUE TITLE
Uncaught TypeError: Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by eugenepro2** [PNKBizz/vue-yandex-map#98]
Вылазит ошибка Uncaught TypeError: Cannot read property 'offsetWidth' of null
Фреймоврк NUXT.JS

При этом карта работает. Но из-за этой ошибки возвращение обратно на страницу с картой крашит страницу. Что может быть?

**Comment by PNKBizz** [comment]
Попробуй https://github.com/PNKBizz/vue-yandex-map/issues/53#issuecomment-377427410

**Comment by eugenepro2** [comment]
Решено!
