### ISSUE TITLE
После выхода из режима fullscreen - неправильная ширина.

### ISSUE THREAD

**Issue by azhirov** [PNKBizz/vue-yandex-map#99]
Заметил, что после закрытия карты с помощью стандартной кнопки выхода из fullscreen, устанавливается ширина элемента:
#yandexMap75339 > ymaps > ymaps

равная ширине окна. Причем это задается в атрибуте style, и переопределить я никак не могу.

При закрытии по Esc - карта вообще исчезает.
Прошу помощи.

**Comment by PNKBizz** [comment]
Не воспроизвел. Сделайте пример в песочнице.
